### ISSUE TITLE
404 error when downloading OpenImages dataset using fiftyOne v0.10.0

### ISSUE THREAD

**Issue by srikanthnadella** [voxel51/fiftyone#1080]
I am trying to download OpenImages dataset without much success. I have been getting an error as shown below when executing the following statement. I am using version 0.10.0 on Python 3.6.7 64-bot on macOS version 10.15.7
```
dataset =fiftyone.zoo.load_zoo_dataset(
    "open-images-v6", split="validation", max_samples=50)
```

Error Output:
```
Downloading split 'validation' to '/Users/srikanth.nadella/fiftyone/open-images-v6/validation'
Downloading validation samples
   0% ||------------------|  0/50 [528.7ms elapsed, ? remaining, ? samples/s] 
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/srikanth.nadella/anaconda3/envs/hfc/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/srikanth.nadella/anaconda3/envs/hfc/lib/python3.6/site-packages/fiftyone/utils/openimages.py", line 1577, in _do_s3_download
    s3_client.download_file(_BUCKET_NAME, filepath_download, filepath)
  File "/Users/srikanth.nadella/.local/lib/python3.6/site-packages/boto3/s3/inject.py", line 172, in download_file
    extra_args=ExtraArgs, callback=Callback)
  File "/Users/srikanth.nadella/.local/lib/python3.6/site-packages/boto3/s3/transfer.py", line 307, in download_file
    future.result()
  File "/Users/srikanth.nadella/anaconda3/envs/hfc/lib/python3.6/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/Users/srikanth.nadella/anaconda3/envs/hfc/lib/python3.6/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/Users/srikanth.nadella/anaconda3/envs/hfc/lib/python3.6/site-packages/s3transfer/tasks.py", line 255, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/Users/srikanth.nadella/anaconda3/envs/hfc/lib/python3.6/site-packages/s3transfer/download.py", line 345, in _submit
    **transfer_future.meta.call_args.extra_args
  File "/Users/srikanth.nadella/.local/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/srikanth.nadella/.local/lib/python3.6/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
"""

The above exception was the direct cause of the following exception:

ClientError                               Traceback (most recent call last)
<ipython-input-44-3f5a506fd2f7> in <module>
      1 dataset = foz.load_zoo_dataset(
----> 2     "open-images-v6", split="validation", max_samples=50
      3 )

~/anaconda3/envs/hfc/lib/python3.6/site-packages/fiftyone/zoo/datasets/__init__.py in load_zoo_dataset(name, split, splits, dataset_name, dataset_dir, download_if_necessary, drop_existing_dataset, overwrite, cleanup, **kwargs)
    193             overwrite=overwrite,
    194             cleanup=cleanup,
--> 195             **download_kwargs
    196         )
    197         zoo_dataset = info.get_zoo_dataset()

~/anaconda3/envs/hfc/lib/python3.6/site-packages/fiftyone/zoo/datasets/__init__.py in download_zoo_dataset(name, split, splits, dataset_dir, overwrite, cleanup, **kwargs)
    118         splits=splits,
    119         overwrite=overwrite,
--> 120         cleanup=cleanup,
    121     )
    122 

~/anaconda3/envs/hfc/lib/python3.6/site-packages/fiftyone/zoo/datasets/__init__.py in download_and_prepare(self, dataset_dir, split, splits, overwrite, cleanup)
    949                     num_samples,
    950                     classes,
--> 951                 ) = self._download_and_prepare(split_dir, scratch_dir, split)
    952 
    953                 # Add split to ZooDatasetInfo

~/anaconda3/envs/hfc/lib/python3.6/site-packages/fiftyone/zoo/datasets/base.py in _download_and_prepare(self, dataset_dir, scratch_dir, split)
    994             shuffle=self.shuffle,
    995             seed=self.seed,
--> 996             max_samples=self.max_samples,
    997         )
    998         dataset_type = fot.OpenImagesV6Dataset()

~/anaconda3/envs/hfc/lib/python3.6/site-packages/fiftyone/utils/openimages.py in download_open_images_split(dataset_dir, split, label_types, classes, attrs, image_ids, image_ids_file, num_workers, version, shuffle, seed, max_samples)
    534         max_samples,
    535         shuffle,
--> 536         num_workers,
    537     )
    538 

~/anaconda3/envs/hfc/lib/python3.6/site-packages/fiftyone/utils/openimages.py in _load_open_images_split(label_types, guarantee_all_types, split_image_ids, downloaded_ids, classes_map, attrs_map, oi_classes, oi_attrs, seg_classes, dataset_dir, split, classes, max_samples, shuffle, num_workers)
   1272         return 0
   1273 
-> 1274     _download_specific_images(valid_ids, split, dataset_dir, num_workers)
   1275 
   1276     if "segmentations" in label_types:

~/anaconda3/envs/hfc/lib/python3.6/site-packages/fiftyone/utils/openimages.py in _download_specific_images(valid_ids, split, dataset_dir, num_workers, ext)
   1561     with fou.ProgressBar(total=len(inputs)) as pb:
   1562         with multiprocessing.Pool(num_workers, _initialize_worker) as pool:
-> 1563             for _ in pool.imap_unordered(_do_s3_download, inputs):
   1564                 pb.update()
   1565 

~/anaconda3/envs/hfc/lib/python3.6/multiprocessing/pool.py in next(self, timeout)
    759         if success:
    760             return value
--> 761         raise value
    762 
    763     __next__ = next                    # XXX

ClientError: An error occurred (404) when calling the HeadObject operation: Not Found

```

**Comment by srikanthnadella** [comment]
I realized that I had the wrong AWS account configured in my awscli. Changing to the correct account fixed this issue.
