### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by emielsteerneman** [voxel51/fiftyone#1103]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04.2 LTS
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: fiftyone v0.11.1, Voxel51, Inc.
-   **Python version**: Python 3.7.10

### Describe the problem
When the data is being downloaded, a number of errors randomly occur. The training set is being downloaded without problems, but when downloading the test set, after having a few images downloaded successfully, the code crashes. The stripped down error looks like this:

```
Uncaught exception
multiprocessing.pool.RemoteTraceback: 
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f52d0766790>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:
requests.exceptions.ConnectionError: HTTPConnectionPool(host='images.cocodataset.org', port=80): Max retries exceeded with url: /train2017/000000000962.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52d0766790>: Failed to establish a new connection: [Errno -2] Name or service not known'))

The above exception was the direct cause of the following exception:
requests.exceptions.ConnectionError: None: Max retries exceeded with url: /train2017/000000000962.jpg (Caused by None)
```

When running the same code again, the download of the test set is resumed, but again crashes after just a handful of images. Every time, it crashes on a different image. I assume that I would be able to download the entire test set by running the code a few hundred times.

### Code to reproduce issue
```
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset(
    "coco-2017", splits=["train", "test"],
    classes=["person", "dog", "car", "clock", "horse"],
    only_matching=True,
    max_samples=1000
)
```
### Other info / logs

```
Downloading split 'train' to '/home/gebruiker/fiftyone/coco-2017/train'
Found annotations at '/home/gebruiker/fiftyone/coco-2017/raw/instances_train2017.json'
93 images found; downloading the remaining 907
   1% |█\--------------------------------------------------------------------------------------------------------------------------------|  13/907 [1.5s elapsed, 1.7m remaining, 9.8 samples/s]     
Uncaught exception
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/gebruiker/anaconda3/envs/deep4drone/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/gebruiker/anaconda3/envs/deep4drone/lib/python3.7/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/gebruiker/anaconda3/envs/deep4drone/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gebruiker/anaconda3/envs/deep4drone/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/gebruiker/anaconda3/envs/deep4drone/lib/python3.7/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/gebruiker/anaconda3/envs/deep4drone/lib/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/gebruiker/anaconda3/envs/deep4drone/lib/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/gebruiker/anaconda3/envs/deep4drone/lib/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/gebruiker/anaconda3/envs/deep4drone/lib/python3.7/http/client.py", line 1032, in _send_output
    self.send(msg)
  File "/home/gebruiker/anaconda3/envs/deep4drone/lib/python3.7/http/client.py", line 972, in send
    self.connect()
  File "/home/gebruiker/anaconda3/envs/deep4drone/lib/python3.7/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/home/gebruiker/anaconda3/envs/deep4drone/lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f52d0766790>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gebruiker/anaconda3/envs/deep4drone/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/gebruiker/anaconda3/envs/deep4drone/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/gebruiker/anaconda3/envs/deep4drone/lib/python3.7/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='images.cocodataset.org', port=80): Max retries exceeded with url: /train2017/000000000962.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52d0766790>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gebruiker/anaconda3/envs/deep4drone/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/gebruiker/anaconda3/envs/deep4drone/lib/python3.7/site-packages/fiftyone/utils/coco.py", line 1743, in _do_download
    etaw.download_file(url, path=path, quiet=True)
  File "/home/gebruiker/anaconda3/envs/deep4drone/lib/python3.7/site-packages/eta/core/web.py", line 67, in download_file
    return sess.write(path, url) if path else sess.get(url)
  File "/home/gebruiker/anaconda3/envs/deep4drone/lib/python3.7/site-packages/eta/core/web.py", line 147, in write
    r = self._get_streaming_response(url, params=params)
  File "/home/gebruiker/anaconda3/envs/deep4drone/lib/python3.7/site-packages/eta/core/web.py", line 158, in _get_streaming_response
    verify=self.verify,
  File "/home/gebruiker/anaconda3/envs/deep4drone/lib/python3.7/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/home/gebruiker/anaconda3/envs/deep4drone/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/gebruiker/anaconda3/envs/deep4drone/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/gebruiker/anaconda3/envs/deep4drone/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='images.cocodataset.org', port=80): Max retries exceeded with url: /train2017/000000000962.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52d0766790>: Failed to establish a new connection: [Errno -2] Name or service not known'))
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "testDataLoading.py", line 17, in <module>
    max_samples=1000
  File "/home/gebruiker/anaconda3/envs/deep4drone/lib/python3.7/site-packages/fiftyone/zoo/datasets/__init__.py", line 201, in load_zoo_dataset
    **download_kwargs,
  File "/home/gebruiker/anaconda3/envs/deep4drone/lib/python3.7/site-packages/fiftyone/zoo/datasets/__init__.py", line 121, in download_zoo_dataset
    cleanup=cleanup,
  File "/home/gebruiker/anaconda3/envs/deep4drone/lib/python3.7/site-packages/fiftyone/zoo/datasets/__init__.py", line 1002, in download_and_prepare
    ) = self._download_and_prepare(split_dir, scratch_dir, split)
  File "/home/gebruiker/anaconda3/envs/deep4drone/lib/python3.7/site-packages/fiftyone/zoo/datasets/base.py", line 813, in _download_and_prepare
    scratch_dir=scratch_dir,
  File "/home/gebruiker/anaconda3/envs/deep4drone/lib/python3.7/site-packages/fiftyone/utils/coco.py", line 1383, in download_coco_dataset_split
    dry_run=False,
  File "/home/gebruiker/anaconda3/envs/deep4drone/lib/python3.7/site-packages/fiftyone/utils/coco.py", line 1580, in _download_coco_dataset_split
    _download_images(images_dir, download_ids, images, num_workers)
  File "/home/gebruiker/anaconda3/envs/deep4drone/lib/python3.7/site-packages/fiftyone/utils/coco.py", line 1737, in _download_images
    for _ in pool.imap_unordered(_do_download, tasks):
  File "/home/gebruiker/anaconda3/envs/deep4drone/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
requests.exceptions.ConnectionError: None: Max retries exceeded with url: /train2017/000000000962.jpg (Caused by None)
```

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core `fiftyone` Python library issue
-   [x] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

**Comment by brimoor** [comment]
Hi @emielsteerneman 👋 

By default, the implementation uses `multiprocessing.cpu_count()` parallel processes to download the images. Perhaps this is resulting in too many connections for you? It never fails in any environment we've tested in...

You can configure the number of processes used by passing the optional `num_workers` parameter to `load_zoo_dataset()`. Can you check if `num_workers=1` works more reliably for you?

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset(
    "coco-2017", 
    split="train",
    classes=["person", "dog", "car", "clock", "horse"],
    only_matching=True,
    max_samples=1000,
    num_workers=1,
)
```

The implementation of the image download is here:
https://github.com/voxel51/fiftyone/blob/94ce6bebac6df848547228869a7825a9e8e67595/fiftyone/utils/coco.py#L1716-L1738.

If `num_workers` doesn't help, perhaps you can investigate what changes might help there?

By the way, once you get past the connection error, you'll see another error that results from trying to provide a `classes` requirement for the test split, which is unlabeled. #1105 tweaks the implementation to print a warning rather than raise an error in that case, but I'd recommend either:

- using the `validation` split instead if you want images with those classes, or
- if you just want to load some random test images, do this:

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset(
    "coco-2017", 
    split="train",
    classes=["person", "dog", "car", "clock", "horse"],
    dataset_name="coco-2017-sample",
    only_matching=True,
    max_samples=1000,
)

tmp = foz.load_zoo_dataset("coco-2017", split="test", max_samples=1000)
dataset.add_collection(tmp)
tmp.delete()

print(dataset)
```

**Comment by emielsteerneman** [comment]
Hello @brimoor,

Thank you for your suggestions. Having too many connections open does indeed sound like a plausible cause. I will test your suggestions next week, on July the 15th. I'll post the results here when I have them.

**Comment by emielsteerneman** [comment]
Hello @brimoor,

Unfortunately, settings `num_workers = 1` did not fix the problem. Even with a single worker, the crashes still occur. I decided do dig a little deeper into the problem, and the exceptions always occur at `./anaconda3/envs/my_environment/lib/python3.7/socket.py`, in the function `getaddrinfo`:

```
def getaddrinfo(host, port, family=0, type=0, proto=0, flags=0):
    addrlist = []
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
        af, socktype, proto, canonname, sa = res
        addrlist.append((_intenum_converter(af, AddressFamily),
                         _intenum_converter(socktype, SocketKind),
                         proto, canonname, sa))
    return addrlist
``` 

Given the same arguments, this function sometimes works, sometimes crashes, indicating that the error lies somewhere outside of this function. So, I decided to add my own little cache.

```
my_custom_cache = None

def getaddrinfo(host, port, family=0, type=0, proto=0, flags=0):
    addrlist = []
    
    global my_custom_cache
    if host == "images.cocodataset.org" and my_custom_cache is not None:
        return my_custom_cache

    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
        af, socktype, proto, canonname, sa = res
        addrlist.append((_intenum_converter(af, AddressFamily),
                         _intenum_converter(socktype, SocketKind),
                         proto, canonname, sa))
    
    if host == "images.cocodataset.org":
        my_custom_cache = addrlist

    return addrlist
```

Now, the errors don't occur anymore, and I can download the COCO dataset in one go. I'm not sure why this cache fixes the issue, but I assume that somewhere I'm annoying a DNS server, which at some point decides to ignore my repetitious requests.
Since `socket.py` comes with the python installation, it seems that the error has nothing to do with Fiftyone, and I think the issue can be closed.
