### ISSUE TITLE
[BUG] Open-images-v6 download check does not include metadata

### ISSUE THREAD

**Issue by collinmccarthy** [voxel51/fiftyone#1129]
### Instructions

I downloaded the OpenImages-V6 dataset the first time like this, by accident (using `download_zoo_dataset` instead of `load_zoo_dataset`):

```python
fiftyone.zoo.datasets.download_zoo_dataset(
        name='open-images-v6',
        dataset_dir='~/data/open-images-v6',
        label_types='classifications',
        num_workers=8
    )
```

I ended up downloading the whole dataset, which is fine. But I noticed I only had `classifications.csv`. So I tried to download the rest, figuring I could use `download_zoo_dataset` again.

```python
fiftyone.zoo.datasets.download_zoo_dataset(
        name='open-images-v6',
        dataset_dir='~/data/open-images-v6',
        label_types=['detections','classifications','relationships','segmentations']
        num_workers=8
    )
```

gave the output:

```console
Split 'train' already downloaded
Split 'test' already downloaded
Split 'validation' already downloaded
```

Okay great, so then I tried to load it:

```python
fiftyone.zoo.datasets.load_zoo_dataset(
        name='open-images-v6',
        dataset_dir='~/data/open-images-v6',
        label_types=['detections','classifications','relationships','segmentations'],
        num_workers=8
    )
```

But I got an output such as this:

```console
Split 'train' already downloaded                                                                                                          Split 'test' already downloaded
Split 'validation' already downloaded                                                                                                     Loading 'open-images-v6' split 'train'                                                                                                    Uncaught exception
Uncaught exception
Traceback (most recent call last):
  File "/home/collin_m_mccarthy/torchvx/utils/fiftyone_download.py", line 60, in <module>
    download_dataset(config)
  File "/home/collin_m_mccarthy/torchvx/utils/fiftyone_download.py", line 42, in download_dataset
    fiftyone.zoo.datasets.load_zoo_dataset(
  File "/home/collin_m_mccarthy/.conda/envs/torchvx/lib/python3.9/site-packages/fiftyone/zoo/datasets/__init__.py", line 273, in load_zoo_dataset
    dataset.add_importer(
  File "/home/collin_m_mccarthy/.conda/envs/torchvx/lib/python3.9/site-packages/fiftyone/core/dataset.py", line 2755, in add_importer
    return foud.import_samples(
  File "/home/collin_m_mccarthy/.conda/envs/torchvx/lib/python3.9/site-packages/fiftyone/utils/data/importers.py", line 107, in import_samples
    with dataset_importer:
  File "/home/collin_m_mccarthy/.conda/envs/torchvx/lib/python3.9/site-packages/fiftyone/utils/data/importers.py", line 694, in __enter__
    self.setup()
  File "/home/collin_m_mccarthy/.conda/envs/torchvx/lib/python3.9/site-packages/fiftyone/utils/openimages.py", line 260, in setup
    ) = _setup(
  File "/home/collin_m_mccarthy/.conda/envs/torchvx/lib/python3.9/site-packages/fiftyone/utils/openimages.py", line 722, in _setup
    attrs_map = _get_attrs_map(dataset_dir, download=download)
  File "/home/collin_m_mccarthy/.conda/envs/torchvx/lib/python3.9/site-packages/fiftyone/utils/openimages.py", line 792, in _get_attrs_map    attrs_csv = _get_general_metadata_file(
  File "/home/collin_m_mccarthy/.conda/envs/torchvx/lib/python3.9/site-packages/fiftyone/utils/openimages.py", line 785, in _get_general_metadata_file
    _download_file_if_necessary(filepath, url, quiet=0, download=download)
  File "/home/collin_m_mccarthy/.conda/envs/torchvx/lib/python3.9/site-packages/fiftyone/utils/openimages.py", line 1590, in _download_file_if_necessary
    raise ValueError("File '%s' is not downloaded" % filepath)
ValueError: File '/home/collin_m_mccarthy/data/open-images-v6/train/metadata/attributes.csv' is not downloaded
```

It looks like when it checks to see if everything is downloaded it's not checking to make sure the metadata is downloaded as well. I believe it should, so at a minimum `load_zoo_dataset` works correctly and downloads it automatically if it is not.  Based on the documentation it sounds like that's how it's supposed to work?

Thank you,
Collin

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [X] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [X] No. I cannot contribute a bug fix at this time.

**Comment by ehofesmann** [comment]
Hi @collinmccarthy!

Yes, the workflow you are performing should work, I'll take a closer look at what is going on and resolve this issue. 

In the meantime, you should be able to force a redownload of the missing metadata files by deleting the `info.json` file found at `~/data/open-images-v6/info.json` and then running the following:
```python
fiftyone.zoo.datasets.download_zoo_dataset(
        name='open-images-v6',
        dataset_dir='~/data/open-images-v6',
        splits=["train", "test", "validation"],
        label_types=['detections','classifications','relationships','segmentations']
        num_workers=8
    )
```
