### ISSUE TITLE
FiftyOne: Loading 'coco-2017' split 'test' Error: Uncaught exception, AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by nagarjunvinukonda** [voxel51/fiftyone#1157]
Hi,

I am trying to download COCO-2017 Test dataset. But during download using fiftyone I am facing an exception error and I didn't get the labels for the images to get downloaded.

I am using the following code:

```
import fiftyone as fo
import fiftyone.zoo as foz 

dataset = foz.load_zoo_dataset(
              "coco-2017",
              split="test",
              label_types=["detections"],
              classes=["dog"],
          )
```

I am able to download validation and train without a problem. The test data images are able to be downloaded but I didn't find its image annotation files that provides bounding boxes coordinates. The only things that are downloaded in raw folder with test  data are: "image_info_test-dev2017.json" and "image_info_test2017.json", which doesn't consists of test data images bounding box coordinates. 

The following is the error after I run the command:

```
/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Downloading split 'test' to '/home/midearobotintern/fiftyone/coco-2017/test'
Test split is unlabeled; ignoring `classes`
Downloading test info to '/home/midearobotintern/fiftyone/coco-2017/tmp-download/image_info_test2017.zip'
 100% |██████████████████████████████████████████████|    8.7Mb/8.7Mb [449.8ms elapsed, 0s remaining, 19.4Mb/s]      
Extracting test info to '/home/midearobotintern/fiftyone/coco-2017/raw/image_info_test2017.json'
Downloading images to '/home/midearobotintern/fiftyone/coco-2017/tmp-download/test2017.zip'
 100% |█████████████████████████████████████████████|   49.5Gb/49.5Gb [4.4m elapsed, 0s remaining, 224.0Mb/s]      
Extracting images to '/home/midearobotintern/fiftyone/coco-2017/test/data'
Writing annotations to '/home/midearobotintern/fiftyone/coco-2017/test/labels.json'
Dataset info written to '/home/midearobotintern/fiftyone/coco-2017/info.json'
Loading 'coco-2017' split 'test'
Uncaught exception
Traceback (most recent call last):
  File "/home/midearobotintern/download_images.py", line 13, in <module>
    classes=["dog"],
  File "/home/midearobotintern/.local/lib/python3.6/site-packages/fiftyone/zoo/datasets/__init__.py", line 274, in load_zoo_dataset
    dataset_importer, label_field=_label_field, tags=[split]
  File "/home/midearobotintern/.local/lib/python3.6/site-packages/fiftyone/core/dataset.py", line 2761, in add_importer
    add_info=add_info,
  File "/home/midearobotintern/.local/lib/python3.6/site-packages/fiftyone/utils/data/importers.py", line 107, in import_samples
    with dataset_importer:
  File "/home/midearobotintern/.local/lib/python3.6/site-packages/fiftyone/utils/data/importers.py", line 694, in __enter__
    self.setup()
  File "/home/midearobotintern/.local/lib/python3.6/site-packages/fiftyone/utils/coco.py", line 497, in setup
    max_samples=self.max_samples,
  File "/home/midearobotintern/.local/lib/python3.6/site-packages/fiftyone/utils/coco.py", line 1678, in _get_matching_image_ids
    image_ids, annotations, classes, all_classes
  File "/home/midearobotintern/.local/lib/python3.6/site-packages/fiftyone/utils/coco.py", line 1762, in _get_images_with_classes
    coco_objects = annotations.get(image_id, None)
AttributeError: 'NoneType' object has no attribute 'get'
```

Please help me solve this problem.

**Comment by brimoor** [comment]
Upgrading to the latest version of FiftyOne should resolve the `AttributeError`:

```shell
pip install --upgrade fiftyone
```

But please note the important line from the logging output in your stack trace:

```
Test split is unlabeled; ignoring `classes`
```

The COCO authors did not make the annotations for the test split publicly available for download. So, you can load the test split using the syntax you showed (after upgrading to avoid the error per above), but it won't contain labels.
