### ISSUE TITLE
[FR] Add support for proxies when downloading files served by Google Drive

### ISSUE THREAD

**Issue by lujx1024** [voxel51/fiftyone#1163]
### Instructions

I tried to download a dataset for training and I was suggested using Fiftyone, so I went through the tutorial and made a quickstart script after I installed this library.

I got a **Timeout** error because I couldn't connect to the google drive from where I am because the stupid thing called "The Great Fire Wall" ,aka "GFW", blocked my connect to any google service.

So I was thinking if could please **add a parameter like Proxy** and transend to the "requests" library so that I  the users can connect website which was blocked via proxy ?

### Proposal Summary

- Add a proxy parameter support to function like `load_zoo_dataset ( )`

### Motivation

-   if fiftyone support network connection via proxy, it will help hundreds of thousands developers who live in an specific region or country where the internet was not that opened such as China mainland.

### Details

My Error Log like below
```
Downloading dataset to 'C:\Users\lujx\fiftyone\quickstart'
Downloading dataset...
Uncaught exception
Traceback (most recent call last):
  File "E:\workon_home\quickstart\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "E:\workon_home\quickstart\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "E:\workon_home\quickstart\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/project_python/learning/fiftyone-test/fiftyone_downloader.py", line 8, in <module>
    dataset = foz.load_zoo_dataset("quickstart")
  File "E:\workon_home\quickstart\lib\site-packages\fiftyone\zoo\datasets\__init__.py", line 201, in load_zoo_dataset
    **download_kwargs,
  File "E:\workon_home\quickstart\lib\site-packages\fiftyone\zoo\datasets\__init__.py", line 121, in download_zoo_dataset
    cleanup=cleanup,
  File "E:\workon_home\quickstart\lib\site-packages\fiftyone\zoo\datasets\__init__.py", line 1065, in download_and_prepare
    ) = self._download_and_prepare(dataset_dir, scratch_dir, None)
  File "E:\workon_home\quickstart\lib\site-packages\fiftyone\zoo\datasets\base.py", line 1323, in _download_and_prepare
    scratch_dir,
  File "E:\workon_home\quickstart\lib\site-packages\fiftyone\zoo\datasets\base.py", line 1554, in _download_and_extract_archive
    etaw.download_google_drive_file(fid, path=archive_path)
  File "E:\workon_home\quickstart\lib\site-packages\eta\core\web.py", line 88, in download_google_drive_file
    return sess.write(path, fid) if path else sess.get(fid)
  File "E:\workon_home\quickstart\lib\site-packages\eta\core\web.py", line 195, in write
    path, self.BASE_URL, params={"id": fid}
  File "E:\workon_home\quickstart\lib\site-packages\eta\core\web.py", line 147, in write
    r = self._get_streaming_response(url, params=params)
  File "E:\workon_home\quickstart\lib\site-packages\eta\core\web.py", line 203, in _get_streaming_response
    url, headers={"Range": "bytes=0-"}, params=params
  File "E:\workon_home\quickstart\lib\site-packages\eta\core\web.py", line 158, in _get_streaming_response
    verify=self.verify,
  File "E:\workon_home\quickstart\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "E:\workon_home\quickstart\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\workon_home\quickstart\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "E:\workon_home\quickstart\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1UWTlFmdq8H-wdJHxVsAKpXBilY1CWwm_ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002ACA507A3C8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))

Process finished with exit code 1

```

**Comment by brimoor** [comment]
Hi @lujx1024 :wave: 

Good news, @ErfanTagh is taking a look into this in https://github.com/voxel51/eta/pull/520. Any chance you can try it out? Any suggestions for best practices when working with proxies would also be much appreciated.

You should be able to setup a test environment by doing a [source install](https://github.com/voxel51/fiftyone#installing-from-source of FiftyOne) and then a source install of the ETA library (a separate library where our download code lives):

```shell
# Source install of FiftyOne
git clone https://github.com/voxel51/fiftyone
cd fiftyone
bash install.bash

# Source install of https://github.com/voxel51/eta/pull/520
git clone https://github.com/ErfanTagh/eta
cd eta
git checkout develop
pip install -e .
```

**Comment by lujx1024** [comment]
Thank you for effort and sorry for taking so long , I was think that make you can let users pre-define a variable proxies like `proxies={"http":"http://127.0.0.1:10809","https":"https://127.0.0.1:10809"}`, and then transend this variable as an argument to the method just once before build connections.

About your suggestion that setup a test enviroment by doing a source install , I followed your tutorial and get it done , but when I  tried to run code like this , I got an RuntimeError :
```
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
session = fo.launch_app(dataset)
```
**The error infomation will be in the bottom of this comment.**

I don't know if it's relevant the platform or version of software that I can't run the code , So I'm gonna list ly envirment so you can check it ：
- OS : Windows 10 
- python version : Python 3.6.8

BTW, I've seen the solution mentionde in  [voxel51/eta#520](https://github.com/voxel51/eta/pull/520) , it get the system proxies instead of set an proxies parameter, but unfortunately I could test it because the RuntimeError. So if you see this , Please tell me more specific , and I feel sorry for I couldn't do more and couldn't offer you more information as I want.

Here is the Error info:
```
Uncaught exception
Traceback (most recent call last):
  File "fiftyone_downloader.py", line 3, in <module>
    import fiftyone as fo
  File "E:\workon_home\fiftyone_test\lib\site-packages\fiftyone-0.11.2.1-py3.6.egg\fiftyone\__init__.py", line 25, in <module>
    from fiftyone.__public__ import *
  File "E:\workon_home\fiftyone_test\lib\site-packages\fiftyone-0.11.2.1-py3.6.egg\fiftyone\__public__.py", line 11, in <module>
    _database_service = fos.DatabaseService()
  File "E:\workon_home\fiftyone_test\lib\site-packages\fiftyone-0.11.2.1-py3.6.egg\fiftyone\core\service.py", line 203, in __init__
    super().__init__()
  File "E:\workon_home\fiftyone_test\lib\site-packages\fiftyone-0.11.2.1-py3.6.egg\fiftyone\core\service.py", line 81, in __init__
    self.start()
  File "E:\workon_home\fiftyone_test\lib\site-packages\fiftyone-0.11.2.1-py3.6.egg\fiftyone\core\service.py", line 288, in start
    super().start()
  File "E:\workon_home\fiftyone_test\lib\site-packages\fiftyone-0.11.2.1-py3.6.egg\fiftyone\core\service.py", line 232, in start
    super().start()
  File "E:\workon_home\fiftyone_test\lib\site-packages\fiftyone-0.11.2.1-py3.6.egg\fiftyone\core\service.py", line 119, in start
    + self.command,
  File "E:\workon_home\fiftyone_test\lib\site-packages\fiftyone-0.11.2.1-py3.6.egg\fiftyone\core\service.py", line 265, in command
    DatabaseService.find_mongod(),
  File "E:\workon_home\fiftyone_test\lib\site-packages\fiftyone-0.11.2.1-py3.6.egg\fiftyone\core\service.py", line 372, in find_mongod
    "Could not find mongod>=%s" % DatabaseService.MIN_MONGO_VERSION
RuntimeError: Could not find mongod>=4.4
```

**Comment by brimoor** [comment]
The error you're seeing is indicating that, for some reason, your MongoDB installation cannot be found. FiftyOne uses MongoDB as its database, which is installed when the `fiftyone-db` package is installed in [this line](https://github.com/voxel51/fiftyone/blob/a8f52fa278540565481dd584588773225333663c/install.bash#L95) of the install script that you ran.

Did you see any errors or anything like that? Try running `pip install fiftyone-db` again to see what happens.

All that FiftyOne needs is to be able to locate the `mongod` executable anywhere on your system path. So, you could also just try [installing MongoDB yourself](https://docs.mongodb.com/manual/tutorial/install-mongodb-on-windows/).

**Comment by brimoor** [comment]
> Thank you for your effort and sorry for taking so long , I was think that make you can let users pre-define a variable proxies like `proxies={"http":"http://127.0.0.1:10809","https":"https://127.0.0.1:10809"}`, and then transend this variable as an argument to the method just once before build connections.

Okay I looked into this myself just now and, since all web downloads in FiftyOne should be happening via the `requests` module in some form or another, the [requests package docs](https://2.python-requests.org/en/latest/user/advanced/#proxies) indicate that you can just set some environment variables and then your proxies will be used by default by `requests` everywhere:

```shell
export HTTP_PROXY="http://127.0.0.1:10809"
export HTTPS_PROXY="https://127.0.0.1:10809"
```

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
session = fo.launch_app(dataset)
```

**Comment by lujx1024** [comment]
Yes It Works.  I really Appreciate your sffort on this !

For Those who are using Windows operating system instead of Linux ：
```
set HTTP_PROXY=http://127.0.0.1:12333
set HTTPS_PROXY=http://127.0.0.1:12333
```
if you need username or password to access your proxy （ignore this if you don't need a password）:
```
set HTTP_PROXY=http://proxy.com:port
set HTTP_PROXY_USER=username
set HTTP_PROXY_PASS=password

set HTTPS_PROXY=http://proxy.com:port
set HTTPS_PROXY_USER=username
set HTTPS_PROXY_PASS=password
```
run the script
```
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")  # should work now
session = fo.launch_app(dataset)
```
Noted that all those codes should run in the CMD terminal and no need to worry about the enviroment variable , it's not permanent, they will be just effective just before the terminal was closed.

**Comment by lujx1024** [comment]
@brimoor Thank you for your support , and now since my problem has been solved , should I close this issue ? Sorry I don't really know about the rules.
