### ISSUE TITLE
[SETUP-BUG] Installation Error for Mac (macOs 0.15.7)

### ISSUE THREAD

**Issue by awandzel** [voxel51/fiftyone#1203]
### Instructions

Thank you for submitting an issue. Please refer to our
[issue policy](https://www.github.com/voxel51/fiftyone/blob/develop/ISSUE_POLICY.md)
for information on what types of issues we address.

**Please fill in this template to ensure a timely and thorough response.**

-   Place an "x" between the brackets next to an option if it applies. Example:
    -   [x] Selected option
-   Please delete this section (all content above this line) before submitting
    the issue

### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS 10.15.7 Catalina 
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: fiftyone v0.12.0, Voxel51, Inc.
-   **Python version**: 3.6.10

### Commands to reproduce

As thoroughly as possible, please provide the Python and/or shell commands used
to encounter the issue.

```
import fiftyone as fo   #<-- works fine
session = fo.launch_app()  #<-- error
```

### Describe the problem
Followed vanilla download instructions on website (https://voxel51.com/docs/fiftyone/getting_started/install.html) resulting in failure; cannot launch app. 

Provide the exact sequence of commands / steps that you executed before running
into the problem.

### Other info / logs

Uncaught exception
Traceback (most recent call last):
  File "/opt/anaconda3/envs/EF/bin/fiftyone", line 5, in <module>
    from fiftyone.core.cli import main
  File "/opt/anaconda3/envs/EF/lib/python3.6/site-packages/fiftyone/__init__.py", line 25, in <module>
    from fiftyone.__public__ import *
  File "/opt/anaconda3/envs/EF/lib/python3.6/site-packages/fiftyone/__public__.py", line 11, in <module>
    _database_service = fos.DatabaseService()
  File "/opt/anaconda3/envs/EF/lib/python3.6/site-packages/fiftyone/core/service.py", line 203, in __init__
    super().__init__()
  File "/opt/anaconda3/envs/EF/lib/python3.6/site-packages/fiftyone/core/service.py", line 81, in __init__
    self.start()
  File "/opt/anaconda3/envs/EF/lib/python3.6/site-packages/fiftyone/core/service.py", line 293, in start
    food.set_default_port(self.port)
  File "/opt/anaconda3/envs/EF/lib/python3.6/site-packages/fiftyone/core/service.py", line 283, in port
    return self._wait_for_child_port()
  File "/opt/anaconda3/envs/EF/lib/python3.6/site-packages/fiftyone/core/service.py", line 180, in _wait_for_child_port
    return find_port()
  File "/opt/anaconda3/envs/EF/lib/python3.6/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/opt/anaconda3/envs/EF/lib/python3.6/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/opt/anaconda3/envs/EF/lib/python3.6/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/opt/anaconda3/envs/EF/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/anaconda3/envs/EF/lib/python3.6/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/opt/anaconda3/envs/EF/lib/python3.6/site-packages/fiftyone/core/service.py", line 178, in find_port
    raise ServiceListenTimeout(etau.get_class_name(self), port)
fiftyone.core.service.ServiceListenTimeout: fiftyone.core.service.DatabaseService failed to bind to port

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and
files should be attached.

**Comment by benjaminpkane** [comment]
Hi @awandzel.

So our database, MongoDB, is failing to start up on your machine. One issue we've seen in the past is a missing entry in the `/etc/hosts` file. Be sure you have this line:
```
127.0.0.1       localhost 
```

If that isn't an issue, seeing the errors from the command itself would help diagnose things:
```
/opt/anaconda3/envs/EF/lib/python3.6/site-packages/fiftyone/db/bin/mongod --dbpath ~/.fiftyone/var/lib/mongo --logpath ~/.fiftyone/var/lib/mongo/log/mongo.log --port 0
```

**Comment by awandzel** [comment]
Does this help?


/opt/anaconda3/envs/EF/lib/python3.6/site-packages/fiftyone/db/bin/mongod --dbpath ~/.fiftyone/var/lib/mongo --logpath ~/.fiftyone/var/lib/mongo/log/mongo.log --port 0

{"t":{"$date":"2021-08-24T07:14:53.038Z"},"s":"I",  "c":"CONTROL",  "id":20697,   "ctx":"main","msg":"Renamed existing log file","attr":{"oldLogPath":"/Users/arthurwandzel/.fiftyone/var/lib/mongo/log/mongo.log","newLogPath":"/Users/arthurwandzel/.fiftyone/var/lib/mongo/log/mongo.log.2021-08-24T07-14-53"}}

**Comment by benjaminpkane** [comment]
Hi @awandzel. Sorry for the late reply.

I would recommend upgrading `fiftyone` and clearing out `~/.fiftyone/var/lib/mongo`

```
pip install -U fiftyone
rm -r ~/.fiftyone/var/lib/mongo
```

**Comment by swheaton** [comment]
no additional response, closing
