### ISSUE TITLE
[SETUP-BUG] MIssing libcrypto.so.1.1

### ISSUE THREAD

**Issue by andreydung** [voxel51/fiftyone#1251]
### Instructions

Thank you for submitting an issue. Please refer to our
[issue policy](https://www.github.com/voxel51/fiftyone/blob/develop/ISSUE_POLICY.md)
for information on what types of issues we address.

**Please fill in this template to ensure a timely and thorough response.**

Running fiftyone on remote server is having problems with lacking libcrypto.so.1.1.

### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
```Linux 75237172f222 4.15.0-122-generic #124-Ubuntu SMP Thu Oct 15 13:03:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
-   **FiftyOne installed from (pip or source)**: pip 
-   **FiftyOne version (run `fiftyone --version`)**:
-   **Python version**: 3.6

### Commands to reproduce

Created conda environment for fiftyone. Then install it using pip as usual.

```
# commands here
```

### Describe the problem

```
fiftyone/db/bin/mongod: error while loading shared libraries: libcrypto.so.1.1

Uncaught exception
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/miniconda3/envs/fiftyone/lib/python3.6/site-packages/fiftyone/__init__.py", line 25, in <module>
    from fiftyone.__public__ import *
  File "/home/ubuntu/miniconda3/envs/fiftyone/lib/python3.6/site-packages/fiftyone/__public__.py", line 14, in <module>
    foo.establish_db_conn(config)
  File "/home/ubuntu/miniconda3/envs/fiftyone/lib/python3.6/site-packages/fiftyone/core/odm/database.py", line 77, in establish_db_conn
    port = _db_service.port
  File "/home/ubuntu/miniconda3/envs/fiftyone/lib/python3.6/site-packages/fiftyone/core/service.py", line 295, in port
    return self._wait_for_child_port()
  File "/home/ubuntu/miniconda3/envs/fiftyone/lib/python3.6/site-packages/fiftyone/core/service.py", line 179, in _wait_for_child_port
    return find_port()
  File "/home/ubuntu/miniconda3/envs/fiftyone/lib/python3.6/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/ubuntu/miniconda3/envs/fiftyone/lib/python3.6/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/home/ubuntu/miniconda3/envs/fiftyone/lib/python3.6/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/home/ubuntu/miniconda3/envs/fiftyone/lib/python3.6/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/ubuntu/miniconda3/envs/fiftyone/lib/python3.6/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/home/ubuntu/miniconda3/envs/fiftyone/lib/python3.6/site-packages/fiftyone/core/service.py", line 177, in find_port
    raise ServiceListenTimeout(etau.get_class_name(self), port)
fiftyone.core.service.ServiceListenTimeout: fiftyone.core.service.DatabaseService failed to bind to port

```

### Other info / logs

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and
files should be attached.

**Comment by benjaminpkane** [comment]
Hi @andreydung :wave: 

 It looks like you might need to install `libcurl4` or similar.  If on Ubuntu 16.04, you'll need to install `fiftyone-db-ubuntu1604`.

```
pip install fiftyone-db-ubuntu1604
```

More details can be found [here](https://voxel51.com/docs/fiftyone/getting_started/troubleshooting.html#troubleshooting-linux-imports).

**Comment by brimoor** [comment]
I just got this error when trying to launch FiftyOne on an EC2 instance running Amazon Linux:

```shell
$ python3 -m venv myenv
$ source ~/myenv/bin/activate
$ pip install ipython fiftyone
$ grep ^NAME  /etc/*release
/etc/os-release:NAME="Amazon Linux"
```

```py
import fiftyone
```

```
Subprocess ['/home/ec2-user/fifty3/lib64/python3.7/site-packages/fiftyone/db/bin/mongod', '--dbpath', '/home/ec2-user/.fiftyone/var/lib/mongo', '--logpath', '/home/ec2-user/.fiftyone/var/lib/mongo/log/mongo.log', '--port', '0', '--nounixsocket'] exited with error 127:
/home/ec2-user/fifty3/lib64/python3.7/site-packages/fiftyone/db/bin/mongod: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by un-knight** [comment]
> 

I meet the same problem.

**Comment by benjaminpkane** [comment]
`libssl`  packages are needed. I will add a troubleshooting note in the docs

**Comment by Hypernovaaa** [comment]
> I just got this error when trying to launch FiftyOne on an EC2 instance running Amazon Linux:
> 
> ```shell
> $ python3 -m venv myenv
> $ source ~/myenv/bin/activate
> $ pip install ipython fiftyone
> $ grep ^NAME  /etc/*release
> /etc/os-release:NAME="Amazon Linux"
> ```
> 
> ```python
> import fiftyone
> ```
> 
> ```
> Subprocess ['/home/ec2-user/fifty3/lib64/python3.7/site-packages/fiftyone/db/bin/mongod', '--dbpath', '/home/ec2-user/.fiftyone/var/lib/mongo', '--logpath', '/home/ec2-user/.fiftyone/var/lib/mongo/log/mongo.log', '--port', '0', '--nounixsocket'] exited with error 127:
> /home/ec2-user/fifty3/lib64/python3.7/site-packages/fiftyone/db/bin/mongod: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
> ```

解决了么，老铁？（did you address it ）

**Comment by ctrlsam** [comment]
For those using `pacman`, installing `openssl 1.1` worked for me:

```
sudo pacman -U https://mirror.cmt.de/archlinux/core/os/x86_64/openssl-1.1-1.1.1.s-4-x86_64.pkg.tar.zst
```
