### ISSUE TITLE
[BUG] Failed to bind to port with PyTorch DistributedDataParallel

### ISSUE THREAD

**Issue by Etoye** [voxel51/fiftyone#1302]
### System information

-   **Ubuntu 18.04**:
-   **FiftyOne installed from pip**:
-   **FiftyOne version v0.13.2**:
-   **Python 3.6.9 (virtual env)**:

### Commands to reproduce

```python -u -m torch.distributed.launch --nproc_per_node=4 test.py```

### Describe the problem

FiftyOne can't bind ports after calling the script with PyTorch `DistributedDataParallel`. There are no problems with a single GPU, but with 2 and more GPUs script terminating instantly and very rare works without issues. Probably it's directly related to the multi-process parallelism of `DistributedDataParallel`.  

### Other info / logs

```
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Process 16911 (service/main.py --51-service db --multi) did not respond
{"t":{"$date":"2021-09-27T06:21:42.600Z"},"s":"I",  "c":"CONTROL",  "id":20697,   "ctx":"main","msg":"Renamed existing log file","attr":{"oldLogPath":"/home/ubuntu/.fiftyone/var/lib/mongo/log/mongo.log","newLogPath":"/home/ubuntu/.fiftyone/var/lib/mongo/log/mongo.log.2021-09-27T06-21-42"}}
Subprocess ['/home/ubuntu/OID/lib/python3.6/site-packages/fiftyone/db/bin/mongod', '--dbpath', '/home/ubuntu/.fiftyone/var/lib/mongo', '--logpath', '/home/ubuntu/.fiftyone/var/lib/mongo/log/mongo.log', '--port', '0', '--nounixsocket'] exited with error 100:
{"t":{"$date":"2021-09-27T06:21:42.609Z"},"s":"I",  "c":"CONTROL",  "id":20697,   "ctx":"main","msg":"Renamed existing log file","attr":{"oldLogPath":"/home/ubuntu/.fiftyone/var/lib/mongo/log/mongo.log","newLogPath":"/home/ubuntu/.fiftyone/var/lib/mongo/log/mongo.log.2021-09-27T06-21-42"}}
Subprocess ['/home/ubuntu/OID/lib/python3.6/site-packages/fiftyone/db/bin/mongod', '--dbpath', '/home/ubuntu/.fiftyone/var/lib/mongo', '--logpath', '/home/ubuntu/.fiftyone/var/lib/mongo/log/mongo.log', '--port', '0', '--nounixsocket'] exited with error 100:
{"t":{"$date":"2021-09-27T06:21:42.627Z"},"s":"I",  "c":"CONTROL",  "id":20697,   "ctx":"main","msg":"Renamed existing log file","attr":{"oldLogPath":"/home/ubuntu/.fiftyone/var/lib/mongo/log/mongo.log","newLogPath":"/home/ubuntu/.fiftyone/var/lib/mongo/log/mongo.log.2021-09-27T06-21-42"}}
Subprocess ['/home/ubuntu/OID/lib/python3.6/site-packages/fiftyone/db/bin/mongod', '--dbpath', '/home/ubuntu/.fiftyone/var/lib/mongo', '--logpath', '/home/ubuntu/.fiftyone/var/lib/mongo/log/mongo.log', '--port', '0', '--nounixsocket'] exited with error 100:
Uncaught exception
Traceback (most recent call last):
  File "train_test.py", line 7, in <module>
    from data_loader_fletch import create_data_loaders
  File "/home/ubuntu/LaboroTrainingOpenImages/data_loader_fletch.py", line 1, in <module>
    import fiftyone as fo
  File "/home/ubuntu/OID/lib/python3.6/site-packages/fiftyone/__init__.py", line 25, in <module>
    from fiftyone.__public__ import *
  File "/home/ubuntu/OID/lib/python3.6/site-packages/fiftyone/__public__.py", line 14, in <module>
    foo.establish_db_conn(config)
  File "/home/ubuntu/OID/lib/python3.6/site-packages/fiftyone/core/odm/database.py", line 77, in establish_db_conn
    port = _db_service.port
  File "/home/ubuntu/OID/lib/python3.6/site-packages/fiftyone/core/service.py", line 295, in port
    return self._wait_for_child_port()
  File "/home/ubuntu/OID/lib/python3.6/site-packages/fiftyone/core/service.py", line 179, in _wait_for_child_port
    return find_port()
  File "/home/ubuntu/OID/lib/python3.6/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/ubuntu/OID/lib/python3.6/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/home/ubuntu/OID/lib/python3.6/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/home/ubuntu/OID/lib/python3.6/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/ubuntu/OID/lib/python3.6/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/home/ubuntu/OID/lib/python3.6/site-packages/fiftyone/core/service.py", line 177, in find_port
    raise ServiceListenTimeout(etau.get_class_name(self), port)
fiftyone.core.service.ServiceListenTimeout: fiftyone.core.service.DatabaseService failed to bind to port
```

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

**Comment by benjaminpkane** [comment]
HI @Etoye. Thanks for the issue. We have some work to do to guarantee multiprocessing support it seems.

The information you provided is fairly specific, but if you provide exact reproduction steps and code, we'll be able to resolve this more quickly. Hopefully within the next couple releases.

Thorough reproduction steps allows others to chime in more easily, as well.

**Comment by Etoye** [comment]
Hello @benjaminpkane, thank you for the prompt reply. Unfortunately, I can't provide a full code related to the issue due to NDA, but I'll describe it in detail as much as possible.

1. Download test subset
```
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset(
    "open-images-v6", 
    "train", 
    label_types=["classifications"], 
    classes = ["Dog", "Cat"],
    max_samples=100,
    seed=51,
    shuffle=True,
    dataset_name="open-images-test",
)

dataset.persistent = True```

2.  data_loader.py, load fifty-one dataset and pass into PyTorch DataLoader for a custom dataset

```
def create_data_loaders(args):

    dataset = fo.load_dataset(args.dataset_name)
    train_dataset = OpenImagesDataset(dataset, transforms=tsfs)

    sampler_train = None
    if num_distrib() > 1:
        sampler_train = torch.utils.data.distributed.DistributedSampler(train_dataset)

    train_loader = torch.utils.data.DataLoader(
        dataset=train_dataset, batch_size=args.batch_size, 
        shuffle=sampler_train is None, collate_fn=collate_fn,
        pin_memory=True, sampler=sampler_train)

    return train_loader


class OpenImagesDataset(torch.utils.data.Dataset):
    def __init__(self):
        ....

    def __getitem__(self):
        ....
        return img, target
```
3. train.py where we call create_data_loaders function and setup DistributedDataParallel

```
def main():
    # arguments
    args = parser.parse_args()

    # setup distributed
    if num_distrib() > 1:
        torch.cuda.set_device(args.local_rank)
        torch.distributed.init_process_group(backend='nccl', init_method='env://')

    # Data loading
    train_loader = create_data_loaders(args)
```
I think the closest reproduction code could be found in [this ](https://github.com/Alibaba-MIIL/ImageNet21K) repository with the only one major difference in data loading, where fiftyone takes care of data, not the build-in PyTorch loaders.

**Comment by Etoye** [comment]
@benjaminpkane If we use pytorch.nn.DataParallel (single-process multi-thread parallelism) to use severe GPUs, on the first sight everything alright except UserWarning rising every epoch during model training. Not sure that it affects anything, but could you, please, have a look? Can we somehow hide this warning or fix it?
```
/home/ubuntu/OID/lib/python3.6/site-packages/pymongo/topology.py:165: UserWarning:

MongoClient opened before fork. Create MongoClient only after forking. See PyMongo's documentation for details: https://pymongo.readthedocs.io/en/stable/faq.html#is-pymongo-fork-safe
```
It repeats several times and depends on the amount of GPU's you use. In our case it's the same 4 UserWarning's.

**Comment by brimoor** [comment]
Hi @Etoye 👋 

Thanks for the all the detailed information. While we're looking into proper distributed training support, let me mention a simple workaround:

Since FiftyOne datasets are stored in a database, doing calls like `dataset[sample_id]` involve a round-trip database connection to retrieve the data. However, an alternative is just to load the filepaths and labels that you'll need into memory in the constructor of your Torch Dataset; then the data loader won't ever need to communicate with FiftyOne's database and distributed code will work fine (assuming all of the labels will fit into memory of course, which will certainly be true for classifications).

Continuing from your open images example code above, you can get the necessary data as follows:

```py
filepaths, labels = dataset.values(["filepath", "positive_labels.classifications.labael"])
```

**Comment by brimoor** [comment]
For example, FiftyOne is integrated with PyTorch Lightning Flash, and that's how things are implemented there:
https://github.com/PyTorchLightning/lightning-flash/blob/9e4fb62e0a7b2d3f265e574172bf88cc7b84924d/flash/core/data/data_source.py#L658-L689

**Comment by Etoye** [comment]
Hi @brimoor, 

Thank you for the hint! After the modification, there is no more UserWarning mentioned above and dataset loading as intended with pytorch.nn.DataParallel. At the same time using torch.nn.parallel.DistributedDataParallel brings the same error I've described in the bug report. Full message:
```
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Process 61778 (service/main.py --51-service db --multi) did not respond
{"t":{"$date":"2021-09-29T03:14:05.228Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"main","msg":"Error during global initialization","attr":{"error":{"code":37,"codeName":"FileRenameFailed","errmsg":"Could not rename preexisting log file \"/home/ubuntu/.fiftyone/var/lib/mongo/log/mongo.log\" to \"/home/ubuntu/.fiftyone/var/lib/mongo/log/mongo.log.2021-09-29T03-14-05\"; run with --logappend or manually remove file: No such file or directory"}}}
Subprocess ['/home/ubuntu/OID/lib/python3.6/site-packages/fiftyone/db/bin/mongod', '--dbpath', '/home/ubuntu/.fiftyone/var/lib/mongo', '--logpath', '/home/ubuntu/.fiftyone/var/lib/mongo/log/mongo.log', '--port', '0', '--nounixsocket'] exited with error 1:
{"t":{"$date":"2021-09-29T03:14:05.228Z"},"s":"I",  "c":"CONTROL",  "id":20697,   "ctx":"main","msg":"Renamed existing log file","attr":{"oldLogPath":"/home/ubuntu/.fiftyone/var/lib/mongo/log/mongo.log","newLogPath":"/home/ubuntu/.fiftyone/var/lib/mongo/log/mongo.log.2021-09-29T03-14-05"}}
Subprocess ['/home/ubuntu/OID/lib/python3.6/site-packages/fiftyone/db/bin/mongod', '--dbpath', '/home/ubuntu/.fiftyone/var/lib/mongo', '--logpath', '/home/ubuntu/.fiftyone/var/lib/mongo/log/mongo.log', '--port', '0', '--nounixsocket'] exited with error 100:
{"t":{"$date":"2021-09-29T03:14:05.256Z"},"s":"I",  "c":"CONTROL",  "id":20697,   "ctx":"main","msg":"Renamed existing log file","attr":{"oldLogPath":"/home/ubuntu/.fiftyone/var/lib/mongo/log/mongo.log","newLogPath":"/home/ubuntu/.fiftyone/var/lib/mongo/log/mongo.log.2021-09-29T03-14-05"}}
Subprocess ['/home/ubuntu/OID/lib/python3.6/site-packages/fiftyone/db/bin/mongod', '--dbpath', '/home/ubuntu/.fiftyone/var/lib/mongo', '--logpath', '/home/ubuntu/.fiftyone/var/lib/mongo/log/mongo.log', '--port', '0', '--nounixsocket'] exited with error 100:
Uncaught exception
Traceback (most recent call last):
  File "train.py", line 10, in <module>
    import fiftyone as fo
  File "/home/ubuntu/OID/lib/python3.6/site-packages/fiftyone/__init__.py", line 25, in <module>
    from fiftyone.__public__ import *
  File "/home/ubuntu/OID/lib/python3.6/site-packages/fiftyone/__public__.py", line 14, in <module>
    foo.establish_db_conn(config)
  File "/home/ubuntu/OID/lib/python3.6/site-packages/fiftyone/core/odm/database.py", line 77, in establish_db_conn
    port = _db_service.port
  File "/home/ubuntu/OID/lib/python3.6/site-packages/fiftyone/core/service.py", line 295, in port
    return self._wait_for_child_port()
  File "/home/ubuntu/OID/lib/python3.6/site-packages/fiftyone/core/service.py", line 179, in _wait_for_child_port
    return find_port()
  File "/home/ubuntu/OID/lib/python3.6/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/ubuntu/OID/lib/python3.6/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/home/ubuntu/OID/lib/python3.6/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/home/ubuntu/OID/lib/python3.6/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/ubuntu/OID/lib/python3.6/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/home/ubuntu/OID/lib/python3.6/site-packages/fiftyone/core/service.py", line 177, in find_port
    raise ServiceListenTimeout(etau.get_class_name(self), port)
fiftyone.core.service.ServiceListenTimeout: fiftyone.core.service.DatabaseService failed to bind to port
Uncaught exception
Traceback (most recent call last):
  File "train.py", line 10, in <module>
    import fiftyone as fo
  File "/home/ubuntu/OID/lib/python3.6/site-packages/fiftyone/__init__.py", line 25, in <module>
    from fiftyone.__public__ import *
  File "/home/ubuntu/OID/lib/python3.6/site-packages/fiftyone/__public__.py", line 14, in <module>
    foo.establish_db_conn(config)
  File "/home/ubuntu/OID/lib/python3.6/site-packages/fiftyone/core/odm/database.py", line 77, in establish_db_conn
    port = _db_service.port
  File "/home/ubuntu/OID/lib/python3.6/site-packages/fiftyone/core/service.py", line 295, in port
    return self._wait_for_child_port()
  File "/home/ubuntu/OID/lib/python3.6/site-packages/fiftyone/core/service.py", line 179, in _wait_for_child_port
    return find_port()
  File "/home/ubuntu/OID/lib/python3.6/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/ubuntu/OID/lib/python3.6/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/home/ubuntu/OID/lib/python3.6/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/home/ubuntu/OID/lib/python3.6/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/ubuntu/OID/lib/python3.6/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/home/ubuntu/OID/lib/python3.6/site-packages/fiftyone/core/service.py", line 177, in find_port
    raise ServiceListenTimeout(etau.get_class_name(self), port)
fiftyone.core.service.ServiceListenTimeout: fiftyone.core.service.DatabaseService failed to bind to port
Uncaught exception
Traceback (most recent call last):
  File "train.py", line 10, in <module>
    import fiftyone as fo
  File "/home/ubuntu/OID/lib/python3.6/site-packages/fiftyone/__init__.py", line 25, in <module>
    from fiftyone.__public__ import *
  File "/home/ubuntu/OID/lib/python3.6/site-packages/fiftyone/__public__.py", line 14, in <module>
    foo.establish_db_conn(config)
  File "/home/ubuntu/OID/lib/python3.6/site-packages/fiftyone/core/odm/database.py", line 77, in establish_db_conn
    port = _db_service.port
  File "/home/ubuntu/OID/lib/python3.6/site-packages/fiftyone/core/service.py", line 295, in port
    return self._wait_for_child_port()
  File "/home/ubuntu/OID/lib/python3.6/site-packages/fiftyone/core/service.py", line 179, in _wait_for_child_port
    return find_port()
  File "/home/ubuntu/OID/lib/python3.6/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/ubuntu/OID/lib/python3.6/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/home/ubuntu/OID/lib/python3.6/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/home/ubuntu/OID/lib/python3.6/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/ubuntu/OID/lib/python3.6/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/home/ubuntu/OID/lib/python3.6/site-packages/fiftyone/core/service.py", line 177, in find_port
    raise ServiceListenTimeout(etau.get_class_name(self), port)
fiftyone.core.service.ServiceListenTimeout: fiftyone.core.service.DatabaseService failed to bind to port
Killing subprocess 61762
Killing subprocess 61763
Killing subprocess 61764
Killing subprocess 61765
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/OID/lib/python3.6/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/ubuntu/OID/lib/python3.6/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/ubuntu/OID/lib/python3.6/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ubuntu/OID/bin/python', '-u', 'train.py', '--local_rank=3', '--dataset_name', 'open-images-test', '--epochs', '3']' returned non-zero exit status 1.
```

**Comment by brimoor** [comment]
Right, this is because (as the stack trace shows) `import fiftyone` itself tries to establish a database connection.

So until we're able to properly support distributed training workflows like this, you'll need to refactor your code to avoid importing FiftyOne at all in any script that is being run via `DistributedDataParallel`. For example, you could write the requisite filepaths and labels to disk in, say, JSON format and load from there in your training script.

**Comment by Etoye** [comment]
Sounds like a plan, thank you for the prompt support. Should we close this issue open until you add support for distributed training workflow or close it?

**Comment by brimoor** [comment]
Let's leave it open to remind us to fix it properly :)

**Comment by EilsonH** [comment]
Hi is there any progress on this issue? I am trying to load a dataset hosted on MongoDB with multiple workers and have been getting this warning. Would appreciate any update!

**Comment by brimoor** [comment]
No update yet. `import fiftyone` currently always opens a database connection in the main process, and those connections can't be serialized. It seems we'd have to find a way to omit the connection from the serialization.

**Comment by tom-robo** [comment]
Thanks for the very useful information in this thread. Having been on this journey myself, could this detail be made more prominent in the documentation or at least highlighted in the pytorch example here: https://github.com/voxel51/fiftyone-examples/blob/master/examples/pytorch_detection_training.ipynb where the UserWarnings are present in the quoted program outputs but not referred to at all.

**Comment by daniel-bogdoll** [comment]
@brimoor Might it be an idea to provide a native (= designed by V51) function to get a fully functional torch.utils.data.Dataset from a fiftyone dataset?

I feel like it's rather important to - after loading a dataset with V51 - get a proper torch datasets loader that also supports multi-process dataloading etc. It's been quite a hassle to figure things out based on

- this tutorial https://github.com/voxel51/fiftyone-examples/blob/master/examples/pytorch_detection_training.ipynb
- this issues to avoid 'fork' problems

The whole "must be pickable" thing is really nothing I wanted to worry about :D

My latest version looks like this:

```
class FiftyOneTorchDatasetCOCO(torch.utils.data.Dataset):
    """
    A custom PyTorch Dataset for loading COCO-style datasets from FiftyOne.
    This dataset class is designed to work with FiftyOne datasets and provides
    functionality to load images and their corresponding annotations in a format
    compatible with PyTorch. It avoids any reference to the original FiftyOne dataset to remain pickable.

    Attributes:
        transforms (callable, optional): A function/transform that takes in an
            image and returns a transformed version. Default is None.
        gt_field (str): The name of the ground truth field in the FiftyOne dataset.
            Default is "ground_truth".
        img_paths (list): List of image file paths.
        labels (list): List of labels corresponding to the images.
        metadata (dict): Dictionary containing metadata for each image.
        classes (list): List of distinct class labels.
        labels_map_rev (dict): Dictionary mapping class labels to indices.

    Args:
        fiftyone_dataset (fiftyone.core.dataset.Dataset): The FiftyOne dataset to load.
        transforms (callable, optional): A function/transform that takes in an
            image and returns a transformed version. Default is None.
        gt_field (str, optional): The name of the ground truth field in the
            FiftyOne dataset. Default is "ground_truth".
        classes (list, optional): List of class labels. If not provided, the
            distinct labels from the dataset will be used.

    Methods:
        __getitem__(idx):
            Returns the image and target at the specified index.
        __getitems__(indices):
            Returns a list of samples for the specified indices.
        __len__():
            Returns the number of samples in the dataset.
        get_classes():
            Returns the list of class labels.
        get_splits():
            Returns the set of splits (tags) in the dataset.

    References:
        - https://github.com/voxel51/fiftyone-examples/blob/master/examples/pytorch_detection_training.ipynb
        - https://github.com/voxel51/fiftyone/issues/1302
    """

    def __init__(
        self,
        fiftyone_dataset,
        transforms=None,
        gt_field="ground_truth",
        classes=None,
    ):
        self.transforms = transforms
        self.gt_field = gt_field
        self.img_paths, self.labels = fiftyone_dataset.values(
            ["filepath", f"{gt_field}.detections"]
        )
        self.metadata = {
            sample.filepath: sample.metadata for sample in fiftyone_dataset
        }
        self.classes = classes
        if not self.classes:
            # Get list of distinct labels that exist in the view
            self.classes = fiftyone_dataset.distinct(f"{gt_field}.detections.label")
        self.labels_map_rev = {c: i for i, c in enumerate(self.classes)}

    def __getitem__(self, idx):
        img_path = self.img_paths[idx]
        metadata = self.metadata.get(img_path, None)
        detections = self.labels[idx]
        img = Image.open(img_path).convert("RGB")
        boxes = []
        labels = []
        area = []
        iscrowd = []
        for det in detections:
            category_id = self.labels_map_rev[det.label]
            coco_obj = fouc.COCOObject.from_label(
                det,
                metadata,
                category_id=category_id,
            )
            x, y, w, h = coco_obj.bbox
            boxes.append([x, y, w, h])
            labels.append(coco_obj.category_id)
            area.append(coco_obj.area)
            iscrowd.append(coco_obj.iscrowd)

        target = {}
        target["boxes"] = torch.as_tensor(boxes, dtype=torch.float32)
        target["labels"] = torch.as_tensor(labels, dtype=torch.int64)
        target["image_id"] = torch.as_tensor([idx])
        target["area"] = torch.as_tensor(area, dtype=torch.float32)
        target["iscrowd"] = torch.as_tensor(iscrowd, dtype=torch.int64)
        if self.transforms is not None:
            img = self.transforms(img)
        return img, target

    def __getitems__(self, indices):
        samples = [self.__getitem__(idx) for idx in indices]
        return samples

    def __len__(self):
        return len(self.img_paths)

    def get_classes(self):
        return self.classes

    def get_splits(self):
        splits = set()
        for sample in self.labels:
            split = sample.tags[0]  # Assuming the split is the first tag
            splits.add(split)
        return splits
```

**Comment by jacobsela** [comment]
Putting this here now for those that need it. An easy way of getting around this issue is by sequentially opening database connections after launching the processes. Here is a pseudocode snippet:

```
for i in range(num_processes):
    if rank == i:
        # load the dataset
        dataset = fo.load_dataset(dataset_name)
    torch.distributed.barrier(local_process_group)
```

In a standard single node, multi proc distributed data parallel run instantiated with `torchrun`, the environment variables `WORLD_SIZE` and `RANK` will have the values corresponding to `num_processes` and `rank`.

All of this will come in a neat and handy package (allowing you to turn any FiftyOne Dataset into a torch dataset with just 1 function) with https://github.com/voxel51/fiftyone/pull/5321. Stay tuned :)

**Comment by jacobsela** [comment]
@kaixi-wang @brimoor 

I just talked with my friend from Mongo. He says the solution proposed [here](https://github.com/voxel51/fiftyone/issues/1302#issuecomment-2715784087), which is also the solution I'm using in https://github.com/voxel51/fiftyone/pull/5321 in the `distributed_init` function is bad because in OSS `fo.load_dataset` creates a new mongo server. This works for the purpose of training, but creates unnecessary servers and could be hazardous when writing back to the DB.

For Teams/Enterprise this is most likely not an issue because I'm assuming that `load_dataset` creates a client rather than a server. Is this true?

For OSS, the solution would be to create the server once on rank 0 and have all of the other processes connect to it as clients. What is the correct way of doing this in OSS?

**Comment by brimoor** [comment]
> For OSS, the solution would be to create the server once on rank 0 and have all of the other processes connect to it as clients. What is the correct way of doing this in OSS?

This *is* how OSS works. Only one mongo server subprocess is created per machine. Subsequent processes that establish mongo connections will realize that the first process already started the server and they'll just connect to it

**Comment by jacobsela** [comment]
Oh perfect then we don't have to worry at all, this solution should be fine!

**Comment by jacobsela** [comment]
@brimoor Thanks for the help, confirmed this work with this snippet:

```python

if __name__ == '__main__':
    """
    run with:
    torchrun --nnodes=1 --nproc-per-node=2 /path/to/snippet
    """
    import os
    import torch
    import fiftyone as fo

    torch.distributed.init_process_group()

    for i in range(torch.distributed.get_world_size()):
        if torch.distributed.get_rank() == i:
            print(f"Loading dataset rank {torch.distributed.get_rank()}")
            dataset = fo.load_dataset("quickstart")
        torch.distributed.barrier()

    for i in range(torch.distributed.get_world_size()):
        if torch.distributed.get_rank() == i:
            print(
                torch.distributed.get_rank(),
                fo.core.odm.database._client.address,
            )
        torch.distributed.barrier()

    torch.distributed.destroy_process_group()
```

Output:
```
Loading dataset rank 0
Loading dataset rank 1
0 ('localhost', 61786)
1 ('localhost', 61786)
```

Can I mark as resolved and continue using this solution in https://github.com/voxel51/fiftyone/pull/5321?

**Comment by brimoor** [comment]
@jacobsela perfect, just add `Resolves #1302` to the PR description of #5321 and it will automatically close this issue when the PR is merged ✅

**Comment by kaixi-wang** [comment]
@jacobsela 
does this only work if you run it as a script with 'if __name__ == "__main__":' ? Not sure if this means that this couldn't be used in an operator/plugin

**Comment by jacobsela** [comment]
@kaixi-wang No, this should work regardless. I just put it under the main so that I can use `torchrun` to easily launch the processes, but this would work if the processes were launched with standard multiprocessing python code, or torch distributed.

**Comment by jacobsela** [comment]
resolved in #5321
