### ISSUE TITLE
[BUG] fiftyone.core.service.DatabaseService failed to bind to port in WSL2

### ISSUE THREAD

**Issue by ZardZen** [voxel51/fiftyone#1303]
When i use fiftyone in WSL2, i got this error after import fiftyone as fo, the trackback as follows:

{"t":{"$date":"2021-09-28T03:24:19.258Z"},"s":"I",  "c":"CONTROL",  "id":20697,   "ctx":"main","msg":"Renamed existing log file","attr":{"oldLogPath":"/home/yuanzhen/.fiftyone/var/lib/mongo/log/mongo.log","newLogPath":"/home/yuanzhen/.fiftyone/var/lib/mongo/log/mongo.log.2021-09-28T03-24-19"}}
Subprocess ['/home/yuanzhen/anaconda3/envs/py36/lib/python3.6/site-packages/fiftyone/db/bin/mongod', '--dbpath', '/home/yuanzhen/.fiftyone/var/lib/mongo', '--logpath', '/home/yuanzhen/.fiftyone/var/lib/mongo/log/mongo.log', '--port', '0', '--nounixsocket'] exited with error -6:
Uncaught exception
Traceback (most recent call last):
  File "data.py", line 1, in <module>
    import fiftyone as fo
  File "/home/yuanzhen/anaconda3/envs/py36/lib/python3.6/site-packages/fiftyone/__init__.py", line 25, in <module>
    from fiftyone.__public__ import *
  File "/home/yuanzhen/anaconda3/envs/py36/lib/python3.6/site-packages/fiftyone/__public__.py", line 14, in <module>
    foo.establish_db_conn(config)
  File "/home/yuanzhen/anaconda3/envs/py36/lib/python3.6/site-packages/fiftyone/core/odm/database.py", line 77, in establish_db_conn
    port = _db_service.port
  File "/home/yuanzhen/anaconda3/envs/py36/lib/python3.6/site-packages/fiftyone/core/service.py", line 295, in port
    return self._wait_for_child_port()
  File "/home/yuanzhen/anaconda3/envs/py36/lib/python3.6/site-packages/fiftyone/core/service.py", line 179, in _wait_for_child_port
    return find_port()
  File "/home/yuanzhen/anaconda3/envs/py36/lib/python3.6/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/yuanzhen/anaconda3/envs/py36/lib/python3.6/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/home/yuanzhen/anaconda3/envs/py36/lib/python3.6/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/home/yuanzhen/anaconda3/envs/py36/lib/python3.6/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/yuanzhen/anaconda3/envs/py36/lib/python3.6/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/home/yuanzhen/anaconda3/envs/py36/lib/python3.6/site-packages/fiftyone/core/service.py", line 177, in find_port
    raise ServiceListenTimeout(etau.get_class_name(self), port)
fiftyone.core.service.ServiceListenTimeout: fiftyone.core.service.DatabaseService failed to bind to port

Thanks for your help!!!!

**Comment by benjaminpkane** [comment]
Pardon the delay, @ZardZen. I'll have something to say on Monday.

**Comment by yuxiaoyuan0406** [comment]
Similar problem here. But my code runs on ubuntu 20.04.  
`import fiftyone as fo` gives this

```
{"t":{"$date":"2021-10-04T00:25:56.959Z"},"s":"I",  "c":"CONTROL",  "id":20697,   "ctx":"main","msg":"Renamed existing log file","attr":{"oldLogPath":"/home/songwei/.fiftyone/var/lib/mongo/log/mongo.log","newLogPath":"/home/songwei/.fiftyone/var/lib/mongo/log/mongo.log.2021-10-04T00-25-56"}}
Subprocess ['/home/songwei/anaconda3/envs/yolof/lib/python3.7/site-packages/fiftyone/db/bin/mongod', '--dbpath', '/home/songwei/.fiftyone/var/lib/mongo', '--logpath', '/home/songwei/.fiftyone/var/lib/mongo/log/mongo.log', '--port', '0', '--nounixsocket'] exited with error 100:
Uncaught exception
Traceback (most recent call last):
  File "/home/songwei/anaconda3/envs/yolof/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/songwei/anaconda3/envs/yolof/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/songwei/.vscode-server/extensions/ms-python.python-2021.9.1246542782/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/songwei/.vscode-server/extensions/ms-python.python-2021.9.1246542782/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/songwei/.vscode-server/extensions/ms-python.python-2021.9.1246542782/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/home/songwei/anaconda3/envs/yolof/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/songwei/anaconda3/envs/yolof/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/songwei/anaconda3/envs/yolof/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/songwei/dennis/Yolo-FastestV2/fiftyone_dataset.py", line 1, in <module>
    import fiftyone as fo
  File "/home/songwei/anaconda3/envs/yolof/lib/python3.7/site-packages/fiftyone/__init__.py", line 25, in <module>
    from fiftyone.__public__ import *
  File "/home/songwei/anaconda3/envs/yolof/lib/python3.7/site-packages/fiftyone/__public__.py", line 14, in <module>
    foo.establish_db_conn(config)
  File "/home/songwei/anaconda3/envs/yolof/lib/python3.7/site-packages/fiftyone/core/odm/database.py", line 77, in establish_db_conn
    port = _db_service.port
  File "/home/songwei/anaconda3/envs/yolof/lib/python3.7/site-packages/fiftyone/core/service.py", line 295, in port
    return self._wait_for_child_port()
  File "/home/songwei/anaconda3/envs/yolof/lib/python3.7/site-packages/fiftyone/core/service.py", line 179, in _wait_for_child_port
    return find_port()
  File "/home/songwei/anaconda3/envs/yolof/lib/python3.7/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/songwei/anaconda3/envs/yolof/lib/python3.7/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/home/songwei/anaconda3/envs/yolof/lib/python3.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/home/songwei/anaconda3/envs/yolof/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/songwei/anaconda3/envs/yolof/lib/python3.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/home/songwei/anaconda3/envs/yolof/lib/python3.7/site-packages/fiftyone/core/service.py", line 177, in find_port
    raise ServiceListenTimeout(etau.get_class_name(self), port)
fiftyone.core.service.ServiceListenTimeout: fiftyone.core.service.DatabaseService failed to bind to port
```

**Comment by benjaminpkane** [comment]
@yuxiaoyuan0406 yours is a different error code (100). It is related to an improper shutdown of `mongod` (fiftyone). We hope to make this more robust.

If you check the log files in `/home/songwei/.fiftyone/var/lib/mongo/log/` there will be more information. Feel free to share anything you find so we can improve things.

**Comment by benjaminpkane** [comment]
@ZardZen I cannot reproduce in my own wsl2 setup, but your error code is `-6`. I cannot find any documentation on that, but `6` is network related.

If you share the relevant startup logs in `home/yuanzhen/.fiftyone/var/lib/mongo/log/` we can try to work through it.

**Comment by yuxiaoyuan0406** [comment]
@benjaminpkane thank you for your advice. I run the program again to generate a new log file. There is this line that gives an error report. 

```
{"t":{"$date":"2021-10-04T08:25:56.966+08:00"},"s":"E",  "c":"STORAGE",  "id":20557,   "ctx":"initandlisten","msg":"DBException in initAndListen, terminating","attr":{"error":"DBPathInUse: Unable to lock the lock file: /home/songwei/.fiftyone/var/lib/mongo/mongod.lock (Resource temporarily unavailable). Another mongod instance is already running on the /home/songwei/.fiftyone/var/lib/mongo directory"}}
```

So I remove `mongod.lock` and try again and got an error code of  `14`. 

```
{"t":{"$date":"2021-10-05T06:46:23.527Z"},"s":"I",  "c":"CONTROL",  "id":20697,   "ctx":"main","msg":"Renamed existing log file","attr":{"oldLogPath":"/home/songwei/.fiftyone/var/lib/mongo/log/mongo.log","newLogPath":"/home/songwei/.fiftyone/var/lib/mongo/log/mongo.log.2021-10-05T06-46-23"}}
Subprocess ['/home/songwei/anaconda3/envs/yolof/lib/python3.7/site-packages/fiftyone/db/bin/mongod', '--dbpath', '/home/songwei/.fiftyone/var/lib/mongo', '--logpath', '/home/songwei/.fiftyone/var/lib/mongo/log/mongo.log', '--port', '0', '--nounixsocket'] exited with error 14:
Uncaught exception
Traceback (most recent call last):
  File "/home/songwei/anaconda3/envs/yolof/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/songwei/anaconda3/envs/yolof/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/songwei/.vscode-server/extensions/ms-python.python-2021.9.1246542782/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/songwei/.vscode-server/extensions/ms-python.python-2021.9.1246542782/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/songwei/.vscode-server/extensions/ms-python.python-2021.9.1246542782/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/home/songwei/anaconda3/envs/yolof/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/songwei/anaconda3/envs/yolof/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/songwei/anaconda3/envs/yolof/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/songwei/dennis/Yolo-FastestV2/fiftyone_dataset.py", line 1, in <module>
    import fiftyone as fo
  File "/home/songwei/anaconda3/envs/yolof/lib/python3.7/site-packages/fiftyone/__init__.py", line 25, in <module>
    from fiftyone.__public__ import *
  File "/home/songwei/anaconda3/envs/yolof/lib/python3.7/site-packages/fiftyone/__public__.py", line 14, in <module>
    foo.establish_db_conn(config)
  File "/home/songwei/anaconda3/envs/yolof/lib/python3.7/site-packages/fiftyone/core/odm/database.py", line 77, in establish_db_conn
    port = _db_service.port
  File "/home/songwei/anaconda3/envs/yolof/lib/python3.7/site-packages/fiftyone/core/service.py", line 295, in port
    return self._wait_for_child_port()
  File "/home/songwei/anaconda3/envs/yolof/lib/python3.7/site-packages/fiftyone/core/service.py", line 179, in _wait_for_child_port
    return find_port()
  File "/home/songwei/anaconda3/envs/yolof/lib/python3.7/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/songwei/anaconda3/envs/yolof/lib/python3.7/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/home/songwei/anaconda3/envs/yolof/lib/python3.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/home/songwei/anaconda3/envs/yolof/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/songwei/anaconda3/envs/yolof/lib/python3.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/home/songwei/anaconda3/envs/yolof/lib/python3.7/site-packages/fiftyone/core/service.py", line 177, in find_port
    raise ServiceListenTimeout(etau.get_class_name(self), port)
fiftyone.core.service.ServiceListenTimeout: fiftyone.core.service.DatabaseService failed to bind to port
```

Hope this is helpful! 

And another question: should I open a new issue for this?

**Comment by ZardZen** [comment]
@benjaminpkane Sorry，I mistake the version of my wsl. It is wsl1 not wsl2, and fiftyone works without this error in wsl2
