### ISSUE TITLE
pymongo.errors.OperationFailure error when using dataset.annotate() on a video dataset

### ISSUE THREAD

**Issue by bachdv99** [voxel51/fiftyone#1422]
### System information

-   OS Platform and Distribution: 20.04 LTS
-   FiftyOne version: 0.14.0 installed from pip
-   Python version: 3.8.10

i run example Annotating videos in CVAT but get this error

```
Failed to populate metadata on 1 samples. Use `dataset.exists("metadata", False)` to retrieve them
Uncaught exception
Traceback (most recent call last):
  File "video.py", line 12, in <module>
    view.annotate(
  File "/home/bach/.local/lib/python3.8/site-packages/fiftyone/core/collections.py", line 6004, in annotate
    return foua.annotate(
  File "/home/bach/.local/lib/python3.8/site-packages/fiftyone/utils/annotations.py", line 204, in annotate
    results = anno_backend.upload_annotations(
  File "/home/bach/.local/lib/python3.8/site-packages/fiftyone/utils/cvat.py", line 2573, in upload_annotations
    results = api.upload_samples(samples, self)
  File "/home/bach/.local/lib/python3.8/site-packages/fiftyone/utils/cvat.py", line 3275, in upload_samples
    samples.ensure_frames()
  File "/home/bach/.local/lib/python3.8/site-packages/fiftyone/core/view.py", line 602, in ensure_frames
    self._dataset._ensure_frames(view=self)
  File "/home/bach/.local/lib/python3.8/site-packages/fiftyone/core/dataset.py", line 2193, in _ensure_frames
    self._aggregate(pipeline=pipeline)
  File "/home/bach/.local/lib/python3.8/site-packages/fiftyone/core/dataset.py", line 4159, in _aggregate
    return foo.aggregate(self._sample_collection, _pipeline)
  File "/home/bach/.local/lib/python3.8/site-packages/fiftyone/core/odm/database.py", line 170, in aggregate
    result = collection.aggregate(pipelines[0], allowDiskUse=True)
  File "/home/bach/.local/lib/python3.8/site-packages/pymongo/collection.py", line 2502, in aggregate
    return self._aggregate(_CollectionAggregationCommand,
  File "/home/bach/.local/lib/python3.8/site-packages/pymongo/collection.py", line 2419, in _aggregate
    return self.__database.client._retryable_read(
  File "/home/bach/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "/home/bach/.local/lib/python3.8/site-packages/pymongo/aggregation.py", line 137, in get_cursor
    result = sock_info.command(
  File "/home/bach/.local/lib/python3.8/site-packages/pymongo/pool.py", line 710, in command
    return command(self, dbname, spec, secondary_ok,
  File "/home/bach/.local/lib/python3.8/site-packages/pymongo/network.py", line 161, in command
    helpers._check_command_response(
  File "/home/bach/.local/lib/python3.8/site-packages/pymongo/helpers.py", line 167, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: $range requires a numeric ending value, found value of type: null, full error: {'ok': 0.0, 'errmsg': '$range requires a numeric ending value, found value of type: null', 'code': 34445, 'codeName': 'Location34445'}
```

i have added `dataset.exists("metadata", False)` but still get the same error

**Comment by brimoor** [comment]
Hi @bachdv99 I'm guessing the issue is that you need to [install ffmpeg](https://voxel51.com/docs/fiftyone/getting_started/troubleshooting.html#videos-do-not-load-in-the-app) in order to work with video datasets.

```
sudo apt install -y ffmpeg
```

 Uploading to CVAT requires computing some metadata like resolution and frame rate about the videos, which is done using ffmpeg.

**Comment by bachdv99** [comment]
thanks brimoor, i have installed ffmpeg and now i can annotate video
