### ISSUE TITLE
[BUG] Filtering by a datetime field makes the server raise an exception

### ISSUE THREAD

**Issue by FGeri** [voxel51/fiftyone#1502]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04.2 LTS
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: v0.14.2
-   **Python version**: 3.8

### Commands to reproduce

-

### Describe the problem

When trying to filter by the sliders on a datetime field in the app, the server raises an uncaught exception, hence the filtering is not done.

### Code to reproduce issue

-

### Other info / logs

```
An exception has been raised by the server. Your session has been reverted to its previous state.

Traceback (most recent call last):
  File "main.py", line 313, in wrapper
    result = await func(self, *args, **kwargs)
  File "main.py", line 556, in on_message
    await event(self, **message)
  File "main.py", line 624, in on_filters_update
    await self.send_statistics(view, filters=filters, extended=True)
  File "main.py", line 1031, in send_statistics
    results = await view._async_aggregate(aggregations)
  File "/home/fhe2bp/venvs/datalake/lib/python3.8/site-packages/fiftyone/core/collections.py", line 6784, in _async_aggregate
    _results = await foo.aggregate(collection, pipelines)
  File "/home/fhe2bp/venvs/datalake/lib/python3.8/site-packages/fiftyone/core/odm/database.py", line 191, in _do_async_pooled_aggregate
    return await asyncio.gather(
  File "/home/fhe2bp/venvs/datalake/lib/python3.8/site-packages/fiftyone/core/odm/database.py", line 201, in _do_async_aggregate
    return await cursor.to_list(1)
  File "/home/fhe2bp/venvs/datalake/lib/python3.8/site-packages/motor/core.py", line 1417, in _to_list
    result = get_more_result.result()
  File "/home/fhe2bp/venvs/datalake/lib/python3.8/site-packages/motor/core.py", line 1626, in _on_started
    pymongo_cursor = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/fhe2bp/venvs/datalake/lib/python3.8/site-packages/pymongo/collection.py", line 2502, in aggregate
    return self._aggregate(_CollectionAggregationCommand,
  File "/home/fhe2bp/venvs/datalake/lib/python3.8/site-packages/pymongo/collection.py", line 2419, in _aggregate
    return self.__database.client._retryable_read(
  File "/home/fhe2bp/venvs/datalake/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "/home/fhe2bp/venvs/datalake/lib/python3.8/site-packages/pymongo/aggregation.py", line 137, in get_cursor
    result = sock_info.command(
  File "/home/fhe2bp/venvs/datalake/lib/python3.8/site-packages/pymongo/pool.py", line 710, in command
    return command(self, dbname, spec, secondary_ok,
  File "/home/fhe2bp/venvs/datalake/lib/python3.8/site-packages/pymongo/network.py", line 161, in command
    helpers._check_command_response(
  File "/home/fhe2bp/venvs/datalake/lib/python3.8/site-packages/pymongo/helpers.py", line 167, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: Failed to optimize pipeline :: caused by :: Failed to optimize expression :: caused by :: Unsupported conversion from int to date in $convert with no onError value, full error: {'ok': 0.0, 'errmsg': 'Failed to optimize pipeline :: caused by :: Failed to optimize expression :: caused by :: Unsupported conversion from int to date in $convert with no onError value', 'code': 241, 'codeName': 'ConversionFailure'}
```

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [ ] `Core`: Core `fiftyone` Python library issue
-   [x] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

**Comment by brimoor** [comment]
Can you share a reproducible example? [These date-based queries work](https://voxel51.com/docs/fiftyone/user_guide/using_views.html#date-based-views), for example.

**Comment by FGeri** [comment]
Hi @brimoor
Looks like the issue only arises when the querry contains only items with the dates 1970.01.
A minimal reproducible example could be:
```
from datetime import datetime, timedelta

import fiftyone as fo
from fiftyone import ViewField as F

dataset = fo.Dataset()
dataset.add_samples(
    [
        fo.Sample(
            filepath="image1.png",
            capture_date=datetime(1970, 1, 1, 1, 0, 0),
        ),
        fo.Sample(
            filepath="image2.png",
            capture_date=datetime(1970, 1, 1, 2, 0, 0),
        ),
        fo.Sample(
            filepath="image3.png",
            capture_date=datetime(1970, 1, 1, 3, 0, 0),
        ),
    ]
)
query_date = datetime(1970, 1, 1, 2, 0, 0)
query_delta = timedelta(minutes=30)

# Samples with capture date after 2021-08-24 02:01:00
view = dataset.match(F("capture_date") > query_date)
print(view)

# Samples with capture date within 30 minutes of 2021-08-24 02:01:00
view = dataset.match(abs(F("capture_date") - query_date) < query_delta)
print(view)
```

**Comment by brimoor** [comment]
Thanks for the reproducible example! https://github.com/voxel51/fiftyone/pull/1508 patches this issue
