### ISSUE TITLE
[BUG] dataset.apply_model AttributeError: Can't pickle local object '_make_data_loader.<locals>.collate_fn'

### ISSUE THREAD

**Issue by gb96** [voxel51/fiftyone#1531]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: 0.14.2
-   **Python version**: 3.9.9

### Describe the problem

Following fiftyone.examples, Uncaught exception when attempting to dataset.apply_model()

### Code to reproduce issue

```py
# from fiftyone.examples
import torch
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("coco-2017", split="validation")
session = fo.launch_app(dataset)
model = foz.load_zoo_model("faster-rcnn-resnet50-fpn-coco-torch")
dataset.apply_model(model, label_field="predictions", confidence_thresh=0.6)
```

### Other info / logs

```py
dataset.apply_model(model, label_field="predictions", confidence_thresh=0.6)
```

```
Uncaught exception
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python\Python39\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Python\Python39\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
   0% ||---------------------------------------------------------------------------------------------------------------------|    0/5000 [4.9s elapsed, ? remaining, ? samples/s]
Uncaught exception
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\FiftyOne\venv\lib\site-packages\fiftyone\core\collections.py", line 1531, in apply_model
    fomo.apply_model(
  File "D:\FiftyOne\venv\lib\site-packages\fiftyone\core\models.py", line 188, in apply_model
    return _apply_image_model_data_loader(
  File "D:\FiftyOne\venv\lib\site-packages\fiftyone\core\models.py", line 294, in _apply_image_model_data_loader
    for sample_batch, imgs in zip(samples_loader, data_loader):
  File "D:\FiftyOne\venv\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "D:\FiftyOne\venv\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "D:\FiftyOne\venv\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
    w.start()
  File "C:\Python\Python39\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Python\Python39\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Python\Python39\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Python\Python39\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Python\Python39\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object '_make_data_loader.<locals>.collate_fn'
```

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x ] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ x] No. I cannot contribute a bug fix at this time.

**Comment by brimoor** [comment]
Multiprocessing on Windows is always sketchy... Can you try passing `num_workers=0`?

```py
dataset.apply_model(
    model,
    label_field="predictions",
    confidence_thresh=0.6,
    num_workers=0,
)
```

This should prevent subprocesses from being used by the Torch data loader

**Comment by gb96** [comment]
Done, worked like a charm.  I wonder if perhaps apply_model should default num_workers=0, or perhaps only default that under Windows?

**Comment by brimoor** [comment]
Yeah good point. I think it is possible to get multiprocessing code to work on Windows, eg [using these ideas](https://stackoverflow.com/questions/20222534/python-multiprocessing-on-windows-if-name-main) when structuring the code you run, but, it's probably best to default to `num_workers=0` so that the code actually runs (albeit slower) out of the box and let users invest the effort to get multiprocessing working if performance becomes a concern.
