### ISSUE TITLE
[SETUP-BUG] Pre-commit fails (Apple Silicon Mac)

### ISSUE THREAD

**Issue by stbdang** [voxel51/fiftyone#1585]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Darwin Kernel Version 21.3.0: Wed Jan 5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000
-   **FiftyOne installed from (pip or source)**: source
-   **FiftyOne version (run `fiftyone --version`)**: 0.14.3 (develop 7c389522ab2122887e69d994214ecc4440bc371f)
-   **Python version**: Python 3.9.10

### Commands to reproduce

After failing to build developer (refer to https://github.com/voxel51/fiftyone/issues/1584), I tried to run install.bash manually

```
pre-commit install
pip install -e .
```

Make some code change and try to commit
```
git add <files>
git commit

git commit                                                                                                                                          daniel@Daniels-MacBook-Pro
Error processing line 1 of /Users/daniel/miniforge3/envs/pytorch/lib/python3.9/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/Users/daniel/miniforge3/envs/pytorch/lib/python3.9/site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
[INFO] Installing environment for https://github.com/prettier/prettier.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/Users/daniel/.cache/pre-commit/reposi83g34u/node_env-system/bin/node', '/Users/daniel/.nvm/versions/node/v17.3.1/bin/npm', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    npm WARN install Usage of the `--dev` option is deprecated. Use `--include=dev` instead.
    npm ERR! code ERESOLVE
    npm ERR! ERESOLVE unable to resolve dependency tree
    npm ERR! 
    npm ERR! While resolving: prettier@2.0.5
    npm ERR! Found: rollup@2.3.2
    npm ERR! node_modules/rollup
    npm ERR!   dev rollup@"2.3.2" from the root project
    npm ERR! 
    npm ERR! Could not resolve dependency:
    npm ERR! peer rollup@"^1.20.0" from @rollup/plugin-alias@3.0.1
    npm ERR! node_modules/@rollup/plugin-alias
    npm ERR!   dev @rollup/plugin-alias@"3.0.1" from the root project
    npm ERR! 
    npm ERR! Fix the upstream dependency conflict, or retry
    npm ERR! this command with --force, or --legacy-peer-deps
    npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
    npm ERR! 
    npm ERR! See /Users/daniel/.npm/eresolve-report.txt for a full report.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /Users/daniel/.npm/_logs/2022-02-04T00_24_37_309Z-debug-0.log
    
Check the log at /Users/daniel/.cache/pre-commit/pre-commit.log
```

### Describe the problem

Seems removing prettier section in .pre-commit-config.yaml would let it pass.

### Other info / logs

Logs pasted above.

**Comment by swheaton** [comment]
Think this is OBE
