### ISSUE TITLE
[BUG]Unhandled expcetion with convert

### ISSUE THREAD

**Issue by clustor** [voxel51/fiftyone#1606]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS
-   **FiftyOne installed from (pip or source)**: pip 
-   **FiftyOne version (run `fiftyone --version`)**: FiftyOne v0.14.4, Voxel51, Inc.
-   **Python version**: 3.9.10

### Commands to reproduce

```
fiftyone convert --input-dir=fiftyone/coco-2017/train --input-type=fiftyone.types.COCODetectionDataset --output-dir=iftyone/coco-2017-tfrecord --output-type=fiftyone.types.TFImageClassificationDataset
```

### Describe the problem

```
Uncaught exception
Traceback (most recent call last):
  File "/usr/local/bin/fiftyone", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/fiftyone/core/cli.py", line 2991, in main
    args.execute(args)
  File "/usr/local/lib/python3.9/site-packages/fiftyone/core/cli.py", line 2974, in <lambda>
    parser.set_defaults(execute=lambda args: command.execute(parser, args))
  File "/usr/local/lib/python3.9/site-packages/fiftyone/core/cli.py", line 336, in execute
    foud.convert_dataset(
  File "/usr/local/lib/python3.9/site-packages/fiftyone/utils/data/converters.py", line 121, in convert_dataset
    dataset.export(
  File "/usr/local/lib/python3.9/site-packages/fiftyone/core/collections.py", line 6127, in export
    _export(
  File "/usr/local/lib/python3.9/site-packages/fiftyone/core/collections.py", line 8134, in _export
    foud.export_samples(
  File "/usr/local/lib/python3.9/site-packages/fiftyone/utils/data/exporters.py", line 328, in export_samples
    write_dataset(
  File "/usr/local/lib/python3.9/site-packages/fiftyone/utils/data/exporters.py", line 381, in write_dataset
    _write_image_dataset(
  File "/usr/local/lib/python3.9/site-packages/fiftyone/utils/data/exporters.py", line 804, in _write_image_dataset
    dataset_exporter.export_sample(
  File "/usr/local/lib/python3.9/site-packages/fiftyone/utils/tf.py", line 710, in export_sample
    tf_example = self._example_generator.make_tf_example(
  File "/usr/local/lib/python3.9/site-packages/fiftyone/utils/tf.py", line 903, in make_tf_example
    img_bytes, img_shape, filename = self._parse_image_or_path(
  File "/usr/local/lib/python3.9/site-packages/fiftyone/utils/tf.py", line 865, in _parse_image_or_path
    img_bytes = tf.image.encode_jpeg(img)
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/ops/gen_image_ops.py", line 1546, in encode_jpeg
    _ops.raise_from_not_ok_status(e, name)
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 7186, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: image must be 3-dimensional[99,66] [Op:EncodeJpeg]
```

### Code to reproduce issue

```
#Download the images with this scripts

import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset(
    "coco-2017",
    splits=['train', 'validation', 'test'],
    label_types=["detections"],
    classes=["stop sign"],
    max_samples=5000
)
view = dataset.view()
print(view) 

```

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

**Comment by brimoor** [comment]
Good catch, this is resolved by https://github.com/voxel51/fiftyone/pull/1612 😄
