### ISSUE TITLE
[BUG] BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#1620]
On `fiftyone==0.14.4`, downloading the following dataset:

```py
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("imagenet-sample")
```

currently raises the error shown below:

```
Downloading dataset to '/Users/x/fiftyone/imagenet-sample'
Using existing archive '/Users/x/fiftyone/imagenet-sample/tmp-download/imagenet-sample.zip'
Extracting dataset...
Uncaught exception
Traceback (most recent call last):
 File "/Users/Documents/Python/general_experiments/load_dataset.py", line 4, in <module>
  dataset = foz.load_zoo_dataset("imagenet-sample")
 File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fiftyone/zoo/datasets/__init__.py", line 197, in load_zoo_dataset
  info, dataset_dir = download_zoo_dataset(
 File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fiftyone/zoo/datasets/__init__.py", line 116, in download_zoo_dataset
  return zoo_dataset.download_and_prepare(
 File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fiftyone/zoo/datasets/__init__.py", line 1047, in download_and_prepare
  ) = self._download_and_prepare(dataset_dir, scratch_dir, None)
 File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fiftyone/zoo/datasets/base.py", line 1306, in _download_and_prepare
  _download_and_extract_archive(
 File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fiftyone/zoo/datasets/base.py", line 2545, in _download_and_extract_archive
  etau.extract_archive(archive_path)
 File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/eta/core/utils.py", line 3523, in extract_archive
  extract_zip(archive_path, outdir=outdir, delete_zip=delete_archive)
 File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/eta/core/utils.py", line 3575, in extract_zip
  with zf.ZipFile(zip_path, "r", allowZip64=True) as f:
 File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/zipfile.py", line 1269, in __init__
  self._RealGetContents()
 File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
  raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

Process finished with exit code 1
```

However, this code ran with no errors last week, for example.

**Comment by brimoor** [comment]
This error is due to a recent change in the Google Drive API. This is fixed by https://github.com/voxel51/eta/pull/554 and will be included in the next release.

In the meantime, a workaround is to manually make the small change from https://github.com/voxel51/eta/pull/554 to your ETA install:

```py
import eta.core.web

# Locate the file that needs editing
print(eta.core.web.__file__)
```

delete the failed download folder:

```shell
DATASET_ZOO_DIR=$(fiftyone config dataset_zoo_dir)
rm -rf ${DATASET_ZOO_DIR}/imagenet-sample
```

and retry the download:

```py
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("imagenet-sample")
```

**Comment by Bassie1** [comment]
@brimoor I am getting the same error when downloading the "open-images-v6" dataset, I tried fix above, but am still getting an error. I identified one folder which errors each time- B in masks in the test set. Any ideas?

**Comment by Bassie1** [comment]
I realized that when I manually downloaded the folder, it downloaded empty as well. I was able to download the folder on a different computer, though, so I ran this code on the second computer without any issues. Still haven't figured out why it would not run on the first computer.
