### ISSUE TITLE
[Errno 24] Too many open files when call view.annotate(...) with 2000 `Open-Image` images

### ISSUE THREAD

**Issue by shaojun** [voxel51/fiftyone#1623]
Hi,
I'm trying to download a small subset with 2000 images of `Open Images` data of class `Bicycle`, and then upload the images and annotations to `CVAT`.
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 20.04.3 LTS, x64
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: FiftyOne v0.14.4, Voxel51, Inc.
-   **Python version**: Python 3.8.10 (default, Nov 26 2021, 20:14:08)

### Commands to reproduce

this is what I've done:
```
dataset = foz.load_zoo_dataset("open-images-v6", split="train", label_types=["detections"], classes=["Bicycle"], max_samples=2000, seed=51, shuffle=True, dataset_name="open-images-bicycle-mini-set-upload-to-cvat-2000-final",)
Downloading split 'train' to '/home/shao/fiftyone/open-images-v6/train' if necessary
Necessary images already downloaded
Existing download of split 'train' is sufficient
Loading 'open-images-v6' split 'train'
 100% |█████████████████████████████████████████████████████████████| 2000/2000 [9.5s elapsed, 0s remaining, 207.7 samples/s]       
Dataset 'open-images-bicycle-mini-set-upload-to-cvat-2000-final' created
>>> view = dataset.view()
>>> anno_key="cvat_existing_field_final"
>>> view.annotate(anno_key, label_field="detections",label_type="detections",classes=["Bicycle","Person"])
Uploading samples to CVAT...
Computing image metadata...
 100% |█████████████████████████████████████████████████████████████| 2000/2000 [1.8s elapsed, 0s remaining, 1.5K samples/s]        
Uncaught exception
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shao/.local/lib/python3.8/site-packages/fiftyone/core/collections.py", line 6272, in annotate
  File "/home/shao/.local/lib/python3.8/site-packages/fiftyone/utils/annotations.py", line 212, in annotate
  File "/home/shao/.local/lib/python3.8/site-packages/fiftyone/utils/cvat.py", line 3155, in upload_annotations
  File "/home/shao/.local/lib/python3.8/site-packages/fiftyone/utils/cvat.py", line 4095, in upload_samples
  File "/home/shao/.local/lib/python3.8/site-packages/fiftyone/utils/cvat.py", line 4741, in _create_task_upload_data
  File "/home/shao/.local/lib/python3.8/site-packages/fiftyone/utils/cvat.py", line 3955, in upload_data
OSError: [Errno 24] Too many open files: '/home/shao/fiftyone/open-images-v6/train/data/94b7ac9d54aad7be.jpg'

```

### Describe the problem

the upload to cvat failed.

### What areas of FiftyOne does this bug affect?

-   [x] `App`: FiftyOne application issue
-   [ ] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [x] No. I cannot contribute a bug fix at this time.

**Comment by ehofesmann** [comment]
1) The first error (`Too many open files`) is a duplicate of this: https://github.com/voxel51/fiftyone/issues/1448
It is resolved using the `task_size` parameter: https://voxel51.com/docs/fiftyone/integrations/cvat.html#large-annotation-runs


2) For the second error:
The image metadata is necessary when uploading samples to CVAT. It seems that there was an issue computing metadata for 93 of your samples. Check to see if those images were downloaded correctly. You can get the filepaths of those samples with the following:
```python
non_metadata_view = dataset.exists("metadata", False)
filepaths = non_metadata_view.values("filepath")
print(filepaths)
```

If there is an issue with them, you can delete those images and have FiftyOne redownload them by calling `foz.load_zoo_dataset` again for your subset of open images. If not, your choices are to either ignore those samples or attempt to manually populate the metadata for them using [ImageMetadata.build_for()](https://voxel51.com/docs/fiftyone/user_guide/using_datasets.html#metadata)

**Comment by shaojun** [comment]
@ehofesmann thanks for the reply.
for the missing `metadata` issue, I tried another round of download (by delete local previously created `open-images-v6` folder) and call `annotate(...)` again, can see the local folder `open-images-v6/train/data` contains **400** images, but from the code  below, seems all of them are missing `metadata`, so I try to rebuild them:
```

import fiftyone as fo
import fiftyone.zoo as foz
import sys
import uuid
dataset = foz.load_zoo_dataset("open-images-v6", split="train", label_types=["detections"], classes=["Bicycle"], 
    max_samples=100, seed=51, shuffle=True, 
    dataset_name="oi-bi-"+str(uuid.uuid4().hex),)
#show local web ui to check downloaded images.
#session = fo.launch_app(dataset)

#upload to CVAT
#view = dataset.view()
view = dataset.exists("metadata",False)
filepaths = view.values("filepath")
for fp in filepaths:
    missing_metadata = fo.ImageMetadata.build_for(fp)
    sample = fo.Sample(filepath=fp, metadata=missing_metadata)
    dataset.add_sample(sample)
    print(sample)
dataset.reload()
#print(filepaths)
anno_key="cvat_"+str(uuid.uuid4().hex)
#task_size=400,
view.annotate(anno_key, label_field="detections",label_type="detections",classes=["Bicycle","Person"])
```

the problem is it stuck there forever:

> 
> Existing download of split 'train' is sufficient
> Loading 'open-images-v6' split 'train'
>  100% |███████████████████████████████████████████████████████████████| 100/100 [483.2ms elapsed, 0s remaining, 207.0 samples/s]      
> Dataset 'oi-bi-8b9b16c6fc104140939c512f93946879' created
> <Sample: {
>     'id': '621f1deb12d4a2918ca6fb03',
>     'media_type': 'image',
>     'filepath': '/home/shao/fiftyone/open-images-v6/train/data/1213de300aa5a850.jpg',
>     'tags': BaseList([]),
>     'metadata': <ImageMetadata: {
>         'size_bytes': 182466,
>         'mime_type': 'image/jpeg',
>         'width': 680,
>         'height': 1024,
>         'num_channels': 3,
>     }>,
>     'detections': None,
> ......
> ......
> ......
> ......
> Uploading samples to CVAT...
> Computing image metadata...
>  100% |███████████████████████████████████████████████████████████████| 100/100 [341.8ms elapsed, 0s remaining, 292.6 samples/s]


I'm using a local deployed `CVAT` server, and the `quickstart` dataset can be successfully upload to my CVAT server.
