### ISSUE TITLE
compute_similarity() breaks the kernel in Jupyter Notebook, also when run as a python file.[BUG]

### ISSUE THREAD

**Issue by isspid** [voxel51/fiftyone#1631]
### Instructions

Thank you for submitting an issue. Please refer to our
[issue policy](https://www.github.com/voxel51/fiftyone/blob/develop/ISSUE_POLICY.md)
for information on what types of issues we address.

**Please fill in this template to ensure a timely and thorough response.**

-   Place an "x" between the brackets next to an option if it applies. Example:
    -   [x] Selected option
-   Please delete this section (all content above this line) before submitting
    the issue

### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows + Anaconda
-   **FiftyOne installed from (pip or source)**:pip
-   **FiftyOne version (run `fiftyone --version`)**:FiftyOne v0.14.4, Voxel51, Inc.
-   **Python version**:Python 3.7.11

### Commands to reproduce

As thoroughly as possible, please provide the Python and/or shell commands used
to encounter the issue. Application steps can be described in the next section.

```

```

### Describe the problem

Describe the problem clearly here. Include descriptions of the expected
behavior and the actual behavior.

### Code to reproduce issue

import fiftyone as fo
import fiftyone.zoo as foz
dataset_dir = r"C:\Users\istaka\Downloads\Floor plan dataset\Floor plan dataset\SFPI\SFPI\coco"

# The path to the COCO labels JSON file
dataset_type = fo.types.COCODetectionDataset

# Import the dataset
dataset1 = fo.Dataset.from_dir(
    dataset_type=fo.types.COCODetectionDataset,
    dataset_dir=dataset_dir,
)
import fiftyone.brain as fob
from fiftyone import ViewField as F

results = fob.compute_similarity(dataset1)

### Other info / logs

Location of the dataset is here: https://cloud.dfki.de/owncloud/index.php/s/mkg5HBBntRbNo8X

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x ] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ x] No. I cannot contribute a bug fix at this time.

**Comment by brimoor** [comment]
Hi @isspid this seems like some kind of PyTorch + Windows error. Can you provide more information, stack trace, etc? Can you try running some other PyTorch code to verify that PyTorch is working in other cases?

https://github.com/voxel51/fiftyone/issues/840#issuecomment-920979914 is relevant here.

`compute_similarity()` and `compute_uniqueness()` use different models by default, so your error shouldn't be seeing the `RuntimeError: Error(s) in loading state_dict for Network:` error reported in that issue. However, if you could follow the instructions in the comment I linked to try some other zoo models, that'd be helpful.

**Comment by TommeTao** [comment]
Hi @brimoor, I am running into the same issue on my Windows machine.

```
pytorch                   1.11.0          py3.9_cuda11.3_cudnn8_0    pytorch
torchaudio                0.11.0               py39_cu113    pytorch
torchvision               0.12.0               py39_cu113    pytorch
```

<details>
  <summary>The full error reads like follows ... click to expand!</summary>

```
Uncaught exception
Traceback (most recent call last):
  File ".\conda-env-dst-fo-torch\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File ".\conda-env-dst-fo-torch\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "%USERPROFILE%\.vscode\extensions\ms-python.python-2022.2.1924087327\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "%USERPROFILE%\.vscode\extensions\ms-python.python-2022.2.1924087327\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "%USERPROFILE%\.vscode\extensions\ms-python.python-2022.2.1924087327\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File ".\conda-env-dst-fo-torch\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File ".\conda-env-dst-fo-torch\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File ".\conda-env-dst-fo-torch\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File ".\tools\fiftyone\calculate_uniqueness.py", line 11, in <module>
    fob.compute_uniqueness(dataset)
  File "<frozen fiftyone.brain>", line 228, in compute_uniqueness
  File "<frozen fiftyone.brain.internal.core.uniqueness>", line 85, in compute_uniqueness
  File "<frozen fiftyone.brain.internal.models>", line 183, in load_model
  File ".\conda-env-dst-fo-torch\lib\site-packages\fiftyone\core\models.py", line 1508, in load_model     
    return config.build()
  File ".\conda-env-dst-fo-torch\lib\site-packages\eta\core\learning.py", line 296, in build
    return self._model_cls(self.config)
  File ".\conda-env-dst-fo-torch\lib\site-packages\fiftyone\utils\torch.py", line 218, in __init__        
    self._model = self._load_model(config)
  File ".\conda-env-dst-fo-torch\lib\site-packages\fiftyone\utils\torch.py", line 434, in _load_model     
    self._load_state_dict(model, config)
  File "<frozen fiftyone.brain.internal.models.torch>", line 44, in _load_state_dict
  File ".\conda-env-dst-fo-torch\lib\site-packages\torch\nn\modules\module.py", line 1497, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Network:
        Missing key(s) in state_dict: "prep\conv.weight", "prep\bn.weight", "prep\bn.bias", "prep\bn.running_mean", "prep\bn.running_var", "layer1\conv.weight", "layer1\bn.weight", "layer1\bn.bias", "layer1\bn.running_mean", "layer1\bn.running_var", "layer1\residual\res1\conv.weight", "layer1\residual\res1\bn.weight", "layer1\residual\res1\bn.bias", "layer1\residual\res1\bn.running_mean", "layer1\residual\res1\bn.running_var", "layer1\residual\res2\conv.weight", "layer1\residual\res2\bn.weight", "layer1\residual\res2\bn.bias", "layer1\residual\res2\bn.running_mean", "layer1\residual\res2\bn.running_var", "layer2\conv.weight", "layer2\bn.weight", "layer2\bn.bias", "layer2\bn.running_mean", "layer2\bn.running_var", "layer3\conv.weight", "layer3\bn.weight", "layer3\bn.bias", "layer3\bn.running_mean", "layer3\bn.running_var", "layer3\residual\res1\conv.weight", "layer3\residual\res1\bn.weight", "layer3\residual\res1\bn.bias", "layer3\residual\res1\bn.running_mean", "layer3\residual\res1\bn.running_var", "layer3\residual\res2\conv.weight", "layer3\residual\res2\bn.weight", "layer3\residual\res2\bn.bias", "layer3\residual\res2\bn.running_mean", "layer3\residual\res2\bn.running_var".
        Unexpected key(s) in state_dict: "prep_conv.weight", "prep_bn.weight", "prep_bn.bias", "prep_bn.running_mean", "prep_bn.running_var", "prep_bn.num_batches_tracked", "layer1_conv.weight", "layer1_bn.weight", "layer1_bn.bias", "layer1_bn.running_mean", "layer1_bn.running_var", "layer1_bn.num_batches_tracked", "layer1_residual_res1_conv.weight", "layer1_residual_res1_bn.weight", "layer1_residual_res1_bn.bias", "layer1_residual_res1_bn.running_mean", "layer1_residual_res1_bn.running_var", "layer1_residual_res1_bn.num_batches_tracked", "layer1_residual_res2_conv.weight", "layer1_residual_res2_bn.weight", "layer1_residual_res2_bn.bias", "layer1_residual_res2_bn.running_mean", "layer1_residual_res2_bn.running_var", "layer1_residual_res2_bn.num_batches_tracked", "layer2_conv.weight", "layer2_bn.weight", "layer2_bn.bias", "layer2_bn.running_mean", "layer2_bn.running_var", "layer2_bn.num_batches_tracked", "layer3_conv.weight", "layer3_bn.weight", "layer3_bn.bias", "layer3_bn.running_mean", "layer3_bn.running_var", "layer3_bn.num_batches_tracked", "layer3_residual_res1_conv.weight", "layer3_residual_res1_bn.weight", "layer3_residual_res1_bn.bias", "layer3_residual_res1_bn.running_mean", "layer3_residual_res1_bn.running_var", "layer3_residual_res1_bn.num_batches_tracked", "layer3_residual_res2_conv.weight", "layer3_residual_res2_bn.weight", "layer3_residual_res2_bn.bias", "layer3_residual_res2_bn.running_mean", "layer3_residual_res2_bn.running_var", "layer3_residual_res2_bn.num_batches_tracked".
```

</details>

> Can you try running some other PyTorch code to verify that PyTorch is working in other cases?

I have been running PyTorch successfully in other FiftyOne examples, such as [Image embeddings example](https://voxel51.com/docs/fiftyone/user_guide/brain.html#image-embeddings-example) and [Adding model predictions](https://voxel51.com/docs/fiftyone/recipes/adding_detections.html#Adding-model-predictions). So PyTorch seems to be working in general.

**Comment by brimoor** [comment]
@TommeTao your error is due to https://github.com/voxel51/fiftyone/issues/840. The default model for `compute_uniqueness()` does not seem to be Windows-compatible and we haven't had a chance to address that yet. 

https://github.com/voxel51/fiftyone/issues/840#issuecomment-920979914 is relevant though- you might find success trying another model.

**Comment by TommeTao** [comment]
@brimoor thanks, I saw #840. I [added a question](https://github.com/voxel51/fiftyone/issues/840#issuecomment-1072863158) regarding the [hint you provided](https://github.com/voxel51/fiftyone/issues/840#issuecomment-920979914) in the discussions of #840.

**Comment by isspid** [comment]
> Hi @isspid this seems like some kind of PyTorch + Windows error. Can you provide more information, stack trace, etc? Can you try running some other PyTorch code to verify that PyTorch is working in other cases?
> 
> [#840 (comment)](https://github.com/voxel51/fiftyone/issues/840#issuecomment-920979914) is relevant here.
> 
> `compute_similarity()` and `compute_uniqueness()` use different models by default, so your error shouldn't be seeing the `RuntimeError: Error(s) in loading state_dict for Network:` error reported in that issue. However, if you could follow the instructions in the comment I linked to try some other zoo models, that'd be helpful.

After converting the images of the dataset from tfif to jpeg, the error stopped occurring.  Should I close the issue?

**Comment by brimoor** [comment]
Hmm thanks for identifying the root cause. I updated the issue's title to reflect the actual error. It would be nice if TIFF images were gracefully handled, so we can leave this issue open for now.
