### ISSUE TITLE
[SETUP-BUG]

### ISSUE THREAD

**Issue by michaelku1** [voxel51/fiftyone#1673]
### System information

-   **OS Platform and Distribution**:  Linux Ubuntu 18.04
-   **FiftyOne installed from**: pip
-   **FiftyOne version**: latest version
-   **Python version**: 3.6

### Commands to reproduce

```
import fiftyone
```

### Describe the problem

Uncaught exception
Traceback (most recent call last):
  File "debug.py", line 10, in <module>
    import fiftyone as fo
  File "/scratch2/users/cku/anaconda/envs/DAnA/lib/python3.6/site-packages/fiftyone/__init__.py", line 25, in <module>
    from fiftyone.__public__ import *
  File "/scratch2/users/cku/anaconda/envs/DAnA/lib/python3.6/site-packages/fiftyone/__public__.py", line 14, in <module>
    foo.establish_db_conn(config)
  File "/scratch2/users/cku/anaconda/envs/DAnA/lib/python3.6/site-packages/fiftyone/core/odm/database.py", line 79, in establish_db_conn
    _db_service = fos.DatabaseService()
  File "/scratch2/users/cku/anaconda/envs/DAnA/lib/python3.6/site-packages/fiftyone/core/service.py", line 80, in __init__
    self.start()
  File "/scratch2/users/cku/anaconda/envs/DAnA/lib/python3.6/site-packages/fiftyone/core/service.py", line 209, in start
    for process in fosu.find_processes_by_args(self._service_args):
  File "/scratch2/users/cku/anaconda/envs/DAnA/lib/python3.6/site-packages/fiftyone/service/util.py", line 93, in find_processes_by_args
    for p in psutil.process_iter(["cmdline", "username"]):
TypeError: process_iter() takes 0 positional arguments but 1 was given

**Comment by michaelku1** [comment]
Problem solved when I updated psutil module to 5.8.0. Closing this issue.
