### ISSUE TITLE
[BUG] mongoengine error: FieldDoesNotExist

### ISSUE THREAD

**Issue by alen-smajic** [voxel51/fiftyone#1708]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: v0.15.0.1
-   **Python version**: 3.8

### Commands to reproduce

As thoroughly as possible, please provide the Python and/or shell commands used
to encounter the issue. Application steps can be described in the next section.

```
# commands here
```

### Describe the problem

Describe the problem clearly here. Include descriptions of the expected
behavior and the actual behavior.

I have uploaded a custom dataset to fiftyone as well as the detection results of two detection models. 
To speed up the process, I ran two evaluations in parallel for the two models (something I shouldn't have done as it turns out). It appears that the second evaluation was overwriting the first one the whole time. When I logged the dataset to the console I realized that the field for the first evaluation is missing (the specified eval_key was not present, only the one from the second evaluation). Once I realized this, I wanted to rerun the evaluation individually however I am receiving the following error:

```
Uncaught exception
Traceback (most recent call last):
  File "/home/alen/Master_Thesis/venv/lib/python3.8/site-packages/fiftyone/core/dataset.py", line 4419, in _sample_dict_to_doc
    return self._sample_doc_cls.from_dict(d, extended=False)
  File "/home/alen/Master_Thesis/venv/lib/python3.8/site-packages/fiftyone/core/odm/document.py", line 303, in from_dict
    return cls._from_son(d)
  File "/home/alen/Master_Thesis/venv/lib/python3.8/site-packages/mongoengine/base/document.py", line 783, in _from_son
    obj = cls(
  File "/home/alen/Master_Thesis/venv/lib/python3.8/site-packages/mongoengine/base/document.py", line 99, in __init__
    raise FieldDoesNotExist(msg)
mongoengine.errors.FieldDoesNotExist: The fields "{'eval_prediction_FCOS_ResNet50_OD_fn', 'eval_prediction_FCOS_ResNet50_OD_tp', 'eval_prediction_FCOS_ResNet50_OD_fp'}" do not exist on the document "samples.2022.04.21.11.24.18"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "evaluate.py", line 577, in <module>
    main()
  File "evaluate.py", line 573, in main
    fo_kia.upload_model_predictions(cfg['checkpoint_path'], cfg['gpu_id'])
  File "evaluate.py", line 484, in upload_model_predictions
    for sample in pb(self.dataset):
  File "/home/alen/Master_Thesis/venv/lib/python3.8/site-packages/eta/core/utils.py", line 1660, in __next__
    val = next(self._iterator)
  File "/home/alen/Master_Thesis/venv/lib/python3.8/site-packages/fiftyone/core/dataset.py", line 1297, in iter_samples
    for sample in self._iter_samples(pipeline):
  File "/home/alen/Master_Thesis/venv/lib/python3.8/site-packages/fiftyone/core/dataset.py", line 1305, in _iter_samples
    doc = self._sample_dict_to_doc(d)
  File "/home/alen/Master_Thesis/venv/lib/python3.8/site-packages/fiftyone/core/dataset.py", line 4425, in _sample_dict_to_doc
    return self._sample_doc_cls.from_dict(d, extended=False)
  File "/home/alen/Master_Thesis/venv/lib/python3.8/site-packages/fiftyone/core/odm/document.py", line 303, in from_dict
    return cls._from_son(d)
  File "/home/alen/Master_Thesis/venv/lib/python3.8/site-packages/mongoengine/base/document.py", line 783, in _from_son
    obj = cls(
  File "/home/alen/Master_Thesis/venv/lib/python3.8/site-packages/mongoengine/base/document.py", line 99, in __init__
    raise FieldDoesNotExist(msg)
mongoengine.errors.FieldDoesNotExist: The fields "{'eval_prediction_FCOS_ResNet50_OD_fn', 'eval_prediction_FCOS_ResNet50_OD_tp', 'eval_prediction_FCOS_ResNet50_OD_fp'}" do not exist on the document "samples.2022.04.21.11.24.18"
```

In the error message you can see the eval key, which I specified for the first evaluation (eval_prediction_FCOS_ResNet50_OD). It appears that it is still somewhere stored and I cannot remove it properly. Is there any way to repair the database, because uploading the dataset again within a new daset instance will take a long time and I would like to avoid this if possible :)

### Code to reproduce issue

Provide a reproducible test case that is the bare minimum necessary to generate
the problem.

### Other info / logs

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and
files should be attached. Please do not use screenshots for sharing text. Code
snippets should be used instead when providing tracebacks, logs, etc.

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [ X] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [X ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

**Comment by brimoor** [comment]
Try this:

```py
import fiftyone as fo

dataset = fo.load_dataset(...)

# Add the fields back to the dataset's schema that are missing
dataset.add_sample_field("eval_prediction_FCOS_ResNet50_OD_fn", fo.FloatField)
dataset.add_sample_field("eval_prediction_FCOS_ResNet50_OD_tp", fo.FloatField)
dataset.add_sample_field("eval_prediction_FCOS_ResNet50_OD_fp", fo.FloatField)

# Delete the evaluation
dataset.delete_evaluation("eval_prediction_FCOS_ResNet50_OD")
```

**Comment by alen-smajic** [comment]
``
Uncaught exception
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alen/Master_Thesis/venv/lib/python3.8/site-packages/fiftyone/core/collections.py", line 2159, in delete_evaluation
    foev.EvaluationMethod.delete_run(self, eval_key)
  File "/home/alen/Master_Thesis/venv/lib/python3.8/site-packages/fiftyone/core/runs.py", line 564, in delete_run
    run_doc = cls._get_run_doc(samples, key)
  File "/home/alen/Master_Thesis/venv/lib/python3.8/site-packages/fiftyone/core/runs.py", line 608, in _get_run_doc
    raise ValueError(
ValueError: Dataset has no evaluation key 'eval_prediction_FCOS_ResNet50_OD'
``

**Comment by brimoor** [comment]
Okay no worries, just manually delete any fields you don't want using `dataset.delete_sample_field()`.

But anyway, your dataset should be usable again.

**Comment by alen-smajic** [comment]
Yep that solved the problem. Thank you very much :)
