### ISSUE TITLE
[BUG] Cannot provide ./relative_paths in YOLOv5 format

### ISSUE THREAD

**Issue by defrag-bambino** [voxel51/fiftyone#1716]
### System information

-  Linux Ubuntu 20.04
-   FiftyOne installed from pip
-   FiftyOne v0.15.1, Voxel51, Inc.
-   Python 3.8.10

### Commands to reproduce

`fiftyone convert --input-dir '/home/me/Desktop/Datasets/MAV-VID' --input-type fiftyone.types.YOLOv5Dataset --output-dir '/home/me/Desktop/Datasets/MAV-VID-COCO' --output-type fiftyone.types.COCODetectionDataset
`

### Describe the problem

I have a YOLOv5 Dataset structured like this:
MAV-VID
   - images
   - labels
   - train.txt
   - test.txt
   - dataset.yaml

where train.txt and test.txt look like this:
./images/45_00002069.jpg
./images/8_00000277.jpg
./images/8_00001444.jpg
..., i.e. containing RELATIVE paths to the images.

Now, when running the above command to convert this YOLOv5 Dataset to another format (COCO in this case), fiftyone crashes while throwing the following error:

Uncaught exception
Traceback (most recent call last):
  File "/home/me/.local/bin/fiftyone", line 8, in <module>
    sys.exit(main())
  File "/home/me/.local/lib/python3.8/site-packages/fiftyone/core/cli.py", line 3031, in main
    args.execute(args)
  File "/home/me/.local/lib/python3.8/site-packages/fiftyone/core/cli.py", line 3014, in <lambda>
    parser.set_defaults(execute=lambda args: command.execute(parser, args))
  File "/home/me/.local/lib/python3.8/site-packages/fiftyone/core/cli.py", line 370, in execute
    foud.convert_dataset(
  File "/home/me/.local/lib/python3.8/site-packages/fiftyone/utils/data/converters.py", line 112, in convert_dataset
    dataset.add_importer(dataset_importer, label_field=label_field)
  File "/home/me/.local/lib/python3.8/site-packages/fiftyone/core/dataset.py", line 3076, in add_importer
    return foud.import_samples(
  File "/home/me/.local/lib/python3.8/site-packages/fiftyone/utils/data/importers.py", line 118, in import_samples
    with dataset_importer:
  File "/home/me/.local/lib/python3.8/site-packages/fiftyone/utils/data/importers.py", line 743, in __enter__
    self.setup()
  File "/home/me/.local/lib/python3.8/site-packages/fiftyone/utils/yolo.py", line 512, in setup
    labels_path = _get_yolo_v5_labels_path(image_path)
  File "/home/me/.local/lib/python3.8/site-packages/fiftyone/utils/yolo.py", line 1070, in _get_yolo_v5_labels_path
    raise ValueError(
ValueError: Invalid image path 'images/12_00000538.jpg'. YOLOv5 image paths must contain '/images/', which is replaced with '/labels/' to locate the corresponding labels

However, when I change the filepaths in the train.txt and test.txt to ABSOLUTE paths, i.e. /home/user/Datasets/..../MAV-VID/images/..., fiftyone converts them just fine.
I suppose this is not the intended behavior?

### Code to reproduce issue

Provide a reproducible test case that is the bare minimum necessary to generate
the problem.

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [X] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [X] No. I cannot contribute a bug fix at this time.

**Comment by brimoor** [comment]
Good catch! This is patched in https://github.com/voxel51/fiftyone/pull/1721.
