### ISSUE TITLE
[BUG] After migrating to 0.16.1, cannot connect to App

### ISSUE THREAD

**Issue by palol** [voxel51/fiftyone#1802]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
-   **FiftyOne installed from (pip or source)**: from pip
-   **FiftyOne version (run `fiftyone --version`)**: 0.16.1
-   **Python version**: 3.9

### Commands to reproduce

As thoroughly as possible, please provide the Python and/or shell commands used
to encounter the issue. Application steps can be described in the next section.

Set-up:
1. On remote server, create docker container that runs Jupyter Lab via: `docker build . -t lookdeep/fiftyone-notebook -f ./Dockerfile_notebook`
    * see docker file [Dockerfile_notebook.txt](https://github.com/voxel51/fiftyone/files/8790419/Dockerfile_notebook.txt) (need to drop `".txt"` extension)
3. On remote server, run docker container and expose additional port for the App via: `SHARED_DIR=/media/storage2/fiftyone; DATA_DIR=/media/storage4/ld-data && docker run   -v ${SHARED_DIR}:/fiftyone   -v ${DATA_DIR}:/images   --gpus '"device=1"'   --shm-size=60gb    -p 5160:5160   -p 5195:5195   -it  lookdeep/fiftyone-notebook` 
4. Downgrade fiftyone to 0.15.1 -> create dataset
5. Upgrade fiftyone to 0.16.1 -> migrate dataset
6. Open a new notebook
7. Run the following code

```
import fiftyone as fo
import fiftyone.constants as foc

foc.DEV_INSTALL = True

name_dataset = "MAIN"
dataset = fo.load_dataset(name_dataset)

session = fo.launch_app(auto=False, port=5160) 
```

### Describe the problem

The problem has two parts. First, the App is not running or being connected to. Second, when session is launched again, output suggests that the session is connected, the App says "not connected". 

### Code to reproduce issue

See "Commands to reproduce"

### Other info / logs

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and
files should be attached. Please do not use screenshots for sharing text. Code
snippets should be used instead when providing tracebacks, logs, etc.

Here is the traceback
```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7efe38bd13d0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=5160): Max retries exceeded with url: /fiftyone (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efe38bd13d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/fiftyone/core/session/client.py", line 98, in run_client
    raise e
  File "/usr/local/lib/python3.9/dist-packages/fiftyone/core/session/client.py", line 93, in run_client
    _ping(f"{self.origin}/fiftyone")
  File "/usr/local/lib/python3.9/dist-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python3.9/dist-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python3.9/dist-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.9/dist-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/lib/python3.9/dist-packages/fiftyone/core/session/client.py", line 37, in _ping
    requests.get(url)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5160): Max retries exceeded with url: /fiftyone (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efe38bd13d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

### What areas of FiftyOne does this bug affect?

-   [X] `App`: FiftyOne application issue
-   [ ] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [X] No. I cannot contribute a bug fix at this time.

**Comment by palol** [comment]
Previously reached out to @benjaminpkane when version 0.16.0 was released. The original issue was that the "App server does not seem to be running, which is odd". Nothing else is running on the port, so I'm not sure what else to do. 

The tentative fix is to stay on version 0.15.1

**Comment by benjaminpkane** [comment]
Hi @palol. Thank you for making the issue.

The error indicates that a server is not running on the specified port, which means the server failed to start for some reason.

You can try starting the server directly to make sure it is working.

```sh
python -c "import fiftyone.server.main as fom; print(fom.__file__)" # path to server
```

```sh
python /path/to/server/main.py
```

The server will exit early, perhaps with an error, if there is an issue.


If that works, i.e. the server does not exit, then it would help to know if this is just a notebook issue, or something more. If it is just a notebook, then a normal [remote session](https://voxel51.com/docs/fiftyone/environments/index.html#remote-data) should work.

**Comment by SauceCat** [comment]
Got the same issue. I found from 0.16.0, starlette was introduced, just wondering whether that's the root cause.

**Comment by swheaton** [comment]
believe this is an old error, please open a new one if it persists in latest FO versions
