### ISSUE TITLE
[BUG] Problems with patches views and session.view property

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#1807]
### System Information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 11.6.5
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: 0.16.1
-   **Python version**: 3.9

### Bugs

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
patches = dataset.to_patches("ground_truth")

session = fo.launch_app(dataset)

session.view = patches  # fails with error below
```

```
Error: invalid path uniqueness
at http://localhost:5151/assets/index.4033b8d5.js:191:11861
at a (http://localhost:5151/assets/vendor.f3a8bf7d.js:51:287465)
at w (http://localhost:5151/assets/vendor.f3a8bf7d.js:51:276411)
at http://localhost:5151/assets/vendor.f3a8bf7d.js:51:274973
```

```py
# Recover from failed state
session.dataset = None
session.refresh()

session = fo.launch_app(patches)  # this actually works

session.view = dataset.limit(10)  # fails with error below
```

```
Error: invalid path sample_id
at http://localhost:5151/assets/index.4033b8d5.js:191:11861
at a (http://localhost:5151/assets/vendor.f3a8bf7d.js:51:287465)
at w (http://localhost:5151/assets/vendor.f3a8bf7d.js:51:276411)
at http://localhost:5151/assets/vendor.f3a8bf7d.js:51:274973
```

**Comment by brimoor** [comment]
Resolved by https://github.com/voxel51/fiftyone/pull/1808.
