### ISSUE TITLE
Issues Loading Full COCO Dataset

### ISSUE THREAD

**Issue by MikeLud** [voxel51/fiftyone#1905]
When I try to download COCO Dataset I get the below error
`
>>> import fiftyone as fo
>>> import fiftyone.zoo as foz
>>>
>>> dataset = foz.load_zoo_dataset(
...     "coco-2017",
...     splits=('train', 'validation', 'test'),
...     label_types=["detections"],
... )
Downloading split 'train' to 'C:\Users\mikel\fiftyone\coco-2017\train' if necessary
Found annotations at 'C:\Users\mikel\fiftyone\coco-2017\raw\instances_train2017.json'
Downloading images to 'C:\Users\mikel\fiftyone\coco-2017\tmp-download\train2017.zip'
 100% |███████████████████████████████████████████████████████████████████████████████████|  144.1Gb/144.1Gb [8.8m elapsed, 0s remaining, 170.8Mb/s]
Extracting images to 'C:\Users\mikel\fiftyone\coco-2017\train\data'
Uncaught exception
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mikel\anaconda3\envs\FiftyOne\lib\site-packages\fiftyone\zoo\datasets\__init__.py", line 197, in load_zoo_dataset
    info, dataset_dir = download_zoo_dataset(
  File "C:\Users\mikel\anaconda3\envs\FiftyOne\lib\site-packages\fiftyone\zoo\datasets\__init__.py", line 116, in download_zoo_dataset
    return zoo_dataset.download_and_prepare(
  File "C:\Users\mikel\anaconda3\envs\FiftyOne\lib\site-packages\fiftyone\zoo\datasets\__init__.py", line 1004, in download_and_prepare
    ) = self._download_and_prepare(split_dir, scratch_dir, split)
  File "C:\Users\mikel\anaconda3\envs\FiftyOne\lib\site-packages\fiftyone\zoo\datasets\base.py", line 1132, in _download_and_prepare
    num_samples, classes, downloaded = fouc.download_coco_dataset_split(
  File "C:\Users\mikel\anaconda3\envs\FiftyOne\lib\site-packages\fiftyone\utils\coco.py", line 1560, in download_coco_dataset_split
    etau.extract_zip(images_zip_path, delete_zip=False)
  File "C:\Users\mikel\anaconda3\envs\FiftyOne\lib\site-packages\eta\core\utils.py", line 3576, in extract_zip
    f.extractall(outdir)
  File "C:\Users\mikel\anaconda3\envs\FiftyOne\lib\zipfile.py", line 1643, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\mikel\anaconda3\envs\FiftyOne\lib\zipfile.py", line 1698, in _extract_member
    shutil.copyfileobj(source, target)
  File "C:\Users\mikel\anaconda3\envs\FiftyOne\lib\shutil.py", line 195, in copyfileobj
    buf = fsrc_read(length)
  File "C:\Users\mikel\anaconda3\envs\FiftyOne\lib\zipfile.py", line 925, in read
    data = self._read1(n)
  File "C:\Users\mikel\anaconda3\envs\FiftyOne\lib\zipfile.py", line 1015, in _read1
    self._update_crc(data)
  File "C:\Users\mikel\anaconda3\envs\FiftyOne\lib\zipfile.py", line 943, in _update_crc
    raise BadZipFile("Bad CRC-32 for file %r" % self.name)
zipfile.BadZipFile: Bad CRC-32 for file 'train2017/000000016518.jpg'
>>>
>>> session = fo.launch_app(dataset)
Uncaught exception
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'dataset' is not defined`

**Comment by brimoor** [comment]
This error means that the zip file you downloaded was corrupted. Since the zip is coming from COCO's official website, the likely issue is that an error was encountered while you were downloading it.

Since I am quite sure this is not an issue with the FiftyOne library itself (the other splits were downloaded and extracted fine, for example), I am going to close this issue for now. However, feel free to reopen it if you try again and the same problem occurs and you believe FiftyOne is indeed to blame.

**Comment by MikeLud** [comment]
I found what was causing the COCO2017 download issue. It was bad RAM, I installed some new RAM and all the download issues went away.
