### ISSUE TITLE
[BUG] BSONObjectTooLarge when computing App statistics for video datasets

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#1914]
Users have reported getting `BSONObjectTooLarge` errors on `fiftyone==0.16.5` as shown below when trying to load video datasets  with frame-level labels in the App:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/fiftyone/server/decorators.py", line 33, in wrapper
    response = await func(endpoint, request, data, *args)
  File "/usr/local/lib/python3.9/dist-packages/fiftyone/server/routes/aggregations.py", line 46, in post
    return {"aggregations": await get_app_statistics(view, filters)}
  File "/usr/local/lib/python3.9/dist-packages/fiftyone/server/routes/aggregations.py", line 71, in get_app_statistics
    results = await view._async_aggregate(ordered)
  File "/usr/local/lib/python3.9/dist-packages/fiftyone/core/collections.py", line 7181, in _async_aggregate
    _results = await foo.aggregate(collection, pipelines)
  File "/usr/local/lib/python3.9/dist-packages/fiftyone/core/odm/database.py", line 319, in _do_async_pooled_aggregate
    return await asyncio.gather(
  File "/usr/local/lib/python3.9/dist-packages/fiftyone/core/odm/database.py", line 325, in _do_async_aggregate
    return [i async for i in collection.aggregate(pipeline, allowDiskUse=True)]
  File "/usr/local/lib/python3.9/dist-packages/fiftyone/core/odm/database.py", line 325, in <listcomp>
    return [i async for i in collection.aggregate(pipeline, allowDiskUse=True)]
  File "/usr/local/lib/python3.9/dist-packages/motor/core.py", line 1158, in next
    if self.alive and (self._buffer_size() or await self._get_more()):
  File "/usr/local/lib/python3.9/dist-packages/motor/core.py", line 1626, in _on_started
    pymongo_cursor = future.result()
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pymongo/collection.py", line 2502, in aggregate
    return self._aggregate(_CollectionAggregationCommand,
  File "/usr/local/lib/python3.9/dist-packages/pymongo/collection.py", line 2419, in _aggregate
    return self.__database.client._retryable_read(
  File "/usr/local/lib/python3.9/dist-packages/pymongo/mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "/usr/local/lib/python3.9/dist-packages/pymongo/aggregation.py", line 137, in get_cursor
    result = sock_info.command(
  File "/usr/local/lib/python3.9/dist-packages/pymongo/pool.py", line 710, in command
    return command(self, dbname, spec, secondary_ok,
  File "/usr/local/lib/python3.9/dist-packages/pymongo/network.py", line 161, in command
    helpers._check_command_response(
  File "/usr/local/lib/python3.9/dist-packages/pymongo/helpers.py", line 167, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: BSONObj size: 23974544 (0x16DD290) is invalid. Size must be between 0 and 16793600(16MB) First element: ok: 0.0, full error: {'ok': 0.0, 'errmsg': 'BSONObj size: 23974544 (0x16DD290) is invalid. Size must be between 0 and 16793600(16MB) First element: ok: 0.0', 'code': 10334, 'codeName': 'BSONObjectTooLarge'}
```

**Comment by brimoor** [comment]
Duplicate of https://github.com/voxel51/fiftyone/issues/1607.
