### ISSUE TITLE
[FR] torchvision: use weights instead of depcrecated pretrained parameter

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#1977]
When loading most Torch models from the FiftyOne Model Zoo with `torchvision==0.13.0` installed:

```py
import fiftyone.zoo as foz

model = foz.load_zoo_model("mobilenet-v2-imagenet-torch")
```

I see the following error:

```
/path/to/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning:
The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.

/path/to/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning:
Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=MobileNet_V2_Weights.IMAGENET1K_V1`. You can also use `weights=MobileNet_V2_Weights.DEFAULT` to get the most up-to-date weights.
```

So it looks like, when `torchvision==0.15.0` is released (as of this writing, the [latest version is 0.13.0](https://pypi.org/project/torchvision/) so this isn't a problem yet...), we'll need to follow the above advice and use `weights='ResNet50_Weights.DEFAULT'` instead of `pretrained=True`.

Here's where the `pretrained=True` is currently coming from:
https://github.com/voxel51/fiftyone/blob/79fe485ae8da86a7aef156fdf466f6f7d81a7045/fiftyone/zoo/models/manifest-torch.json#L700-L710

Note that, if we're going to update the syntax, we either need to require a sufficiently new `torchvision` version (unsure if `weights` was available prior to `torchvision==0.13.0`, for example), or we need to bake some logic into the code to selectively use the appropriate parameter based on the installed `torchvision` version...

**Comment by n3ry7** [comment]
I would like to solve this issue as my first contribution. II tried to replicate the issue but I got another error instead.

Traceback (most recent call last):
  File "/home/nery/test.py", line 4, in <module>
    model = foz.load_zoo_model("mobilenet-v2-imagenet-torch")
  File "/home/nery/fiftyone/fiftyone/zoo/models/__init__.py", line 188, in load_zoo_model
    error_level = fo.config.requirement_error_level
AttributeError: module 'fiftyone' has no attribute 'config'

**Comment by brimoor** [comment]
Related conversation: https://fiftyone-users.slack.com/archives/C0189A476EQ/p1673357874994249

**Comment by ai2ys** [comment]
> When loading most Torch models from the FiftyOne Model Zoo with `torchvision==0.13.0` installed:
> 
> ```python
> import fiftyone.zoo as foz
> 
> model = foz.load_zoo_model("mobilenet-v2-imagenet-torch")
> ```
> 
> I see the following error:
> 
> ```
> /path/to/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning:
> The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
> 
> /path/to/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning:
> Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=MobileNet_V2_Weights.IMAGENET1K_V1`. You can also use `weights=MobileNet_V2_Weights.DEFAULT` to get the most up-to-date weights.
> ```
> 
> So it looks like, when `torchvision==0.15.0` is released (as of this writing, the [latest version is 0.13.0](https://pypi.org/project/torchvision/) so this isn't a problem yet...), we'll need to follow the above advice and use `weights='ResNet50_Weights.DEFAULT'` instead of `pretrained=True`.
> 
> Here's where the `pretrained=True` is currently coming from:
> 
> https://github.com/voxel51/fiftyone/blob/79fe485ae8da86a7aef156fdf466f6f7d81a7045/fiftyone/zoo/models/manifest-torch.json#L700-L710
> 
> Note that, if we're going to update the syntax, we either need to require a sufficiently new `torchvision` version (unsure if `weights` was available prior to `torchvision==0.13.0`, for example), or we need to bake some logic into the code to selectively use the appropriate parameter based on the installed `torchvision` version...

Just checked on availability of parameter `weights` for torchvision version `0.12.0`. There only the parameter `pretrained` is available.
https://github.com/pytorch/vision/blob/v0.12.0/torchvision/models/mobilenetv2.py

**Comment by helioshe4** [comment]
Hi, is this still an ongoing issue? I'd be willing to look into it and try and fix it.

**Comment by brimoor** [comment]
@helioshe4 a contribution would be welcome, thanks! The problem here is that we need to support these two syntaxes:

```py
# torchvision < 0.13
model = torchvision.models.mobilenet.mobilenet_v2(pretrained=True)

# torchvision >= 0.13
model = torchvision.models.mobilenet.mobilenet_v2(weights='ResNet50_Weights.DEFAULT)
```

I suppose we could just update the manifest JSON to use `weights` instead of `pretrained` everywhere, and then add a `torchvision>=0.13` requirement.

For bonus points, you could add a check [in this function](https://github.com/voxel51/fiftyone/blob/ab947f50c5998609aeef99204295e8ffcb93f599/fiftyone/zoo/models/torch.py#L94-L106) that would replace `weights=XXX` with `pretrained=True` only when `torchvision<0.13` is installed. So that we would not have to strictly require `torchvision>=0.13`.

**Comment by helioshe4** [comment]
Hello @brimoor , just wanted to check in.
An example warning when I use pretrained=True prints 
```
The current behavior is equivalent to passing `weights=DeepLabV3_ResNet101_Weights.COCO_WITH_VOC_LABELS_V1`. 
You can also use `weights=DeepLabV3_ResNet101_Weights.DEFAULT` to get the most up-to-date weights.
```
Should I replace the pretrained:true in the manifest-torch json file using the "equivalent" (in this case, DeepLabV3_ResNet101_Weights.COCO_WITH_VOC_LABELS_V1') weights, or the .DEFAULT weights?

PyTorch docs says the two are the same, but I guess that would change if the weights ever get updated.
https://pytorch.org/vision/main/models/generated/torchvision.models.segmentation.deeplabv3_resnet101.html

I hope that made sense.
Thanks

**Comment by brimoor** [comment]
I think using `.DEFAULT` is a good idea because it will make the code more future-proof. If torchvision authors decide to update the the default weights, FiftyOne users will likely want the same update.

**Comment by helioshe4** [comment]
Hello @brimoor , I've submitted a pr here #3347

**Comment by Ibnathism** [comment]
> @helioshe4 a contribution would be welcome, thanks! The problem here is that we need to support these two syntaxes:
> 
> ```python
> # torchvision < 0.13
> model = torchvision.models.mobilenet.mobilenet_v2(pretrained=True)
> 
> # torchvision >= 0.13
> model = torchvision.models.mobilenet.mobilenet_v2(weights=ResNet50_Weights.DEFAULT)
> ```
> 
> I suppose we could just update the [manifest JSON](https://github.com/voxel51/fiftyone/blob/develop/fiftyone/zoo/models/manifest-torch.json) to use `weights` instead of `pretrained` everywhere, and then add a `torchvision>=0.13` requirement.
> 
> For bonus points, perhaps you could add a check [in this function](https://github.com/voxel51/fiftyone/blob/ab947f50c5998609aeef99204295e8ffcb93f599/fiftyone/zoo/models/torch.py#L94-L106) that would replace `weights=XXX` with `pretrained=True` only when `torchvision<0.13` is installed. So that we would not have to strictly require `torchvision>=0.13` 😄

Hey, I need to make `pretrained = False`. What should I do in that case?

**Comment by brimoor** [comment]
@Ibnathism here's a couple helpful resources depending on what you're waning to achieve:
- Load a customized model from Torch Hub: https://docs.voxel51.com/integrations/pytorch_hub.html
- Load an arbitrary custom Torch model: https://docs.voxel51.com/user_guide/model_zoo/index.html#using-custom-models
