### ISSUE TITLE
[BUG] Desktop App is not compatible with plugins-and-groups changes

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#2001]
The Desktop App is not currently compatible with the changes introduced in https://github.com/voxel51/fiftyone/pull/1955:

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart-groups")

session = fo.launch_app(dataset, desktop=True)
```

```
Desktop App launched.

Subprocess ['yarn', 'start-desktop'] exited with error 1:
internal/modules/cjs/loader.js:1172
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/Brian/dev/fiftyone/app/node_modules/vite/bin/vite.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1172:13)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_REQUIRE_ESM'
```

**Comment by benjaminpkane** [comment]
I cannot reproduce. Are you using node 18.1?

```
nvm current # version
nvm install 18.1.0
nvm alias default 18.1.0
```

**Comment by brimoor** [comment]
Hmm my bad, my `nvm current` was indeed old...

I'm quite perplexed how that happened because it seems the install script always tries to use the correct version:
https://github.com/voxel51/fiftyone/blob/c7d45d02a5f63e8318244e4baa8289ac5c6533e1/install.bash#L101-L102

Anyhow, confirmed that the App is working on `plugins-and-groups` when `nvm current==18.1.0`.

 Thank you 🙌
