### ISSUE TITLE
`fiftyone app connect` still tries to load the dataset locally

### ISSUE THREAD

**Issue by lethosor** [voxel51/fiftyone#208]
I'm testing on a Windows machine with no datasets available and connecting to a Linux machine with `cifar10` downloaded. Running `fiftyone app launch cifar10 --remote` on Linux, then `fiftyone app connect` on Windows brings up a working dashboard but produces these errors in the Windows console whenever I click on an image:

```
Exception in thread Thread-11:
Traceback (most recent call last):
  File "c:\users\test\env\lib\site-packages\mongoengine\queryset\base.py", line 260, in get
    result = next(queryset)
  File "c:\users\test\env\lib\site-packages\mongoengine\queryset\base.py", line 1590, in __next__
    raw_doc = next(self._cursor)
  File "c:\users\test\env\lib\site-packages\pymongo\cursor.py", line 1164, in next
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\test\env\lib\site-packages\fiftyone\core\dataset.py", line 1616, in _load_dataset
    _meta = foo.ODMDataset.objects.get(name=name)
  File "c:\users\test\env\lib\site-packages\mongoengine\queryset\base.py", line 263, in get
    raise queryset._document.DoesNotExist(msg)
fiftyone.core.odm.dataset.DoesNotExist: ODMDataset matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\test\env\lib\site-packages\socketio\client.py", line 616, in _handle_eio_message
    self._handle_event(pkt.namespace, pkt.id, pkt.data)
  File "c:\users\test\env\lib\site-packages\socketio\client.py", line 500, in _handle_event
    r = self._trigger_event(data[0], namespace, *data[1:])
  File "c:\users\test\env\lib\site-packages\socketio\client.py", line 554, in _trigger_event
    return self.namespace_handlers[namespace].trigger_event(
  File "c:\users\test\env\lib\site-packages\socketio\namespace.py", line 18, in trigger_event
    return getattr(self, handler_name)(*args)
  File "c:\users\test\env\lib\site-packages\fiftyone\core\client.py", line 72, in on_update
    self.data = self.data_cls.from_dict(data)
  File "c:\users\test\env\lib\site-packages\fiftyone\core\state.py", line 82, in from_dict
    dataset = fod.load_dataset(dataset.get("name"))
  File "c:\users\test\env\lib\site-packages\fiftyone\core\dataset.py", line 92, in load_dataset
    return Dataset(name, _create=False)
  File "c:\users\test\env\lib\site-packages\fiftyone\core\singleton.py", line 51, in __call__
    instance.__init__(name, _create=_create, *args, **kwargs)
  File "c:\users\test\env\lib\site-packages\fiftyone\core\dataset.py", line 174, in __init__
    self._meta, self._sample_doc_cls = _load_dataset(name)
  File "c:\users\test\env\lib\site-packages\fiftyone\core\dataset.py", line 1618, in _load_dataset
    raise DoesNotExistError("Dataset '%s' not found" % name)
fiftyone.core.dataset.DoesNotExistError: Dataset 'cifar10' not found
```

mongodb appears to be spun up locally, which is likely part of the issue (probably the server too)

**Comment by benjaminpkane** [comment]
`fiftyone app connect` now fails due to the migration framework attempting to load the dataset.
