### ISSUE TITLE
[BUG] Dataset creation is not multiprocessing-safe

### ISSUE THREAD

**Issue by elsampsa** [voxel51/fiftyone#2096]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.6
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: 0.16.6
-   **Python version**: 3.8

### Commands to reproduce

- Use separate mongodb server (not the default local one)
- Launch two python scripts _simultaneously_
- Both scripts clone the same dataset

### Describe the problem

When cloning a dataset, fiftyone seems to create mongodb collections with names based on timestamps.  If the same dataset is cloned _almost_ simultaneously, there will be a conflict in the collection name

Come on, when using timestamps, you must always include time information up to microseconds..! :)  Or otherwise use uuids.

I am giving an explicit name to the dataset when cloning (based in uuid):
```
dataset=dataset.clone(some_name)
dataset.persistent=True
```
but even so, fiftyone uses at some internal stage (which crashes) the name ``samples.2022.09.19.10.46.48`` for mongodb (see the logs below).

### Code to reproduce issue

n/a

### Other info / logs

Logs from two processes launched near-simultaneously (by a batch job system):

Process 1:
```
Traceback (most recent call last):
  File "/mnt/wekamount/RI-Users/sampsa.riikonen/venv3/lib/python3.8/site-packages/fiftyone/core/odm/document.py", line 590, in _save
    _id = collection.insert_one(doc).inserted_id
  File "/mnt/wekamount/RI-Users/sampsa.riikonen/venv3/lib/python3.8/site-packages/pymongo/collection.py", line 705, in insert_one
    self._insert(document,
  File "/mnt/wekamount/RI-Users/sampsa.riikonen/venv3/lib/python3.8/site-packages/pymongo/collection.py", line 620, in _insert
    return self._insert_one(
  File "/mnt/wekamount/RI-Users/sampsa.riikonen/venv3/lib/python3.8/site-packages/pymongo/collection.py", line 609, in _insert_one
    self.__database.client._retryable_write(
  File "/mnt/wekamount/RI-Users/sampsa.riikonen/venv3/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1552, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "/mnt/wekamount/RI-Users/sampsa.riikonen/venv3/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1438, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
  File "/mnt/wekamount/RI-Users/sampsa.riikonen/venv3/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1470, in _retry_internal
    return func(session, sock_info, retryable)
  File "/mnt/wekamount/RI-Users/sampsa.riikonen/venv3/lib/python3.8/site-packages/pymongo/collection.py", line 607, in _insert_command
    _check_write_command_response(result)
  File "/mnt/wekamount/RI-Users/sampsa.riikonen/venv3/lib/python3.8/site-packages/pymongo/helpers.py", line 241, in _check_write_command_response
    _raise_last_write_error(write_errors)
  File "/mnt/wekamount/RI-Users/sampsa.riikonen/venv3/lib/python3.8/site-packages/pymongo/helpers.py", line 210, in _raise_last_write_error
    raise DuplicateKeyError(error.get("errmsg"), 11000, error)
pymongo.errors.DuplicateKeyError: E11000 duplicate key error collection: fiftyone.datasets index: sample_collection_name_1 dup key: { sample_collection_name: "samples.2022.09.19.10.46.48" }, full error: {'index': 0, 'code': 11000, 'keyPattern': {'sample_collection_name': 1}, 'keyValue': {'sample_collection_name': 'samples.2022.09.19.10.46.48'}, 'errmsg': 'E11000 duplicate key error collection: fiftyone.datasets index: sample_collection_name_1 dup key: { sample_collection_name: "samples.2022.09.19.10.46.48" }'}
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/mnt/wekamount/RI-Users/sampsa.riikonen/venv3/bin/compressai-vision", line 8, in <module>
    sys.exit(main())
  File "/mnt/wekamount/RI-Users/sampsa.riikonen/CompressAI-Vision/compressai_vision/cli/main.py", line 317, in main
    func(parsed)
  File "/mnt/wekamount/RI-Users/sampsa.riikonen/CompressAI-Vision/compressai_vision/cli/detectron2_eval.py", line 251, in main
    dataset=dataset.clone(tmp_name)
  File "/mnt/wekamount/RI-Users/sampsa.riikonen/venv3/lib/python3.8/site-packages/fiftyone/core/dataset.py", line 2292, in clone
    return self._clone(name=name, persistent=persistent)
  File "/mnt/wekamount/RI-Users/sampsa.riikonen/venv3/lib/python3.8/site-packages/fiftyone/core/dataset.py", line 2303, in _clone
    return _clone_dataset_or_view(sample_collection, name, persistent)
  File "/mnt/wekamount/RI-Users/sampsa.riikonen/venv3/lib/python3.8/site-packages/fiftyone/core/dataset.py", line 5066, in _clone_dataset_or_view
    dataset_doc.save()
  File "/mnt/wekamount/RI-Users/sampsa.riikonen/venv3/lib/python3.8/site-packages/fiftyone/core/odm/document.py", line 549, in save
    self._save(deferred=False, validate=validate, clean=clean, **kwargs)
  File "/mnt/wekamount/RI-Users/sampsa.riikonen/venv3/lib/python3.8/site-packages/fiftyone/core/odm/document.py", line 614, in _save
    raise mongoengine.NotUniqueError(message % e)
mongoengine.errors.NotUniqueError: Tried to save duplicate unique keys (E11000 duplicate key error collection: fiftyone.datasets index: sample_collection_name_1 dup key: { sample_collection_name: "samples.2022.09.19.10.46.48" }, full error: {'index': 0, 'code': 11000, 'keyPattern': {'sample_collection_name': 1}, 'keyValue': {'sample_collection_name': 'samples.2022.09.19.10.46.48'}, 'errmsg': 'E11000 duplicate key error collection: fiftyone.datasets index: sample_collection_name_1 dup key: { sample_collection_name: "samples.2022.09.19.10.46.48" }'})
srun: error: kopspgpu09p: task 0: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=165398.0
```

Process 2: (almost identical)
```
...
...
File "/mnt/wekamount/RI-Users/sampsa.riikonen/venv3/lib/python3.8/site-packages/fiftyone/core/odm/document.py", line 549, in save
    self._save(deferred=False, validate=validate, clean=clean, **kwargs)
  File "/mnt/wekamount/RI-Users/sampsa.riikonen/venv3/lib/python3.8/site-packages/fiftyone/core/odm/document.py", line 614, in _save
    raise mongoengine.NotUniqueError(message % e)
mongoengine.errors.NotUniqueError: Tried to save duplicate unique keys (E11000 duplicate key error collection: fiftyone.datasets index: sample_collection_name_1 dup key: { sample_collection_name: "samples.2022.09.19.10.46.48" }, full error: {'index': 0, 'code': 11000, 'keyPattern': {'sample_collection_name': 1}, 'keyValue': {'sample_collection_name': 'samples.2022.09.19.10.46.48'}, 'errmsg': 'E11000 duplicate key error collection: fiftyone.datasets index: sample_collection_name_1 dup key: { sample_collection_name: "samples.2022.09.19.10.46.48" }'})
srun: error: kopspgpu09p: task 0: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=165399.0
```

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [X] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [X] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

**Comment by elsampsa** [comment]
I think the problem is here:
https://github.com/voxel51/fiftyone/blob/develop/fiftyone/core/dataset.py#L5631

Why this?
```
name = create_name(now.strftime("%Y.%m.%d.%H.%M.%S"))
    if name in conn.list_collection_names():
        name = create_name(now.strftime("%Y.%m.%d.%H.%M.%S.%f"))
```
instead of just this?
```
name = create_name(now.strftime("%Y.%m.%d.%H.%M.%S.%f"))
```
I'm gonna monkey-patch this for my own use.

Maybe you guys can decide if my proposed fix is ok & then changes those lines in the code?

**Comment by brimoor** [comment]
@elsampsa good catch, fixed in https://github.com/voxel51/fiftyone/pull/2097!
