### ISSUE TITLE
[BUG] Error trying to install custom plugin

### ISSUE THREAD

**Issue by erikadicesare** [voxel51/fiftyone#2147]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 18.04
-   **FiftyOne installed from (pip or source)**: source
-   **FiftyOne version (run `fiftyone --version`)**: v0.17.2
-   **Python version**: 3.9.12

### Commands to reproduce

I tried to follow this guide: https://github.com/voxel51/fiftyone-plugins/tree/main/hello-world

### Describe the problem

I follow the following steps:
```
npm install
cd $MY_FIFTYONE_SRC_DIR/app/packages;
cd aggregations;
npm link;
cd ../plugins;
npm link;
cd ../state;
npm link;
cd $HELLO_WORLD_DIR;
npm link @fiftyone/aggregations;
npm link @fiftyone/plugins;
npm link @fiftyone/state;
```

Then, i run:
``` 
yarn build
```

and I got this error:
```
[vite]: Rollup failed to resolve import "@fiftyone/plugins" from "src/HelloWorldPlugin.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
build.rollupOptions.external
error during build:
Error: [vite]: Rollup failed to resolve import "@fiftyone/plugins" from "src/HelloWorldPlugin.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
build.rollupOptions.external
    at onRollupWarning (/home/musausr/fiftyone/plugins/hello-world/node_modules/vite/dist/node/chunks/dep-689425f3.js:41797:19)
    at onwarn (/home/musausr/fiftyone/plugins/hello-world/node_modules/vite/dist/node/chunks/dep-689425f3.js:41613:13)
    at Object.onwarn (/home/musausr/fiftyone/plugins/hello-world/node_modules/vite/node_modules/rollup/dist/shared/rollup.js:23216:13)
    at ModuleLoader.handleResolveId (/home/musausr/fiftyone/plugins/hello-world/node_modules/vite/node_modules/rollup/dist/shared/rollup.js:22466:26)
    at /home/musausr/fiftyone/plugins/hello-world/node_modules/vite/node_modules/rollup/dist/shared/rollup.js:22427:26
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

So, I thought that what was going wrong were the links created with npm. In the files "HelloWorld.tsx" and "HelloWorldPlugins.tsx" I tried to substitute those lines:
```
import * as fop from '@fiftyone/plugins';
import * as fop from '@fiftyone/aggregations';
import * as fop from '@fiftyone/state';
```
with:
```
import * as fop from './../../../fiftyone/app/packages/plugins';
import * as fos from './../../../fiftyone/app/packages/aggregations';
import * as fop from './../../../fiftyone/app/packages/state';
```
Now the 
``` 
yarn build
```
command is successful, but I ran into another error. Starting the server with the following commands:
``` 
cd $FIFTYONE
python fiftyone/server/main.py
```
I got the following problem in the web console:
```
Uncaught Invariant Violation: graphql: Unexpected invocation at runtime. Either the Babel transform was not set up, or it failed to identify this call site. Make sure it is being used verbatim as `graphql`. Note also that there cannot be a space between graphql and the backtick that follows.
    at b1 (http://localhost:5151/plugins/hello-world/dist/index.umd.js:28:673)
    at Object.pW [as graphql] (http://localhost:5151/plugins/hello-world/dist/index.umd.js:29:4255)
    at http://localhost:5151/plugins/hello-world/dist/index.umd.js:58:79798
    at http://localhost:5151/plugins/hello-world/dist/index.umd.js:1:64
    at http://localhost:5151/plugins/hello-world/dist/index.umd.js:1:70
```

**Comment by ritch** [comment]
```
import * as fop from './../../../fiftyone/app/packages/plugins';
import * as fos from './../../../fiftyone/app/packages/aggregations';
import * as fop from './../../../fiftyone/app/packages/state';
```

This is not supported. The plugin needs to refer to the package itself so that it can be externalized. This part of the config is also required: https://github.com/voxel51/fiftyone-plugins/blob/main/hello-world/vite.config.ts#L17

Try running a `yarn install` in your plugin dir after creating the links.

**Comment by erikadicesare** [comment]
The config part is ok.

I tried running ```yarn install``` after creating the ```npm links``` and it was successful. I started the server and i got this error in the web console:
GET http://127.0.0.1:5151/plugins/hello-world/dist/index.umd.js net::ERR_ABORTED 500         index.1e70dfa6.js:704 

I also tried to run ```yarn build``` and I got again this error:
[vite]: Rollup failed to resolve import "@fiftyone/plugins" from "src/HelloWorldPlugin.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "@fiftyone/plugins" from "src/HelloWorldPlugin.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (/home/musausr/fiftyone/plugins/hello-world/node_modules/vite/dist/node/chunks/dep-689425f3.js:41797:19)
    at onwarn (/home/musausr/fiftyone/plugins/hello-world/node_modules/vite/dist/node/chunks/dep-689425f3.js:41613:13)
    at Object.onwarn (/home/musausr/fiftyone/plugins/hello-world/node_modules/rollup/dist/shared/rollup.js:23216:13)
    at ModuleLoader.handleResolveId (/home/musausr/fiftyone/plugins/hello-world/node_modules/rollup/dist/shared/rollup.js:22466:26)
    at /home/musausr/fiftyone/plugins/hello-world/node_modules/rollup/dist/shared/rollup.js:22427:26
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error


This is the terminal of the server:
Traceback (most recent call last):
  File "/home/musausr/anaconda3/lib/python3.9/site-packages/hypercorn/asyncio/task_group.py", line 23, in _handle
    await app(scope, receive, send, sync_spawn, call_soon)
  File "/home/musausr/anaconda3/lib/python3.9/site-packages/hypercorn/app_wrappers.py", line 33, in __call__
    await self.app(scope, receive, send)
  File "/home/musausr/anaconda3/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/musausr/anaconda3/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/musausr/anaconda3/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/musausr/anaconda3/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/musausr/anaconda3/lib/python3.9/site-packages/starlette/middleware/base.py", line 57, in __call__
    task_group.cancel_scope.cancel()
  File "/home/musausr/anaconda3/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/home/musausr/anaconda3/lib/python3.9/site-packages/starlette/middleware/base.py", line 30, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/home/musausr/anaconda3/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/musausr/anaconda3/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/musausr/anaconda3/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/musausr/anaconda3/lib/python3.9/site-packages/starlette/routing.py", line 408, in handle
    await self.app(scope, receive, send)
  File "/home/musausr/anaconda3/lib/python3.9/site-packages/starlette/staticfiles.py", line 98, in __call__
    await response(scope, receive, send)
  File "/home/musausr/anaconda3/lib/python3.9/site-packages/starlette/responses.py", line 285, in __call__
    raise RuntimeError(f"File at path {self.path} does not exist.")
RuntimeError: File at path  does not exist.

**Comment by erikadicesare** [comment]
> ```
> import * as fop from './../../../fiftyone/app/packages/plugins';
> import * as fos from './../../../fiftyone/app/packages/aggregations';
> import * as fop from './../../../fiftyone/app/packages/state';
> ```
> 
> This is not supported. The plugin needs to refer to the package itself so that it can be externalized. This part of the config is also required: https://github.com/voxel51/fiftyone-plugins/blob/main/hello-world/vite.config.ts#L17
> 
> Try running a `yarn install` in your plugin dir after creating the `npm links`.

The config part is ok.

I tried running ```yarn install``` after creating the ```npm links``` and it was successful. I started the server and i got this error in the web console:
GET http://127.0.0.1:5151/plugins/hello-world/dist/index.umd.js net::ERR_ABORTED 500         index.1e70dfa6.js:704 

I also tried to run ```yarn build``` and I got again this error:
[vite]: Rollup failed to resolve import "@fiftyone/plugins" from "src/HelloWorldPlugin.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "@fiftyone/plugins" from "src/HelloWorldPlugin.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (/home/musausr/fiftyone/plugins/hello-world/node_modules/vite/dist/node/chunks/dep-689425f3.js:41797:19)
    at onwarn (/home/musausr/fiftyone/plugins/hello-world/node_modules/vite/dist/node/chunks/dep-689425f3.js:41613:13)
    at Object.onwarn (/home/musausr/fiftyone/plugins/hello-world/node_modules/rollup/dist/shared/rollup.js:23216:13)
    at ModuleLoader.handleResolveId (/home/musausr/fiftyone/plugins/hello-world/node_modules/rollup/dist/shared/rollup.js:22466:26)
    at /home/musausr/fiftyone/plugins/hello-world/node_modules/rollup/dist/shared/rollup.js:22427:26
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error


This is the terminal of the server:
[2022-10-11 09:25:20 +0200] [3185] [ERROR] Error in ASGI Framework
Traceback (most recent call last):
  File "/home/musausr/anaconda3/lib/python3.9/site-packages/hypercorn/asyncio/task_group.py", line 23, in _handle
    await app(scope, receive, send, sync_spawn, call_soon)
  File "/home/musausr/anaconda3/lib/python3.9/site-packages/hypercorn/app_wrappers.py", line 33, in __call__
    await self.app(scope, receive, send)
  File "/home/musausr/anaconda3/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/musausr/anaconda3/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/musausr/anaconda3/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/musausr/anaconda3/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/musausr/anaconda3/lib/python3.9/site-packages/starlette/middleware/base.py", line 57, in __call__
    task_group.cancel_scope.cancel()
  File "/home/musausr/anaconda3/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/home/musausr/anaconda3/lib/python3.9/site-packages/starlette/middleware/base.py", line 30, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/home/musausr/anaconda3/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/musausr/anaconda3/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/musausr/anaconda3/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/musausr/anaconda3/lib/python3.9/site-packages/starlette/routing.py", line 408, in handle
    await self.app(scope, receive, send)
  File "/home/musausr/anaconda3/lib/python3.9/site-packages/starlette/staticfiles.py", line 98, in __call__
    await response(scope, receive, send)
  File "/home/musausr/anaconda3/lib/python3.9/site-packages/starlette/responses.py", line 285, in __call__
    raise RuntimeError(f"File at path {self.path} does not exist.")
RuntimeError: File at path  does not exist.
