### ISSUE TITLE
[BUG] Refreshing App in Jupyter notebook

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/fiftyone#2153]
After launching the app in the cell of a jupyter notebook, I get the following error when clicking the Voxel cube to refresh the App.

```
TypeError: Cannot destructure property 'colorscale' of '(intermediate value)(intermediate value)(intermediate value)' as it is null.
at P (http://localhost:5151/assets/index.44476aa2.js:1:332)
at w (http://localhost:5151/assets/index.44476aa2.js:1:550)
at MU (http://localhost:5151/assets/index.8160f4d9.js:58:19145)
at $O (http://localhost:5151/assets/index.8160f4d9.js:60:12552)
at vae (http://localhost:5151/assets/index.8160f4d9.js:60:45611)
at pae (http://localhost:5151/assets/index.8160f4d9.js:60:40384)
at tLe (http://localhost:5151/assets/index.8160f4d9.js:60:40307)
at SE (http://localhost:5151/assets/index.8160f4d9.js:60:40157)
at sW (http://localhost:5151/assets/index.8160f4d9.js:60:36485)
at K5 (http://localhost:5151/assets/index.8160f4d9.js:60:37299)
```

**Comment by brimoor** [comment]
@ehofesmann is this still an issue in `fiftyone==0.18`?
