### ISSUE TITLE
[FR] Verify latitude and longitude values at creation time

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/fiftyone#2171]
Invalid lat and long coordinates in a `GeoLocation` field will result in the App throwing an error: 
```
Error: Invalid LngLat latitude value: must be between -90 and 90
    at new de (http://localhost:5151/assets/index.f01320f2.js:711:66777)
    at de.convert (http://localhost:5151/assets/index.f01320f2.js:711:67409)
    at Q.extend (http://localhost:5151/assets/index.f01320f2.js:711:65535)
    at http://localhost:5151/assets/index.f01320f2.js:1790:65057
    at Array.reduce (<anonymous>)
    at bye (http://localhost:5151/assets/index.f01320f2.js:1790:65016)
    at http://localhost:5151/assets/index.f01320f2.js:1790:65695
    at Object.Gae [as useMemo] (http://localhost:5151/assets/index.f01320f2.js:34:23601)
    at Eo.useMemo (http://localhost:5151/assets/index.f01320f2.js:9:6259)
    at Tst (http://localhost:5151/assets/index.f01320f2.js:1790:65683)
```

It would be best to catch this error at data ingestion time.

**Comment by brimoor** [comment]
This validation logic would be implemented here and below:
https://github.com/voxel51/fiftyone/blob/bf03dde6e4a0becabbce9e8fbe6fe82aa0a0f9be/fiftyone/core/fields.py#L355

**Comment by brimoor** [comment]
Rather than raising an error at data ingest time, I would prefer that we update the App rendering logic to silently ignore lat/lon points that lie outside the allowed range.

Sometimes the user has a need to specifically store out of range values, eg when ingesting raw data for cleaning.

We have precedent for this, eg like how we allow bounding box coordinates that exceed `[0, 1]`.
