### ISSUE TITLE
[BUG] State consistency issues when loading/unloading views that change media type/schema via session object

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#2290]
Looks like there are some state issues that are uncovered when loading or unloading views that make significant changes to the media type/schema of the current collection via the `session` object:

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart-groups")
session = fo.launch_app(dataset)

# ERROR 1
session.view = dataset.select_group_slices(media_type="image").to_patches("ground_truth")

# Refresh browser, now view loads

# ERROR 2
session.view = None
```

### ERROR 1

```
DatasetView has no groups
File "/Users/Brian/dev/env/fo/lib/python3.9/site-packages/graphql/execution/execute.py", line 1036, in await_result
return build_response(await result, errors) # type: ignore
File "/Users/Brian/dev/env/fo/lib/python3.9/site-packages/graphql/execution/execute.py", line 451, in get_results
await gather(*(results[field] for field in awaitable_fields)),
File "/Users/Brian/dev/env/fo/lib/python3.9/site-packages/graphql/execution/execute.py", line 535, in await_result
self.handle_field_error(error, return_type)
File "/Users/Brian/dev/env/fo/lib/python3.9/site-packages/graphql/execution/execute.py", line 569, in handle_field_error
raise error
File "/Users/Brian/dev/env/fo/lib/python3.9/site-packages/graphql/execution/execute.py", line 528, in await_result
return_type, field_nodes, info, path, await result
File "/Users/Brian/dev/env/fo/lib/python3.9/site-packages/strawberry/schema/schema_converter.py", line 513, in _async_resolver
return await await_maybe(_get_result(_source, strawberry_info, **kwargs))
File "/Users/Brian/dev/env/fo/lib/python3.9/site-packages/strawberry/utils/await_maybe.py", line 12, in await_maybe
return await value
File "/Users/Brian/dev/fiftyone/fiftyone/server/aggregations.py", line 120, in aggregate_resolver
view = fosv.get_view(
File "/Users/Brian/dev/fiftyone/fiftyone/server/view.py", line 65, in get_view
view.group_slice = sample_filter.group.slice
File "/Users/Brian/dev/fiftyone/fiftyone/core/view.py", line 201, in group_slice
raise ValueError("DatasetView has no groups")
```

### ERROR 2

```
Field 'sample_id' does not exist on collection 'quickstart-groups-view'
File "/Users/Brian/dev/env/fo/lib/python3.9/site-packages/graphql/execution/execute.py", line 1036, in await_result
return build_response(await result, errors) # type: ignore
File "/Users/Brian/dev/env/fo/lib/python3.9/site-packages/graphql/execution/execute.py", line 451, in get_results
await gather(*(results[field] for field in awaitable_fields)),
File "/Users/Brian/dev/env/fo/lib/python3.9/site-packages/graphql/execution/execute.py", line 535, in await_result
self.handle_field_error(error, return_type)
File "/Users/Brian/dev/env/fo/lib/python3.9/site-packages/graphql/execution/execute.py", line 569, in handle_field_error
raise error
File "/Users/Brian/dev/env/fo/lib/python3.9/site-packages/graphql/execution/execute.py", line 528, in await_result
return_type, field_nodes, info, path, await result
File "/Users/Brian/dev/env/fo/lib/python3.9/site-packages/strawberry/schema/schema_converter.py", line 513, in _async_resolver
return await await_maybe(_get_result(_source, strawberry_info, **kwargs))
File "/Users/Brian/dev/env/fo/lib/python3.9/site-packages/strawberry/utils/await_maybe.py", line 12, in await_maybe
return await value
File "/Users/Brian/dev/fiftyone/fiftyone/server/aggregations.py", line 157, in aggregate_resolver
result = await view._async_aggregate(flattened)
File "/Users/Brian/dev/fiftyone/fiftyone/core/collections.py", line 8165, in _async_aggregate
compiled_facet_aggs, facet_pipelines = self._build_facets(
File "/Users/Brian/dev/fiftyone/fiftyone/core/collections.py", line 8284, in _build_facets
pipeline=aggregation.to_mongo(self),
File "/Users/Brian/dev/fiftyone/fiftyone/core/aggregations.py", line 1113, in to_mongo
path, pipeline, _, _, _ = _parse_field_and_expr(
File "/Users/Brian/dev/fiftyone/fiftyone/core/aggregations.py", line 2559, in _parse_field_and_expr
) = sample_collection._parse_field_name(
File "/Users/Brian/dev/fiftyone/fiftyone/core/collections.py", line 8526, in _parse_field_name
return _parse_field_name(
File "/Users/Brian/dev/fiftyone/fiftyone/core/collections.py", line 9331, in _parse_field_name
raise ValueError(
```

**Comment by brimoor** [comment]
I just ran this on `develop` and got this error when trying to load the patches view:

```
TypeError: Cannot read properties of null (reading 'data')
at http://localhost:5151/assets/index.4a1cc8b6.js:548:55749
at Array.forEach (<anonymous>)
at e._handleErrorResponse (http://localhost:5151/assets/index.4a1cc8b6.js:548:55722)
at e._handleNext (http://localhost:5151/assets/index.4a1cc8b6.js:549:860)
at http://localhost:5151/assets/index.4a1cc8b6.js:548:55512
at Awt (http://localhost:5151/assets/index.4a1cc8b6.js:548:37671)
at http://localhost:5151/assets/index.4a1cc8b6.js:548:55496
at e._schedule (http://localhost:5151/assets/index.4a1cc8b6.js:548:55037)
at e._next (http://localhost:5151/assets/index.4a1cc8b6.js:548:55469)
at Object.next (http://localhost:5151/assets/index.4a1cc8b6.js:548:53220)
```

**Comment by brimoor** [comment]
On `develop`, I am still occasionally seeing `Cannot read properties of null` when loading either of these views:

```py
session.view = dataset.select_group_slices(media_type="image")
session.view = dataset.select_group_slices(media_type="image").to_patches("ground_truth")
```

**Comment by brimoor** [comment]
Now I get:

```
  File "/Users/Brian/dev/env/fo/lib/python3.9/site-packages/graphql/execution/execute.py", line 1036, in await_result
    return build_response(await result, errors)  # type: ignore

  File "/Users/Brian/dev/env/fo/lib/python3.9/site-packages/graphql/execution/execute.py", line 451, in get_results
    await gather(*(results[field] for field in awaitable_fields)),

  File "/Users/Brian/dev/env/fo/lib/python3.9/site-packages/graphql/execution/execute.py", line 535, in await_result
    self.handle_field_error(error, return_type)

  File "/Users/Brian/dev/env/fo/lib/python3.9/site-packages/graphql/execution/execute.py", line 569, in handle_field_error
    raise error

  File "/Users/Brian/dev/env/fo/lib/python3.9/site-packages/graphql/execution/execute.py", line 528, in await_result
    return_type, field_nodes, info, path, await result

  File "/Users/Brian/dev/env/fo/lib/python3.9/site-packages/strawberry/schema/schema_converter.py", line 513, in _async_resolver
    return await await_maybe(_get_result(_source, strawberry_info, **kwargs))

  File "/Users/Brian/dev/env/fo/lib/python3.9/site-packages/strawberry/utils/await_maybe.py", line 12, in await_maybe
    return await value

  File "/Users/Brian/dev/fiftyone/fiftyone/server/aggregations.py", line 125, in aggregate_resolver
    view = fosv.get_view(

  File "/Users/Brian/dev/fiftyone/fiftyone/server/view.py", line 119, in get_view
    view.group_slice = sample_filter.group.slice

  File "/Users/Brian/dev/fiftyone/fiftyone/core/view.py", line 208, in group_slice
    raise ValueError("DatasetView has no groups")
```

**Comment by brimoor** [comment]
After page refresh, the view loads correctly. But if I then clear my view bar in UI, I see this:

<img width="1144" alt="Screen Shot 2023-02-09 at 9 11 40 AM" src="https://user-images.githubusercontent.com/25985824/217836274-4624dc5b-7eea-40c8-879d-71b01a36045c.png">
