### ISSUE TITLE
no version information available

### ISSUE THREAD

**Issue by applepieiris** [voxel51/fiftyone#2323]
os : centos 7
python: 3.8

i install the fiftyone using `pip install fiftyne` in conda environment. The env is created for testing fiftyone so i only install the fiftyone. the installation is ok 👍 but when i type `fiftyone` in terminal, it shows :
`(fif) fiftyone
Subprocess ['/root/anaconda3/envs/fif/lib/python3.8/site-packages/fiftyone/db/bin/mongod', '--dbpath', '/root/.fiftyone/var/lib/mongo', '--logpath', '/root/.fiftyone/var/lib/mongo/log/mongo.log', '--port', '0', '--nounixsocket'] exited with error 1:
/root/anaconda3/envs/fif/lib/python3.8/site-packages/fiftyone/db/bin/mongod: /usr/lib64/libc.so.6: version `GLIBC_2.18' not found (required by /root/anaconda3/envs/fif/lib/python3.8/site-packages/fiftyone/db/bin/mongod)
/root/anaconda3/envs/fif/lib/python3.8/site-packages/fiftyone/db/bin/mongod: /usr/lib64/libc.so.6: version `GLIBC_2.25' not found (required by /root/anaconda3/envs/fif/lib/python3.8/site-packages/fiftyone/db/bin/mongod)
/root/anaconda3/envs/fif/lib/python3.8/site-packages/fiftyone/db/bin/mongod: /root/anaconda3/envs/autotag/lib/libcurl.so.4: no version information available (required by /root/anaconda3/envs/fif/lib/python3.8/site-packages/fiftyone/db/bin/mongod)
^CTraceback (most recent call last):
  File "/root/anaconda3/envs/fif/bin/fiftyone", line 5, in <module>
    from fiftyone.core.cli import main
  File "/root/anaconda3/envs/fif/lib/python3.8/site-packages/fiftyone/__init__.py", line 25, in <module>
    from fiftyone.__public__ import *
  File "/root/anaconda3/envs/fif/lib/python3.8/site-packages/fiftyone/__public__.py", line 15, in <module>
    _foo.establish_db_conn(config)
  File "/root/anaconda3/envs/fif/lib/python3.8/site-packages/fiftyone/core/odm/database.py", line 156, in establish_db_conn
    port = _db_service.port
  File "/root/anaconda3/envs/fif/lib/python3.8/site-packages/fiftyone/core/service.py", line 276, in port
    return self._wait_for_child_port()
  File "/root/anaconda3/envs/fif/lib/python3.8/site-packages/fiftyone/core/service.py", line 170, in _wait_for_child_port
    return find_port()
  File "/root/anaconda3/envs/fif/lib/python3.8/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/root/anaconda3/envs/fif/lib/python3.8/site-packages/retrying.py", line 220, in call
    time.sleep(sleep / 1000.0)
KeyboardInterrupt

(fif) /root/anaconda3/envs/fif/lib/python3.8/site-packages/fiftyone/db/bin/mongod --version
/root/anaconda3/envs/fif/lib/python3.8/site-packages/fiftyone/db/bin/mongod: /usr/lib64/libc.so.6: version `GLIBC_2.18' not found (required by /root/anaconda3/envs/fif/lib/python3.8/site-packages/fiftyone/db/bin/mongod)
/root/anaconda3/envs/fif/lib/python3.8/site-packages/fiftyone/db/bin/mongod: /usr/lib64/libc.so.6: version `GLIBC_2.25' not found (required by /root/anaconda3/envs/fif/lib/python3.8/site-packages/fiftyone/db/bin/mongod)
/root/anaconda3/envs/fif/lib/python3.8/site-packages/fiftyone/db/bin/mongod: /root/anaconda3/envs/autotag/lib/libcurl.so.4: no version information available (required by /root/anaconda3/envs/fif/lib/python3.8/site-packages/fiftyone/db/bin/mongod)`

I looked up the dir `root/anaconda3/envs/autotag/lib`, can find the lib file :
`libcurl.so.4.8.0`
i think it should know the curl version. Thank you for your effort

**Comment by applepieiris** [comment]
(fif) ls -l /root/anaconda3/envs/autotag/lib/libcurl.so.4
lrwxrwxrwx 1 root root 16 11月 18 10:14 /root/anaconda3/envs/autotag/lib/libcurl.so.4 -> libcurl.so.4.8.0

**Comment by brimoor** [comment]
We have a [troubleshooting section](https://voxel51.com/docs/fiftyone/getting_started/troubleshooting.html#troubleshooting-linux-imports) of the docs for errors like this. I don't have a centos environment handy to test on, but there's a long tail of small system-related things that might be wrong. The question at this point is why the MongoDB binary at the indicated path is not happy.

If you're still facing issues, a fallback solution as recommended in the link above is to [configure FiftyOne](https://voxel51.com/docs/fiftyone/user_guide/config.html#configuring-mongodb-connection) to use a MongoDB instance that you have installed yourself.

**Comment by doem97** [comment]
> os : centos 7 python: 3.8
> 
> i install the fiftyone using `pip install fiftyne` in conda environment. The env is created for testing fiftyone so i only install the fiftyone. the installation is ok 👍 but when i type `fiftyone` in terminal, it shows : `(fif) fiftyone Subprocess ['/root/anaconda3/envs/fif/lib/python3.8/site-packages/fiftyone/db/bin/mongod', '--dbpath', '/root/.fiftyone/var/lib/mongo', '--logpath', '/root/.fiftyone/var/lib/mongo/log/mongo.log', '--port', '0', '--nounixsocket'] exited with error 1:
> 
> /root/anaconda3/envs/fif/lib/python3.8/site-packages/fiftyone/db/bin/mongod: /usr/lib64/libc.so.6: version GLIBC_2.18 not found (required by /root/anaconda3/envs/fif/lib/python3.8/site-packages/fiftyone/db/bin/mongod)
> 
> /root/anaconda3/envs/fif/lib/python3.8/site-packages/fiftyone/db/bin/mongod: /usr/lib64/libc.so.6: version GLIBC_2.25 not found (required by /root/anaconda3/envs/fif/lib/python3.8/site-packages/fiftyone/db/bin/mongod)
> 
> /root/anaconda3/envs/fif/lib/python3.8/site-packages/fiftyone/db/bin/mongod: /root/anaconda3/envs/autotag/lib/libcurl.so.4: no version information available (required by /root/anaconda3/envs/fif/lib/python3.8/site-packages/fiftyone/db/bin/mongod)`
> 
> I looked up the dir `root/anaconda3/envs/autotag/lib`, can find the lib file : `libcurl.so.4.8.0` i think it should know the curl version. Thank you for your effort

Hi, we got any update on this? met the same problem. Thanks.

**Comment by sjtu-hxj** [comment]
same again
