### ISSUE TITLE
[INSTALL] Cannot use motor>3 on Ubuntu?

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#2356]
A user reported the following error when trying to install `fiftyone==0.18` on `ubuntu 20.04` + `python 3.8.10`:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.8/site-packages/fiftyone/__init__.py", line 25, in <module>
    from fiftyone.__public__ import *
  File "/home/user/.local/lib/python3.8/site-packages/fiftyone/__public__.py", line 9, in <module>
    import fiftyone.core.odm as _foo
  File "/home/user/.local/lib/python3.8/site-packages/fiftyone/core/odm/__init__.py", line 10, in <module>
    from .database import (
  File "/home/user/.local/lib/python3.8/site-packages/fiftyone/core/odm/database.py", line 19, in <module>
    import motor.motor_asyncio as mtr
  File "/home/user/.local/lib/python3.8/site-packages/motor/motor_asyncio.py", line 47, in <module>
    AsyncIOMotorDatabase = create_asyncio_class(core.AgnosticDatabase)
  File "/home/user/.local/lib/python3.8/site-packages/motor/motor_asyncio.py", line 38, in create_asyncio_class
    return create_class_with_framework(cls, asyncio_framework, "motor.motor_asyncio")
  File "/home/user/.local/lib/python3.8/site-packages/motor/metaprogramming.py", line 288, in create_class_with_framework
    new_class_attr = attr.create_attribute(new_class, name)
  File "/home/user/.local/lib/python3.8/site-packages/motor/metaprogramming.py", line 226, in create_attribute
    return ReadOnlyProperty.create_attribute(self, cls, attr_name)
  File "/home/user/.local/lib/python3.8/site-packages/motor/metaprogramming.py", line 204, in create_attribute
    doc = getattr(cls.__delegate_class__, attr_name).__doc__
AttributeError: type object 'Database' has no attribute '__bool__'
```

The reported resolution was to force install `motor>=2.3,<3`, which was the requirement prior to `fiftyone==0.18`. 

In `fiftyone==0.18`, we relaxed this requirement to `motor>=2.3`.

**Comment by brimoor** [comment]
Our CI tests are currently installing `motor==3.1.1` on Ubuntu 20.04 and running without issue, so this is strange...
https://github.com/voxel51/fiftyone/actions/runs/3554747473/jobs/5971049863#step:10:256

**Comment by sebimarkgraf** [comment]
A possible hint on why the pymongo version is installed incorrectly, could be the later installation of apache-beam via pip.
They require "pymongo <4.0" which leads to an incompatible version.

**Comment by allenleetc** [comment]
Believe I hit this on Ubuntu 20.04.5 + Python 3.8.10. Similar trace but slightly different:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/al/venv/fo_devel/lib/python3.8/site-packages/fiftyone/__init__.py", line 25, in <module>
    from fiftyone.__public__ import *
  File "/home/al/venv/fo_devel/lib/python3.8/site-packages/fiftyone/__public__.py", line 9, in <module>
    import fiftyone.core.odm as _foo
  File "/home/al/venv/fo_devel/lib/python3.8/site-packages/fiftyone/core/odm/__init__.py", line 10, in <module>
    from .database import (
  File "/home/al/venv/fo_devel/lib/python3.8/site-packages/fiftyone/core/odm/database.py", line 19, in <module>
    import motor.motor_asyncio as mtr
  File "/home/al/venv/fo_devel/lib/python3.8/site-packages/motor/__init__.py", line 35, in <module>
    from .motor_tornado import *  # noqa: F403
  File "/home/al/venv/fo_devel/lib/python3.8/site-packages/motor/motor_tornado.py", line 47, in <module>
    MotorDatabase = create_motor_class(core.AgnosticDatabase)
  File "/home/al/venv/fo_devel/lib/python3.8/site-packages/motor/motor_tornado.py", line 38, in create_motor_class
    return create_class_with_framework(cls, tornado_framework, "motor.motor_tornado")
  File "/home/al/venv/fo_devel/lib/python3.8/site-packages/motor/metaprogramming.py", line 288, in create_class_with_framework
    new_class_attr = attr.create_attribute(new_class, name)
  File "/home/al/venv/fo_devel/lib/python3.8/site-packages/motor/metaprogramming.py", line 226, in create_attribute
    return ReadOnlyProperty.create_attribute(self, cls, attr_name)
  File "/home/al/venv/fo_devel/lib/python3.8/site-packages/motor/metaprogramming.py", line 204, in create_attribute
    doc = getattr(cls.__delegate_class__, attr_name).__doc__
AttributeError: type object 'Database' has no attribute '__bool__'
```

I had also done a pip install of apache-beam. However, simply doing pip install pymongo==4.0 does not fix my environment, instead I get a new trace:

```
>>> import fiftyone as fo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/al/venv/fo_devel/lib/python3.8/site-packages/fiftyone/__init__.py", line 25, in <module>
    from fiftyone.__public__ import *
  File "/home/al/venv/fo_devel/lib/python3.8/site-packages/fiftyone/__public__.py", line 9, in <module>
    import fiftyone.core.odm as _foo
  File "/home/al/venv/fo_devel/lib/python3.8/site-packages/fiftyone/core/odm/__init__.py", line 10, in <module>
    from .database import (
  File "/home/al/venv/fo_devel/lib/python3.8/site-packages/fiftyone/core/odm/database.py", line 19, in <module>
    import motor.motor_asyncio as mtr
  File "/home/al/venv/fo_devel/lib/python3.8/site-packages/motor/__init__.py", line 35, in <module>
    from .motor_tornado import *  # noqa: F403
  File "/home/al/venv/fo_devel/lib/python3.8/site-packages/motor/motor_tornado.py", line 77, in <module>
    MotorClientEncryption = create_motor_class(core.AgnosticClientEncryption)
  File "/home/al/venv/fo_devel/lib/python3.8/site-packages/motor/motor_tornado.py", line 38, in create_motor_class
    return create_class_with_framework(cls, tornado_framework, "motor.motor_tornado")
  File "/home/al/venv/fo_devel/lib/python3.8/site-packages/motor/metaprogramming.py", line 288, in create_class_with_framework
    new_class_attr = attr.create_attribute(new_class, name)
  File "/home/al/venv/fo_devel/lib/python3.8/site-packages/motor/metaprogramming.py", line 152, in create_attribute
    method = getattr(cls.__delegate_class__, name)
AttributeError: type object 'ClientEncryption' has no attribute 'rewrap_many_data_key'
```
