### ISSUE TITLE
[BUG] Error when trying to load patches view in auto=False mode in notebooks

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#2421]
When I try to load a patches view with `auto=False` mode as shown below, I get an error:

https://user-images.githubusercontent.com/25985824/206569100-7f8f21f2-db3f-41f3-903b-8ca3e7a1effc.mov

```py
import fiftyone as fo
import fiftyone.zoo as foz
from fiftyone import ViewField as F

dataset = foz.load_zoo_dataset("quickstart")
```

```py
session = fo.launch_app(dataset, auto=False)
session.show()
```

```py
# works
session.view = dataset.limit(10)
```

```py
# doesn't work
session.view = dataset.to_patches("ground_truth")
```

**Comment by brimoor** [comment]
There might be an outstanding PR that addresses the `TypeError: Cannot read properties of undefined (reading 'embeddedDocType')` error. Not sure, too many outstanding PRs right now.

**Comment by brimoor** [comment]
I can also reproduce this more simply as follows:

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
view = dataset.select_fields()

session = fo.launch_app(view)

# Manually clear the view bar in the App
```

```
TypeError: Cannot read properties of undefined (reading 'embeddedDocType')
at Zdt (http://localhost:5151/assets/index.21635274.js:481:9462)
at $3.renderSelf (http://localhost:5151/assets/index.21635274.js:481:8093)
at $3.render (http://localhost:5151/assets/index.21635274.js:475:500312)
at http://localhost:5151/assets/index.21635274.js:475:500402
at Array.forEach (<anonymous>)
at U3.render (http://localhost:5151/assets/index.21635274.js:475:500349)
at Lft.updater (http://localhost:5151/assets/index.21635274.js:491:63632)
at Lft.updateOptions (http://localhost:5151/assets/index.21635274.js:491:71506)
at http://localhost:5151/assets/index.21635274.js:1665:5025
at http://localhost:5151/assets/index.21635274.js:1609:12503
```

**Comment by brimoor** [comment]
This has been resolved in `develop` and will be fixed as of `fiftyone==0.19`.
