### ISSUE TITLE
[BUG] From Archive assumes that archive extracts into ./archive directory

### ISSUE THREAD

**Issue by sebimarkgraf** [voxel51/fiftyone#2462]
### Instructions
The dataset from archive function expects the archive to extract into a folder with the same name.
That assumption is very often false, as archives can be named any way the user wants.

Example
Create zip directory of a COCO Dataset:
``` bash
zip -r archive.zip dataset
``` 
Then try to load it via Fiftyone
``` python
import fiftyone as fo
dataset = fo.Dataset.from_archive('./archive.zip', dataset_type=fo.types.COCODetectionDataset)
``` 
Expectancy: Load the dataset correctly
Current result is the error:
``` python
>>> dataset = fo.Dataset.from_archive("./archive.zip", type=fo.types.COCODetectionDataset)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/pip-global/fiftyone/core/dataset.py", line 4799, in from_archive
    dataset.add_archive(
  File "/usr/local/pip-global/fiftyone/core/dataset.py", line 3736, in add_archive
    dataset_dir = _extract_archive_if_necessary(archive_path, cleanup)
  File "/usr/local/pip-global/fiftyone/core/dataset.py", line 7619, in _extract_archive_if_necessary
    raise ValueError(
ValueError: Expected to find a directory './archive' after extracting './archive.zip', but it was not found
```

This could be prevented by the extraction commands yielding extracted folder names from the archive.
Additionally, this could then be integrated by especially extracting into a correctly named directory, to keep the current behaviour of reusing already extracted archives.

Moreover, at the same time, one could streamline the extraction process to only use tool instead of splitting between the Python implementations and patool. Since Patool falls back to Python implementations if the tools are not installed, this would make the code better to understand and more readable.

### System information

-   **OS Platform and Distribution** Tested on both Ubuntu 20.04 and Windows 11
-   **Python version** (`python --version`): 3.9 && 3.10
-   **FiftyOne version** (`fiftyone --version`): 0.18.0
-   **FiftyOne installed from** (pip or source): pip

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [X] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [X] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

**Comment by brimoor** [comment]
Hi @sebimarkgraf 👋 thanks for identifying this issue! It would be great if you'd like to contribute a patch to add support for extracting archives whose internal directory name does not match the name of the archive itself.

It sounds like you dug into the implementation of the `extract_archive()` utility being used here:
https://github.com/voxel51/eta/blob/74931c059c205e9e10ebbff756463c1d9a7ed671/eta/core/utils.py#L3505

I suppose that method could be directly improved, but, in my opinion, a good path forward here would just be to update the 
`_extract_archive_if_necessary()` function below to set `dataset_dir` using this order of precedence:
- If a directory matching the archive's name is found, use it
- Else, if a single directory was unpacked, use that
- Else, raise an error 

`https://github.com/voxel51/fiftyone/blob/5b0d7248d40590c4d5637be4cf92612b43dbb5e5/fiftyone/core/dataset.py#L7906

What do you think?

**Comment by sebimarkgraf** [comment]
Hi @brimoor 
Thanks for the suggestion!

While I understand your approach, how would you go into detecting if a single directory was unpacked without touching the other methods?
As far as I know, the extracted methods all do not return the extracted directory / directories yet.

Additionally, this would make the future support of top-level datasets that contain multiple files more complicated.
