### ISSUE TITLE
[BUG] Conversion from OpenImagesV6Dataset to YOLOv5Dataset fails because attributes.csv doesn't exist

### ISSUE THREAD

**Issue by finnjbm** [voxel51/fiftyone#2465]
I downloaded a subsection of the openimages dataset with the following python code:

```py
import fiftyone.zoo as foz

foz.download_zoo_dataset(
    "open-images-v6",
    split="train",
    label_types=["detections", "segmentations"],
    classes=["Balloon"],
    max_samples=100,
)
```

This executed just fine and looks normal upon inspection

I need this in YOLO format, so I tried the following CLI command:

```
fiftyone convert \
    --input-dir ~/fiftyone/open-images-v6/train/ \
    --output-dir ~/yolo-images/train/ \
    --input-type fiftyone.types.dataset_types.OpenImagesV6Dataset \
    --output-type fiftyone.types.YOLOv5Dataset
```

It will then fail out with the following error:

```
Using input format: fiftyone.types.dataset_types.OpenImagesV6Dataset
Using export format: fiftyone.types.dataset_types.YOLOv5Dataset
Loading dataset from '/home/admin/fiftyone/open-images-v6/train/'
Traceback (most recent call last):
  File "/home/admin/.local/share/virtualenvs/Project-Ib9IqvpB/bin/fiftyone", line 8, in <module>
    sys.exit(main())
  File "/home/admin/.local/share/virtualenvs/Project-Ib9IqvpB/lib/python3.10/site-packages/fiftyone/core/cli.py", line 3162, in main
    args.execute(args)
  File "/home/admin/.local/share/virtualenvs/Project-Ib9IqvpB/lib/python3.10/site-packages/fiftyone/core/cli.py", line 3145, in <lambda>
    parser.set_defaults(execute=lambda args: command.execute(parser, args))
  File "/home/admin/.local/share/virtualenvs/Project-Ib9IqvpB/lib/python3.10/site-packages/fiftyone/core/cli.py", line 370, in execute
    foud.convert_dataset(
  File "/home/admin/.local/share/virtualenvs/Project-Ib9IqvpB/lib/python3.10/site-packages/fiftyone/utils/data/converters.py", line 127, in convert_dataset
    dataset.add_importer(dataset_importer)
  File "/home/admin/.local/share/virtualenvs/Project-Ib9IqvpB/lib/python3.10/site-packages/fiftyone/core/dataset.py", line 3986, in add_importer
    return foud.import_samples(
  File "/home/admin/.local/share/virtualenvs/Project-Ib9IqvpB/lib/python3.10/site-packages/fiftyone/utils/data/importers.py", line 122, in import_samples
    with dataset_importer:
  File "/home/admin/.local/share/virtualenvs/Project-Ib9IqvpB/lib/python3.10/site-packages/fiftyone/utils/data/importers.py", line 816, in __enter__
    self.setup()
  File "/home/admin/.local/share/virtualenvs/Project-Ib9IqvpB/lib/python3.10/site-packages/fiftyone/utils/openimages.py", line 260, in setup
    ) = _setup(
  File "/home/admin/.local/share/virtualenvs/Project-Ib9IqvpB/lib/python3.10/site-packages/fiftyone/utils/openimages.py", line 643, in _setup
    attrs_map, _did_download = _get_attrs_map(
  File "/home/admin/.local/share/virtualenvs/Project-Ib9IqvpB/lib/python3.10/site-packages/fiftyone/utils/openimages.py", line 719, in _get_attrs_map
    attrs_csv, did_download = _get_general_metadata_file(
  File "/home/admin/.local/share/virtualenvs/Project-Ib9IqvpB/lib/python3.10/site-packages/fiftyone/utils/openimages.py", line 710, in _get_general_metadata_file
    did_download = _download_file_if_necessary(
  File "/home/admin/.local/share/virtualenvs/Project-Ib9IqvpB/lib/python3.10/site-packages/fiftyone/utils/openimages.py", line 1551, in _download_file_if_necessary
    raise ValueError("File '%s' is not downloaded" % filepath)
ValueError: File '/home/admin/fiftyone/open-images-v6/train/metadata/attributes.csv' is not downloaded
```

Checking the metadata directory shows the following:

```
ls ~/fiftyone/open-images-v6/train/metadata/
classes.csv  hierarchy.json  image_ids.csv  segmentation_classes.csv
```

I verified the file isn't there and tried downloading the dataset again, but it didn't download, making me believe it's an error with the OpenImagesV6Dataset converter/exporter, although I'm not familiar enough with fiftyone to really know what's happening. Thanks for your help!

**Comment by brimoor** [comment]
Hi @finnjbm 👋 

I believe this is a consequence of the fact that the `fiftyone convert` syntax you shared above will also try to load the `relationships` labels, although you did not download them.

I was able to bypass the error by specifying that I'm only interested in `label_types=detections` as shown below:

```shell
fiftyone convert \
    --input-dir ~/fiftyone/open-images-v6/train/ \
    --output-dir /tmp/yolov5/train/ \
    --input-type fiftyone.types.dataset_types.OpenImagesV6Dataset \
    --output-type fiftyone.types.YOLOv5Dataset \
    --input-kwargs label_types=detections classes=Person max_samples=10 \
```

FYI, the above command is equivalent to the following code, which is likely more useful for you when trying to export multiple YOLOv5 splits, as you'll need to ensure that a single consistent `classes` list is used [as explained here](https://voxel51.com/docs/fiftyone/user_guide/export_datasets.html#yolov5dataset):

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset(
    "open-images-v6",
    split="train",
    label_types=["detections"],
    classes=["Person"],
    max_samples=10,
    download_if_necessary=False,
)

dataset.export(
    export_dir="/tmp/yolov5/train/",
    dataset_type=fo.types.YOLOv5Dataset,
)
```

**Comment by brimoor** [comment]
In fairness, this is
