### ISSUE TITLE
{BUG} 'KeyError' when converting dataset

### ISSUE THREAD

**Issue by rmg1996** [voxel51/fiftyone#2586]
Hello, I am new to Fiftyone and attempting to convert a dataset from COCO detection format to Yolov4 object detection format.  I have tried running the following code to convert my annotations: 

 fiftyone convert \ 
--input-dir /home/morgan/images_rgb_train \
--input-type fiftyone.types.COCODetectionDataset \
--output-dir /home/morgan/yolo/ \
--output-type fiftyone.types.YOLOv4Dataset

Upon executing, it appears that the files are found by the program (as the correct number of images is detailed on the load bar) , but then the program fails to read through them all for conversion returning the following error: 

Using input format: fiftyone.types.dataset_types.COCODetectionDataset
Using export format: fiftyone.types.dataset_types.YOLOv4Dataset
Loading dataset from '/home/morgan/images_rgb_train'
   0% |/------------------------------------------|     1/10318 [210.2us elapsed, 2.2s remaining, 39.6K samples/s]
Traceback (most recent call last):
  File "/home/morgan/.local/bin/fiftyone", line 8, in <module>
    sys.exit(main())
  File "/home/morgan/.local/lib/python3.8/site-packages/fiftyone/core/cli.py", line 3162, in main
    args.execute(args)
  File "/home/morgan/.local/lib/python3.8/site-packages/fiftyone/core/cli.py", line 3145, in <lambda>
    parser.set_defaults(execute=lambda args: command.execute(parser, args))
  File "/home/morgan/.local/lib/python3.8/site-packages/fiftyone/core/cli.py", line 370, in execute
    foud.convert_dataset(
  File "/home/morgan/.local/lib/python3.8/site-packages/fiftyone/utils/data/converters.py", line 127, in convert_dataset
    dataset.add_importer(dataset_importer)
  File "/home/morgan/.local/lib/python3.8/site-packages/fiftyone/core/dataset.py", line 3986, in add_importer
    return foud.import_samples(
  File "/home/morgan/.local/lib/python3.8/site-packages/fiftyone/utils/data/importers.py", line 142, in import_samples
    sample_ids = dataset.add_samples(
  File "/home/morgan/.local/lib/python3.8/site-packages/fiftyone/core/dataset.py", line 2209, in add_samples
    for batch in batcher:
  File "/home/morgan/.local/lib/python3.8/site-packages/fiftyone/core/utils.py", line 987, in __next__
    batch.append(next(self._iter))
  File "/home/morgan/.local/lib/python3.8/site-packages/fiftyone/utils/coco.py", line 433, in __next__
    image_path = self._image_paths_map[filename]
KeyError: 'data/video-23bsd9bsr962GdFBZ-frame-000221-arDqqfMYcrbEEqsex.jpg'

I have tried the fix mentioned in https://github.com/voxel51/fiftyone/issues/1675 but still have had no luck.  Tried to execute this code both from windows as well as Ubuntu.   Any help or advice would be greatly appreciated! Thanks!

**Comment by nghible** [comment]
I have the same issue but I was converting from CVATImageDataset to COCODetectionDataset. The issue seems to be that when the DatasetImporter get the filenames from the annotation file, the filenames does not contain the file extensions. But the names used in the self._image_paths_map does have the file extensions hence causing mismatch of the keys. Seems to be a simple fix.
