### ISSUE TITLE
[BUG] Error loading schema-changing view into grouped dataset

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#2832]
Load `quickstart-groups`:

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart-groups")
session = fo.launch_app(dataset)
```

Then try to load this view:

```py
session.view = dataset.select_group_slices(media_type="image").to_patches("ground_truth")
```

Error:

Route
http://localhost:5151/samples

Payload
```
{
  "filters": {},
  "view": [
    {
      "_cls": "fiftyone.core.stages.SelectGroupSlices",
      "kwargs": [
        [
          "slices",
          null
        ],
        [
          "media_type",
          "image"
        ]
      ],
      "_uuid": "a2413924-cd0f-44aa-b58c-46a2986abb02"
    },
    {
      "_cls": "fiftyone.core.stages.ToPatches",
      "kwargs": [
        [
          "field",
          "ground_truth"
        ],
        [
          "config",
          null
        ],
        [
          "_state",
          {
            "dataset": "quickstart-groups",
            "stages": [
              {
                "_cls": "fiftyone.core.stages.SelectGroupSlices",
                "kwargs": [
                  [
                    "slices",
                    null
                  ],
                  [
                    "media_type",
                    "image"
                  ]
                ]
              }
            ],
            "field": "ground_truth",
            "config": null,
            "name": "2023.03.22.11.00.39"
          }
        ]
      ],
      "_uuid": "c1b4bb94-d78e-4d95-a042-abedc340f552"
    }
  ],
  "dataset": "quickstart-groups",
  "extended": {},
  "slice": "left",
  "page": 3
}
```

Trace

```
Traceback (most recent call last):
  File "/Users/Brian/dev/fiftyone/fiftyone/server/decorators.py", line 34, in wrapper
    response = await func(endpoint, request, data, *args)
  File "/Users/Brian/dev/fiftyone/fiftyone/server/routes/samples.py", line 29, in post
    results = await paginate_samples(
  File "/Users/Brian/dev/fiftyone/fiftyone/server/samples.py", line 75, in paginate_samples
    view = fosv.get_view(
  File "/Users/Brian/dev/fiftyone/fiftyone/server/view.py", line 119, in get_view
    view.group_slice = sample_filter.group.slice
  File "/Users/Brian/dev/fiftyone/fiftyone/core/view.py", line 208, in group_slice
    raise ValueError("DatasetView has no groups")
ValueError: DatasetView has no groups
```

Upon refreshing the browser, the view then loads successfully.

**Comment by brimoor** [comment]
Hey @fnobis, indeed, sorry about the bug (I can reproduce the bug in your variation of the workflow as well). I'll push for this to be fixed in the next release.

In the meantime, a workaround is to clone the view into a temporary dataset and view that in the App instead:

```py
session.dataset = dataset.select_group_slices(media_type="image").clone()
```
