### ISSUE TITLE
[BUG] - Deleting annotation runs crashes entire server

### ISSUE THREAD

**Issue by stobias123** [voxel51/fiftyone#2867]
### Commands to reproduce

I had a bunch of old annotation runs, so to clean them up I did this.

```
ds = fo.load_dataset('foo')
for annotation in ds.list_annotation_runs():
    if 'train-v1_label_run_1' in annotation:
        ds.delete_annotation_run(annotation)
```

### Describe the problem

Now my whole server is borked until I reboot it. Web UI shows 500s. Logs are complaining about key errors.

If I reboot, things come back, but I cannot try to load the `foo` dataset. If I do things crash again.

```
[2023-03-31 21:07:15 +0000] [7] [INFO] Running on http://0.0.0.0:5151 (CTRL + C to quit)
to_dict

GraphQL request:7:3
6 |   ...DatasetSavedViewsFragment
7 |   dataset(name: $name, view: $view, savedViewSlug: $savedViewSlug) {
  |   ^
8 |     stages(slug: $savedViewSlug)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/bson/dbref.py", line 89, in __getattr__
    return self.__kwargs[key]
KeyError: 'to_dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/graphql/execution/execute.py", line 528, in await_result
    return_type, field_nodes, info, path, await result
  File "/usr/local/lib/python3.8/dist-packages/strawberry/schema/schema_converter.py", line 538, in _async_resolver
    return await await_maybe(_get_result(_source, strawberry_info, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/strawberry/utils/await_maybe.py", line 12, in await_maybe
    return await value
  File "/usr/local/lib/python3.8/dist-packages/fiftyone/server/query.py", line 297, in resolver
    return await serialize_dataset(
  File "/usr/local/lib/python3.8/dist-packages/fiftyone/server/query.py", line 530, in serialize_dataset
    return await loop.run_in_executor(None, run)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/fiftyone/server/query.py", line 471, in run
    doc = dataset._doc.to_dict(no_dereference=True)
  File "/usr/local/lib/python3.8/dist-packages/fiftyone/core/odm/dataset.py", line 472, in to_dict
    d["saved_views"] = [v.to_dict() for v in self.saved_views]
  File "/usr/local/lib/python3.8/dist-packages/fiftyone/core/odm/dataset.py", line 472, in <listcomp>
    d["saved_views"] = [v.to_dict() for v in self.saved_views]
  File "/usr/local/lib/python3.8/dist-packages/bson/dbref.py", line 91, in __getattr__
    raise AttributeError(key)
AttributeError: to_dict
Stack (most recent call last):
  File "/usr/local/lib/python/dist-packages/fiftyone/server/main.py", line 43, in <module>
    asyncio.run(serve(app, config), debug=foc.DEV_INSTALL)
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.8/dist-packages/strawberry/schema/execute.py", line 153, in execute
    process_errors(result.errors, execution_context)
view_stages

GraphQL request:115:3
114 | fragment DatasetSavedViewsFragment on Query {
115 |   savedViews(datasetName: $name) {
    |   ^
116 |     id
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/bson/dbref.py", line 89, in __getattr__
    return self.__kwargs[key]
KeyError: 'view_stages'

During handling of the above exception, another exception occurred:

```

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core Python library issue
-   [x] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [x] No. I cannot contribute a bug fix at this time

**Comment by brimoor** [comment]
I don't think this error has anything to do with the `delete_annotation_run()` calls you made. Are you working with a source install of `fiftyone`? Or are you running a release version?

It looks like the saved views on your dataset are corrupted somehow. If you can't find any other solution, you can manually delete the saved views like this:

```py
import fiftyone as fo

dataset = fo.load_dataset("foo")
dataset._doc.saved_views = []
dataset.save()
```
