### ISSUE TITLE
[BUG] Sample import from_dict does not work with exported datetime fields

### ISSUE THREAD

**Issue by Mawiszus** [voxel51/fiftyone#2899]
### System information

-   **OS Platform and Distribution**: Linux Ubuntu 20.04
-   **Python version**: Python 3.8.12
-   **FiftyOne version**: FiftyOne v0.20.0
-   **FiftyOne installed from**: pip

### Commands to reproduce

- Export a Samplecollection containing a datetime field with `dataset.to_dict`
- Re-import that dictionary with `dataset.from_dict`

```python
dataset_dict = dataset.to_dict()

second_dataset = fo.Dataset.from_dict(dataset_dict)
```

### Describe the problem

When exporting a Samplecollection, e.g. a Dataset, with `to_dict`, datetime fields are saved in the format `'field_name' : {'$date : datetime_iso_string}`, but the importer expects the format `'field_name' : datetime_object` and throws a ValidationError.
This behavior extends to `to_json` and `from_json`, as they internally use `to_dict` and `from_dict`.

### Code to reproduce issue

```python
import fiftyone as fo
from datetime import datetime

dataset = fo.Dataset("test-dataset")

sample = fo.Sample(filepath="/path/to/image.png", created_at=datetime.utcnow())

dataset.add_sample(sample)

dataset_dict = dataset.to_dict()

second_dataset = fo.Dataset.from_dict(dataset_dict)
```

### Other info/logs

Traceback of the code sample provided above:
```
Traceback (most recent call last):
  File "/home/deep/miniconda3/envs/workspace/lib/python3.8/site-packages/fiftyone/core/dataset.py", line 6209, in _validate_samples
    field.validate(value)
  File "/home/deep/miniconda3/envs/workspace/lib/python3.8/site-packages/fiftyone/core/fields.py", line 542, in validate
    self.error("Datetime fields must have `datetime` values")
  File "/home/deep/miniconda3/envs/workspace/lib/python3.8/site-packages/mongoengine/base/fields.py", line 171, in error
    raise ValidationError(message, errors=errors, field_name=field_name)
mongoengine.errors.ValidationError: Datetime fields must have `datetime` values

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/deep/miniconda3/envs/workspace/lib/python3.8/site-packages/fiftyone/core/dataset.py", line 5697, in from_dict
    dataset.add_samples(
  File "/home/deep/miniconda3/envs/workspace/lib/python3.8/site-packages/fiftyone/core/dataset.py", line 2422, in add_samples
    _ids = self._add_samples_batch(
  File "/home/deep/miniconda3/envs/workspace/lib/python3.8/site-packages/fiftyone/core/dataset.py", line 2486, in _add_samples_batch
    self._validate_samples(samples)
  File "/home/deep/miniconda3/envs/workspace/lib/python3.8/site-packages/fiftyone/core/dataset.py", line 6211, in _validate_samples
    raise ValueError(
ValueError: Invalid value for field 'created_at'. Reason: Datetime fields must have `datetime` values
```

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

**Comment by Mawiszus** [comment]
In my personal use case, I want to re-import the dataset from a json file, so I made a workaround by adding loading the file on my own instead of with `from_json` and adding an `object_hook` to the json loader:

```python
def json_import_date_hook(json_dict):
    """
        A hook for the json parser to import datetime straings as actual datetime objects
    """
    for (key, value) in json_dict.items():
        try:
            if isinstance(value, str):
                # parse top level datetime (e.g. in .info fields)
                json_dict[key] = parser.parse(value)
            else:  
                # undo nested datetime as exported by fo
                json_dict[key] = parser.parse(value["$date"])
        except:
            pass
    return json_dict
```

I read the file with `json.loads`:
```python
dataset_dict = json.loads(file.read(), object_hook=json_import_date_hook)
```

This makes the dictionary compliant with `from_dict`.
FiftyOne uses `etas.load_json(path_or_str)` in `from_json` internally, which does not seem to allow adding an `object_hook`.

In any case, even with this fix, the problem is still there when using `to_dict` and `from_dict` directly.
