### ISSUE TITLE
[BUG] Unable to login to CVAT 2.4: `415 Client Error: Unsupported Media Type`

### ISSUE THREAD

**Issue by ioangatop** [voxel51/fiftyone#2907]
### Description
After deploying a local CVAT instance though docker-compose, I was unable to login in my try to annotation data. I get a `415 Client Error: Unsupported Media Type` error as I try to log in, because it seems that the CVAT client sends the login credentials ad `data` and not `json` that the endpoint exists:
https://github.com/voxel51/fiftyone/blob/758537c1dd89635d985a1b6ab3acce4b05f9771f/fiftyone/utils/cvat.py#L3691

### Proposal fix
The issue can be easily resolved by replacing `data` key-word argument with json as follows:
```py3
json={"username": username, "password": password},
```

### Replicate and logs

Code to replicate the issue:
```py3
dataset = foz.load_zoo_dataset("quickstart", max_samples=1)

results = dataset.annotate(
    "reannotation",
    label_field="ground_truth",
    backend="cvat",
    url="http://localhost:8080",
    username="username",
    password="password",
)
```
The error message:
```bash
requests.exceptions.HTTPError: 415 Client Error: Unsupported Media Type for url: http://localhost:8080/api/auth/login
```

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [x] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

**Comment by fiastros** [comment]
After I change "data" into "json" in cvat.py, i get another type of error:
      
      Uploading samples to CVAT...
      Traceback (most recent call last):
        File "/home/loic/Documents/10-THESE_ciffre/projets/02_fiftyone/another_cvat_test.py", line 9, in <module>
          view.annotate(
        File "/home/loic/Documents/10-THESE_ciffre/projets/02_fiftyone/venv/lib/python3.10/site-packages/fiftyone/core/collections.py", line 7907, in annotate
          return foua.annotate(
        File "/home/loic/Documents/10-THESE_ciffre/projets/02_fiftyone/venv/lib/python3.10/site-packages/fiftyone/utils/annotations.py", line 247, in annotate
          results = anno_backend.upload_annotations(
        File "/home/loic/Documents/10-THESE_ciffre/projets/02_fiftyone/venv/lib/python3.10/site-packages/fiftyone/utils/cvat.py", line 3249, in upload_annotations
          results = api.upload_samples(samples, anno_key, self)
        File "/home/loic/Documents/10-THESE_ciffre/projets/02_fiftyone/venv/lib/python3.10/site-packages/fiftyone/utils/cvat.py", line 4344, in upload_samples
          ) = self._create_task_upload_data(
        File "/home/loic/Documents/10-THESE_ciffre/projets/02_fiftyone/venv/lib/python3.10/site-packages/fiftyone/utils/cvat.py", line 5105, in _create_task_upload_data
          task_id, class_id_map, attr_id_map = self.create_task(
        File "/home/loic/Documents/10-THESE_ciffre/projets/02_fiftyone/venv/lib/python3.10/site-packages/fiftyone/utils/cvat.py", line 4011, in create_task
          class_id = label["id"]
      TypeError: string indices must be integers

**Comment by ioangatop** [comment]
@fiastros indeed this is due to 2.4 (related issue: https://github.com/voxel51/fiftyone/issues/2732)

I do have the full fix but I didn't want to make the PR big and/or duplicate the other; however if you think this would not be an issue I can submit all

**Comment by nsriniva03** [comment]
Is there any update on this issue? @ioangatop, were you able to login to cvat?

**Comment by abdelmasrour** [comment]
did you solve issue

**Comment by yrrah** [comment]
looks like it was addressed here https://github.com/voxel51/fiftyone/pull/2903

**Comment by ioangatop** [comment]
Indeed, resolved!
