### ISSUE TITLE
[BUG] numba error when running compute_visualization() with method=umap

### ISSUE THREAD

**Issue by NevilleMthw** [voxel51/fiftyone#2955]
### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.6 LTS
-   **Python version** (`python --version`): Python 3.10.9
-   **FiftyOne version** (`fiftyone --version`): FiftyOne v0.20.1, Voxel51, Inc.
-   **FiftyOne installed from** (pip or source): pip

### Commands to reproduce

As thoroughly as possible, please provide the Python and/or shell commands used to encounter the issue. Application steps can be described in the next section.

```
python fifty.py
```

### Describe the problem

I am trying to run a sample code from the documentation of Fiftyone and I cannot get it to run, I get a strange error which I cannot seem to understand.

### Code to reproduce issue

```
import cv2
import numpy as np

import fiftyone as fo
import fiftyone.brain as fob
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("mnist", split="test")
print(type(dataset))

# Construct a `num_samples x num_pixels` array of images
images = np.array([
    cv2.imread(f, cv2.IMREAD_UNCHANGED).ravel()
    for f in dataset.values("filepath")
])
print(type(images))
# Compute 2D embeddings
results = fob.compute_visualization(dataset, embeddings=images, seed=51)
```

### Other info/logs

```
Split 'test' already downloaded
Loading 'mnist' split 'test'
 100% |███████████████████████████████████████████████████████████████| 10000/10000 [3.3s elapsed, 0s remaining, 3.1K samples/s]      
Dataset 'mnist-test' created
<class 'fiftyone.core.dataset.Dataset'>
<class 'numpy.ndarray'>
Generating visualization...
/home/intern/anaconda3/lib/python3.10/site-packages/umap/distances.py:1053: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
/home/intern/anaconda3/lib/python3.10/site-packages/umap/distances.py:1061: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
/home/intern/anaconda3/lib/python3.10/site-packages/umap/distances.py:1076: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
Traceback (most recent call last):
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/core/errors.py", line 823, in new_error_context
    yield
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/core/lowering.py", line 285, in lower_block
    self.lower_inst(inst)
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/core/lowering.py", line 463, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/core/lowering.py", line 675, in lower_assign
    return self.lower_expr(ty, value)
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/core/lowering.py", line 1211, in lower_expr
    res = self.lower_call(resty, expr)
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/core/lowering.py", line 940, in lower_call
    res = self._lower_call_normal(fnty, expr, signature)
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/core/lowering.py", line 1182, in _lower_call_normal
    res = impl(self.builder, argvals, self.loc)
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/core/base.py", line 1187, in __call__
    res = self._imp(self._context, builder, self._sig, args, loc=loc)
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/core/base.py", line 1217, in wrapper
    return fn(*args, **kwargs)
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/cpython/rangeobj.py", line 38, in range1_impl
    state.stop = stop
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/core/cgutils.py", line 164, in __setattr__
    self[self._datamodel.get_field_position(field)] = value
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/core/cgutils.py", line 188, in __setitem__
    raise TypeError("Invalid store of {value.type} to "
TypeError: Invalid store of i64 to i32 in <numba.core.datamodel.models.RangeModel object at 0x7f98cd843880> (trying to write member #1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/intern/Desktop/fifty.py", line 57, in <module>
    results = fob.compute_visualization(dataset, embeddings=images, seed=51)
  File "/home/intern/anaconda3/lib/python3.10/site-packages/fiftyone/brain/__init__.py", line 378, in compute_visualization
    return fbv.compute_visualization(
  File "/home/intern/anaconda3/lib/python3.10/site-packages/fiftyone/brain/internal/core/visualization.py", line 113, in compute_visualization
    points = brain_method.fit(embeddings)
  File "/home/intern/anaconda3/lib/python3.10/site-packages/fiftyone/brain/internal/core/visualization.py", line 229, in fit
    _umap = umap.UMAP(
  File "/home/intern/anaconda3/lib/python3.10/site-packages/fiftyone/core/utils.py", line 646, in __getattr__
    self._import_module()
  File "/home/intern/anaconda3/lib/python3.10/site-packages/fiftyone/core/utils.py", line 662, in _import_module
    module = importlib.import_module(self.__name__)
  File "/home/intern/anaconda3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/intern/anaconda3/lib/python3.10/site-packages/umap/__init__.py", line 2, in <module>
    from .umap_ import UMAP
  File "/home/intern/anaconda3/lib/python3.10/site-packages/umap/umap_.py", line 41, in <module>
    from umap.layouts import (
  File "/home/intern/anaconda3/lib/python3.10/site-packages/umap/layouts.py", line 39, in <module>
    def rdist(x, y):
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/core/decorators.py", line 241, in wrapper
    disp.compile(sig)
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/core/dispatcher.py", line 965, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/core/dispatcher.py", line 125, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/core/dispatcher.py", line 139, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/core/dispatcher.py", line 152, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/core/compiler.py", line 742, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/core/compiler.py", line 460, in compile_extra
    return self._compile_bytecode()
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/core/compiler.py", line 528, in _compile_bytecode
    return self._compile_core()
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/core/compiler.py", line 507, in _compile_core
    raise e
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/core/compiler.py", line 494, in _compile_core
    pm.run(self.state)
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 368, in run
    raise patched_exception
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/core/typed_passes.py", line 466, in run_pass
    lower.lower()
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/core/lowering.py", line 187, in lower
    self.lower_normal_function(self.fndesc)
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/core/lowering.py", line 241, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/core/lowering.py", line 271, in lower_function_body
    self.lower_block(block)
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/core/lowering.py", line 283, in lower_block
    with new_error_context('lowering "{inst}" at {loc}', inst=inst,
  File "/home/intern/anaconda3/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/intern/anaconda3/lib/python3.10/site-packages/numba/core/errors.py", line 837, in new_error_context
    raise newerr.with_traceback(tb)
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: native lowering)
Invalid store of i64 to i32 in <numba.core.datamodel.models.RangeModel object at 0x7f98cd843880> (trying to write member #1)

File "../anaconda3/lib/python3.10/site-packages/umap/layouts.py", line 53:
def rdist(x, y):
    <source elided>
    dim = x.shape[0]
    for i in range(dim):
    ^

During: lowering "$20call_function.7 = call $16load_global.5(dim, func=$16load_global.5, args=[Var(dim, layouts.py:52)], kws=(), vararg=None, varkwarg=None, target=None)" at /home/intern/anaconda3/lib/python3.10/site-packages/umap/layouts.py (53)
```

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [x] No. I cannot contribute a bug fix at this time

**Comment by brimoor** [comment]
I believe this is some kind of issue with [umap-learn](https://github.com/lmcinnes/umap) and its installation of `numba`, which is outside the scope of the FiftyOne codebase itself.

**Comment by NevilleMthw** [comment]
Oh alright, thanks for the reply. So would it be better for me to create an issue in their GH repo and reference this?

**Comment by NevilleMthw** [comment]
This issue has been resolved, please check the referenced issue above.
