### ISSUE TITLE
[BUG] Creating views crashes the App (except if using the app's view bar)

### ISSUE THREAD

**Issue by alen-smajic** [voxel51/fiftyone#3112]
### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
-   **Python version** (`python --version`): 3.8.5
-   **FiftyOne version** (`fiftyone --version`): 0.20.1
-   **FiftyOne installed from** (pip or source): pip

### Commands to reproduce

```
session = fo.launch_app(my_dataset)  # This works just fine
session = fo.launch_app(my_dataset.take(2))  # This crashes the App
```

### Describe the problem

When I try to create dataset views and load them into the app, it just crashes with the following error message:
TypeError: Cannot read properties of undefined (reading 'stack')
    at http://localhost:5151/assets/index.22e7b001.js:755:16
    at Array.map (<anonymous>)
    at http://localhost:5151/assets/index.22e7b001.js:753:82704
    at EJ (http://localhost:5151/assets/index.22e7b001.js:61:19168)
    at v1e (http://localhost:5151/assets/index.22e7b001.js:63:44857)
    at m1e (http://localhost:5151/assets/index.22e7b001.js:63:40452)
    at D$e (http://localhost:5151/assets/index.22e7b001.js:63:40375)
    at MP (http://localhost:5151/assets/index.22e7b001.js:63:40225)
    at nQ (http://localhost:5151/assets/index.22e7b001.js:63:36544)
    at d1e (http://localhost:5151/assets/index.22e7b001.js:63:35487)
    
If I try to create the same view via the app's view bar, it works just fine. 

### Code to reproduce issue

session = fo.launch_app(my_dataset.take(2))

### Other info/logs

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Please do not use screenshots for sharing text. Code snippets should be used instead when providing tracebacks, logs, etc.

### What areas of FiftyOne does this bug affect?

-   [X] `App`: FiftyOne application issue
-   [ ] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [X] No. I cannot contribute a bug fix at this time

**Comment by alen-smajic** [comment]
Upgrading to the newest version (0.21.0) solved the issue for me.
