### ISSUE TITLE
[BUG] DatabaseService failed to bind to port

### ISSUE THREAD

**Issue by NicoJorgensen1** [voxel51/fiftyone#3188]
### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 16.04): Ubuntu 20.04. Both inside and outside a docker container running ubuntu 20.04.
-   **Python version** (`python --version`): python3.9
-   **FiftyOne version** (`fiftyone --version`): fiftyone v0.21.0
-   **FiftyOne installed from** (pip or source): pip

### Commands to reproduce

As thoroughly as possible, please provide the Python and/or shell commands used to encounter the issue. Application steps can be described in the next section.

```
python -m pip install fiftyone
python -c "import fiftyone as fo"
```

### Describe the problem

I have an ssh connection to a server computer in my basement. I have ssh'ed into the computer through "Attach to Host" in vscode.
On the server computer I install fiftyone - both locally and when running a docker container.
The installation goes without any issues.
In python I can say `import fiftyone as fo` and then I quickly get an error with something like "subprocess failed with error 14": 
```
`{"t":{"$date":"2023-06-12T12:22:56.265Z"},"s":"I",  "c":"CONTROL",  "id":20697,   "ctx":"-","msg":"Renamed existing log file","attr":{"oldLogPath":"/fiftyone/db/log/mongo.log","newLogPath":"/fiftyone/db/log/mongo.log.2023-06-12T12-22-56"}}
Subprocess ['/usr/local/lib/python3.9/dist-packages/fiftyone/db/bin/mongod', '--dbpath', '/fiftyone/db', '--logpath', '/fiftyone/db/log/mongo.log', '--port', '0', '--nounixsocket'] exited with error 14:`
```

Then the process times out, waits for a while, and then several new error messages with a traceback are displayed, ending with fiftyone.core.service.ServiceListenTimeout: fiftyone.core.service.DatabaseService failed to bind to port:
```
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/fiftyone/__init__.py", line 25, in <module>
    from fiftyone.__public__ import *
  File "/usr/local/lib/python3.9/dist-packages/fiftyone/__public__.py", line 15, in <module>
    _foo.establish_db_conn(config)
  File "/usr/local/lib/python3.9/dist-packages/fiftyone/core/odm/database.py", line 200, in establish_db_conn
    port = _db_service.port
  File "/usr/local/lib/python3.9/dist-packages/fiftyone/core/service.py", line 276, in port
    return self._wait_for_child_port()
  File "/usr/local/lib/python3.9/dist-packages/fiftyone/core/service.py", line 170, in _wait_for_child_port
    return find_port()
  File "/usr/local/lib/python3.9/dist-packages/retrying.py", line 56, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python3.9/dist-packages/retrying.py", line 266, in call
    raise attempt.get()
  File "/usr/local/lib/python3.9/dist-packages/retrying.py", line 301, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.9/dist-packages/retrying.py", line 251, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/lib/python3.9/dist-packages/fiftyone/core/service.py", line 168, in find_port
    raise ServiceListenTimeout(etau.get_class_name(self), port)
fiftyone.core.service.ServiceListenTimeout: fiftyone.core.service.DatabaseService failed to bind to port``
```

### Other info/logs

Don't know if any logs are saved anywhere, but here is a copy of the output in the terminal after trying to 'import fiftyone as fo'.
Here is an example of the entire error message printed out when trying to import fiftyone:
```
`goatherd@aiserver2:~/fiftyone$ python -c "import fiftyone as fo"
{"t":{"$date":"2023-06-12T12:22:56.265Z"},"s":"I",  "c":"CONTROL",  "id":20697,   "ctx":"-","msg":"Renamed existing log file","attr":{"oldLogPath":"/fiftyone/db/log/mongo.log","newLogPath":"/fiftyone/db/log/mongo.log.2023-06-12T12-22-56"}}
Subprocess ['/usr/local/lib/python3.9/dist-packages/fiftyone/db/bin/mongod', '--dbpath', '/fiftyone/db', '--logpath', '/fiftyone/db/log/mongo.log', '--port', '0', '--nounixsocket'] exited with error 14:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/fiftyone/__init__.py", line 25, in <module>
    from fiftyone.__public__ import *
  File "/usr/local/lib/python3.9/dist-packages/fiftyone/__public__.py", line 15, in <module>
    _foo.establish_db_conn(config)
  File "/usr/local/lib/python3.9/dist-packages/fiftyone/core/odm/database.py", line 200, in establish_db_conn
    port = _db_service.port
  File "/usr/local/lib/python3.9/dist-packages/fiftyone/core/service.py", line 276, in port
    return self._wait_for_child_port()
  File "/usr/local/lib/python3.9/dist-packages/fiftyone/core/service.py", line 170, in _wait_for_child_port
    return find_port()
  File "/usr/local/lib/python3.9/dist-packages/retrying.py", line 56, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python3.9/dist-packages/retrying.py", line 266, in call
    raise attempt.get()
  File "/usr/local/lib/python3.9/dist-packages/retrying.py", line 301, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.9/dist-packages/retrying.py", line 251, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/lib/python3.9/dist-packages/fiftyone/core/service.py", line 168, in find_port
    raise ServiceListenTimeout(etau.get_class_name(self), port)
fiftyone.core.service.ServiceListenTimeout: fiftyone.core.service.DatabaseService failed to bind to port`
```

The weird thing is that after a restart of my computer/server, I am good to go and able to re-import fiftyone using a regular script.
If I run the command in "regular" mode, I get no errors, as shown below:
![image](https://github.com/voxel51/fiftyone/assets/70665230/1e285cb3-bf49-4b90-8856-694a24a870d0)

If I use debug mode in vscode, I get the error.
![image](https://github.com/voxel51/fiftyone/assets/70665230/eea0ab3e-f26f-4bae-a64a-3f34762467b6)
In this screenshot it says that there is a `ModuleNotFoundERror: No module named fiftyone`, which is kind of weird as it is the same environment as I use when not running in debug mode.
Therefore, I feel like something is wrong with the debugging mode of vscode and fiftyone, I just don't know what...

### What areas of FiftyOne does this bug affect?

-   [ X ] `App`: FiftyOne application issue
-   [ ] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [X] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

**Comment by kaixi-wang** [comment]
have you set up port forwarding for the db server? https://code.visualstudio.com/docs/remote/ssh-tutorial#:~:text=your%20virtual%20machine.-,Port%20forwarding,-To%20be%20able

**Comment by NicoJorgensen1** [comment]
Hi @kaixi-wang.
With regards to port forwarding the answer is yes; and as I am able to perform `python -c import fiftyone as fo` without errors when running regularly, but not when running in debug mode, I assume something is wrong with the debug module or with how the MongoDB initialization is created - but I really have no clue.

However, today I have been testing the environment a bit further. Perhaps I was too quick to mention that the issue was happening only on my remote machine. Sorry about that as that might have mislead you guys. I was simply only developing on my remote machine as I want my fiftyone app to be accessible 24/7, and my remote machine is turned on 24/7, so I simply thought developing through a ssh connection to that machine was the easiest way of making that happen.
Now, I don't (necessarily) think that the issue is related to using my basement-server computer. I think it is more related to how the fiftyone process is initialized/closed, when running vscode in debug mode.

### A minimal reproducible example

- On my local laptop I have a script named `run_51.py`. In this script the only line is `import fiftyone as fo`.
- I can now run this script using two options, either through the regular "run python file" command or using "debug python file". 
![debug_mode](https://github.com/voxel51/fiftyone/assets/70665230/46ad2a79-7dca-4c42-9fa7-4e758be90d07)

1.  If I choose to run the script normaly using `python3 run_51.py` then I can do that in an endless loop without any issues, as seen on the below screenshot:
![image](https://github.com/voxel51/fiftyone/assets/70665230/3caf1ded-2115-464f-a927-e2e33b62f8ac)
2. If I choose to run the script in debug mode, then the first time I run the script, the import will succed. The second time, I will get the error.
![image](https://github.com/voxel51/fiftyone/assets/70665230/15c4853a-bbe9-4d76-808d-43b36d3464d2)

The entire printed log, which you can see in my terminal are these lines:
```
`nico@nico-Legion:~/Documents/Capra_Projects/voxel51_fiftyone$  cd /home/nico/Documents/Capra_Projects/voxel51_fiftyone ; /usr/bin/env /bin/python3 /home/nico/.vscode/extensions/ms-python.python-2023.10.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 50525 -- /home/nico/Documents/Capra_Projects/voxel51_fiftyone/run_51.py 
{"t":{"$date":"2023-06-13T05:31:21.401Z"},"s":"I",  "c":"CONTROL",  "id":20697,   "ctx":"-","msg":"Renamed existing log file","attr":{"oldLogPath":"/home/nico/.fiftyone/var/lib/mongo/log/mongo.log","newLogPath":"/home/nico/.fiftyone/var/lib/mongo/log/mongo.log.2023-06-13T05-31-21"}}
Subprocess ['/home/nico/.local/lib/python3.8/site-packages/fiftyone/db/bin/mongod', '--dbpath', '/home/nico/.fiftyone/var/lib/mongo', '--logpath', '/home/nico/.fiftyone/var/lib/mongo/log/mongo.log', '--port', '0', '--nounixsocket'] exited with error 100:
Backend GTK3Agg is interactive backend. Turning interactive mode on.`
```

As this happens on my local laptop (running ubuntu 20.04) and not on my remote machine, this is what leads me to think that the issue is related to how the MongoDB instance is created/closed, when running in debug mode in vscode.
Again, sorry for the misleading with regards to my remote machine...
