### ISSUE TITLE
[BUG] ``evaluate_detections`` throws a ``ValueError: Failed to update sample`` error

### ISSUE THREAD

**Issue by stwerner97** [voxel51/fiftyone#3207]
### System information

-   **OS Platform and Distribution**: ``Linux Ubuntu 20.04``
-   **Python version**: ``Python 3.9.16``
-   **FiftyOne version**: ``FiftyOne v0.21.0, Voxel51, Inc.``
-   **FiftyOne installed from**: ``pip``

### Describe the problem

I use the code below to load a dataset (coco-2017) and evaluate an object detection network on it.  An error is thrown once I call the ``evaluate_detections`` method. The same code works fine for another neural network, but the thrown error gives no indication that an invalid format of the predictions or something similar are at fault. Instead it throws an ``Failed to update sample`` error once the evaluation is about 50% - 75% complete.

### Code to reproduce issue

```python
<... some-more-code-above ...>

dataset_type = fo.types.COCODetectionDataset

dataset = fo.Dataset.from_dir(
    dataset_dir=cfg.dataset.location,
    dataset_type=dataset_type,
    tags=[cfg.dataset.tag],
)

predictions = fo.Dataset(run_name)
predictions.persist = True

with fo.ProgressBar() as pb:
    for sample in pb(dataset):
        result = model.detect(sample)

        detections = []
        for label, score, bbox in result:
            detections.append(
                fo.Detection(label=label, bounding_box=bbox, confidence=score)
            )

        prediction = fo.Sample(filepath=sample.filepath)
        prediction[run_name] = fo.Detections(detections=detections)

        predictions.add_sample(prediction)

dataset.merge_samples(predictions)

results = dataset.evaluate_detections(
    run_name,
    gt_field=cfg.dataset.gt_field,
    eval_key="eval",
    compute_mAP=True,
)

results.print_report()
```

### Other info/logs

```
Traceback (most recent call last):
  File "<some-path>/evaluate.py", line 77, in evaluate
    results = dataset.evaluate_detections(
  File "/root/fiftyone-detections/lib/python3.9/site-packages/fiftyone/core/collections.py", line 3131, in evaluate_detections
    return foue.evaluate_detections(
  File "/root/fiftyone-detections/lib/python3.9/site-packages/fiftyone/utils/eval/detection.py", line 207, in evaluate_detections
    sample.save()
  File "/root/fiftyone-detections/lib/python3.9/site-packages/fiftyone/core/sample.py", line 738, in save
    super().save()
  File "/root/fiftyone-detections/lib/python3.9/site-packages/fiftyone/core/document.py", line 825, in save
    self._save()
  File "/root/fiftyone-detections/lib/python3.9/site-packages/fiftyone/core/sample.py", line 746, in _save
    sample_ops = super()._save(deferred=deferred)
  File "/root/fiftyone-detections/lib/python3.9/site-packages/fiftyone/core/document.py", line 829, in _save
    return self._doc._save(
  File "/root/fiftyone-detections/lib/python3.9/site-packages/fiftyone/core/odm/document.py", line 643, in _save
    raise ValueError(
ValueError: Failed to update sample with ID '648c6817545d90c81f4bb7c5'
```

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

-   [ ] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [x] No. I cannot contribute a bug fix at this time

**Comment by stwerner97** [comment]
I located the source of the error. Under some conditions my model would output all-zero bounding boxes, confidence scores, etc., leading to the error above. Still, it would be nice if ``fiftyone`` could throw a less opaque error message or not fail in the first place for such outputs.
