### ISSUE TITLE
[BUG] Issue with cloning group datasets

### ISSUE THREAD

**Issue by benjaminpkane** [voxel51/fiftyone#3334]
Selecting fields and cloning seems to copy unwanted fields into the clone. This issue only applies to group datasets
```py
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
dataset = dataset.select_fields().clone("image-clone")
dataset.first() # Works

dataset = foz.load_zoo_dataset("quickstart-groups")
dataset = dataset.select_fields().clone("group-clone")
dataset.first() # Unexpected ground truth data
```

Traceback
```
Traceback (most recent call last):
  File "/Users/benjaminkane/code/fiftyone/fiftyone/core/dataset.py", line 6406, in _sample_dict_to_doc
    return self._sample_doc_cls.from_dict(d, extended=False)
  File "/Users/benjaminkane/code/fiftyone/fiftyone/core/odm/document.py", line 452, in from_dict
    return cls._from_son(d)
  File "/Users/benjaminkane/venvs/fo/lib/python3.10/site-packages/mongoengine/base/document.py", line 837, in _from_son
    obj = cls(__auto_convert=False, _created=created, **data)
  File "/Users/benjaminkane/venvs/fo/lib/python3.10/site-packages/mongoengine/base/document.py", line 99, in __init__
    raise FieldDoesNotExist(msg)
mongoengine.errors.FieldDoesNotExist: The fields "{'ground_truth'}" do not exist on the document "samples.64bea2e5c505526444f4d0c0"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/benjaminkane/code/scratch/mult-pcd.py", line 5, in <module>
    dataset.first()
  File "/Users/benjaminkane/code/fiftyone/fiftyone/core/dataset.py", line 1114, in first
    return super().first()
  File "/Users/benjaminkane/code/fiftyone/fiftyone/core/collections.py", line 712, in first
    return next(iter(self))
  File "/Users/benjaminkane/code/fiftyone/fiftyone/core/dataset.py", line 2183, in iter_samples
    for sample in samples:
  File "/Users/benjaminkane/code/fiftyone/fiftyone/core/dataset.py", line 2199, in _iter_samples
    sample = make_sample(d)
  File "/Users/benjaminkane/code/fiftyone/fiftyone/core/dataset.py", line 2212, in make_sample
    doc = self._sample_dict_to_doc(d)
  File "/Users/benjaminkane/code/fiftyone/fiftyone/core/dataset.py", line 6412, in _sample_dict_to_doc
    return self._sample_doc_cls.from_dict(d, extended=False)
  File "/Users/benjaminkane/code/fiftyone/fiftyone/core/odm/document.py", line 452, in from_dict
    return cls._from_son(d)
  File "/Users/benjaminkane/venvs/fo/lib/python3.10/site-packages/mongoengine/base/document.py", line 837, in _from_son
    obj = cls(__auto_convert=False, _created=created, **data)
  File "/Users/benjaminkane/venvs/fo/lib/python3.10/site-packages/mongoengine/base/document.py", line 99, in __init__
    raise FieldDoesNotExist(msg)
mongoengine.errors.FieldDoesNotExist: The fields "{'ground_truth'}" do not exist on the document "samples.64bea2e5c505526444f4d0c0"
```

**Comment by benjaminpkane** [comment]
Resolved by #3336
