### ISSUE TITLE
[BUG] wide-resnet50-2-imagenet-torch weights argument is incorrect

### ISSUE THREAD

**Issue by helioshe4** [voxel51/fiftyone#3394]
### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
-   **Python version** (`python --version`): 3.8.10
-   **FiftyOne version** (`fiftyone --version`): 0.21.4
-   **FiftyOne installed from** (pip or source): from source
-   **torchvision version** (pip show torchvision): 0.14.0

### Commands to reproduce
This is regarding the code on the `release/v0.21.5 branch` introduced by #3348.

```
import fiftyone.zoo as foz

model = foz.load_zoo_model("wide-resnet50-2-imagenet-torch")
```

### Describe the problem

Expected behaviour: 
```
Downloading: "https://download.pytorch.org/models/wide_resnet50_2-9ba9bcbe.pth" to /home/helioshe4/.cache/torch/hub/checkpoints/wide_resnet50_2-9ba9bcbe.pth
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 263M/263M [00:24<00:00, 11.3MB/s]
```
Actual behaviour:
```
Traceback (most recent call last):
  File "model_test.py", line 4, in <module>
    model = foz.load_zoo_model("wide-resnet50-2-imagenet-torch")
  File "/home/helioshe4/personal_cs/fiftyone/fiftyone/zoo/models/__init__.py", line 216, in load_zoo_model
    model = fom.load_model(config_dict, model_path=model_path, **kwargs)
  File "/home/helioshe4/personal_cs/fiftyone/fiftyone/core/models.py", line 1777, in load_model
    return config.build()
  File "/home/helioshe4/personal_cs/fiftyone/env/lib/python3.8/site-packages/eta/core/learning.py", line 296, in build
    return self._model_cls(self.config)
  File "/home/helioshe4/personal_cs/fiftyone/fiftyone/utils/torch.py", line 238, in __init__
    self._model = self._load_model(config)
  File "/home/helioshe4/personal_cs/fiftyone/fiftyone/utils/torch.py", line 483, in _load_model
    model = self._load_network(config)
  File "/home/helioshe4/personal_cs/fiftyone/fiftyone/zoo/models/torch.py", line 114, in _load_network
    model = entrypoint(**kwargs)
  File "/home/helioshe4/personal_cs/fiftyone/env/lib/python3.8/site-packages/torchvision/models/_utils.py", line 142, in wrapper
    return fn(*args, **kwargs)
  File "/home/helioshe4/personal_cs/fiftyone/env/lib/python3.8/site-packages/torchvision/models/_utils.py", line 228, in inner_wrapper
    return builder(*args, **kwargs)
  File "/home/helioshe4/personal_cs/fiftyone/env/lib/python3.8/site-packages/torchvision/models/resnet.py", line 914, in wide_resnet50_2
    weights = Wide_ResNet50_2_Weights.verify(weights)
  File "/home/helioshe4/personal_cs/fiftyone/env/lib/python3.8/site-packages/torchvision/models/_api.py", line 58, in verify
    obj = cls.from_str(obj.replace(cls.__name__ + ".", ""))
  File "/home/helioshe4/personal_cs/fiftyone/env/lib/python3.8/site-packages/torchvision/_utils.py", line 16, in from_str
    raise ValueError(f"Unknown value '{member}' for {self.__name__}.") from None
ValueError: Unknown value 'wide-resnet50-2-imagenet-torch' for Wide_ResNet50_2_Weights.
```

### What areas of FiftyOne does this bug affect?

-   [x] `App`: FiftyOne application issue
-   [ ] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

Willing to contribute, but fix should be easy.  Change line 1836 in manifest-torch.json from `wide-resnet50-2-imagenet-torch` to `Wide_ResNet50_2_Weights.DEFAULT`. Fix works locally.   
https://github.com/voxel51/fiftyone/blob/aa498dca6942d401d08edd4d6e2ecb84b16fe383/fiftyone/zoo/models/manifest-torch.json#L1830-L1844

Made a mistake in #3348, my bad

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [x] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

**Comment by brimoor** [comment]
@helioshe4 yes I discovered this and already fixed it on `release/v0.21.5` in [this commit](https://github.com/voxel51/fiftyone/commit/181f3e30e5ed81c9ca46b26631d9d073c7edf52c). We're all set!
