### ISSUE TITLE
[BUG] draw_labels can't assign different colors to different labels

### ISSUE THREAD

**Issue by twmht** [voxel51/fiftyone#3410]
### Instructions

Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/voxel51/fiftyone/blob/develop/ISSUE_POLICY.md) for information on what types of issues we address.

1. Please fill in this template to ensure a timely and thorough response
2. Place an "x" between the brackets next to an option if it applies. For example:
    -   [x] Selected option
3. **Please delete everything above this line before submitting the issue**

### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 16.04):Ubuntu  22.04
-   **Python version** (`python --version`):3.9.16
-   **FiftyOne version** (`fiftyone --version`):0.21.4
-   **FiftyOne installed from** (pip or source):pip

### Commands to reproduce

As thoroughly as possible, please provide the Python and/or shell commands used to encounter the issue. Application steps can be described in the next section.

```
# commands here
```

### Describe the problem

I have created a fiftyone video dataset, which containing 3 video samples, and i want to draw bounding box on them and exporting to new video files.

But I found out sometimes different labels may have same colors even i have specified `per_object_label_colors=True` with config.

### Code to reproduce issue

```py
import fiftyone as fo
import fiftyone.utils.annotations as foua
#  from fiftyone.utils.annotations import draw_labeled_videos, draw_labeled_video

dataset=fo.load_dataset('test_clip_1')
labels_field=['predictions']


config = foua.DrawConfig(
    {
        "per_object_label_colors": True
    }
)


dataset.draw_labels('/home/shared/samba/s2/s2/Alec/out_test_clip_3', labels_field=labels_field, config=config)
```

### Other info/logs

Besides this bug, Can we manual assign color to each label? I think this is very common feature but i could not find the usage from api document,.

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [x] No. I cannot contribute a bug fix at this time

**Comment by benjaminpkane** [comment]
HI @twmht. I believe there is a limit to the number of colors used when drawing. You can increase that number by providing a `colormap_config`.

```py
import fiftyone as fo
import fiftyone.utils.annotations as foua
import eta.core.annotations as etaa

#  from fiftyone.utils.annotations import draw_labeled_videos, draw_labeled_video

dataset = fo.load_dataset("test_clip_1")
labels_field = ["predictions"]

NUM_COLORS = 100


config = foua.DrawConfig(
    {
        "per_object_label_colors": True,
        "colormap_config": etaa.ColormapConfig(
            {
                "type": "core.annotations.ShuffledHLSColormap",
                "config": etaa.ShuffledHLSColormapConfig({"num_colors": NUM_COLORS}),
            }
        ),
    }
)


dataset.draw_labels('/home/shared/samba/s2/s2/Alec/out_test_clip_3', labels_field=labels_field, config=config)
```

**Comment by twmht** [comment]
@benjaminpkane 

I have tried the code you provided, but got 

```py
Traceback (most recent call last):                                                                                                                                                                  File "/home/shared/fiftyone_playground/draw_video.py", line 31, in <module>                                                                                                                         "colormap_config": etaa.ColormapConfig(                                                                                                                                                         File "/home/acer/.pyenv/versions/training_env/lib/python3.9/site-packages/eta/core/annotations.py", line 609, in __init__                                                                           self._colormap_cls, config_cls = Configurable.parse(self.type)                                                                                                                                  File "/home/acer/.pyenv/versions/training_env/lib/python3.9/site-packages/eta/core/config.py", line 149, in parse                                                                                   cls = etau.get_class(class_name, module_name=module_name)                                                                                                                                       File "/home/acer/.pyenv/versions/training_env/lib/python3.9/site-packages/eta/core/utils.py", line 586, in get_class                                                                                __import__(module_name)  # does nothing if module is already imported                                                                                                                         ModuleNotFoundError: No module named 'core' 
```

**Comment by twmht** [comment]
fixed the errror by changing "type": "core.annotations.ShuffledHLSColormap", to type": "eta.core.annotations.ShuffledHLSColormap"

**Comment by twmht** [comment]
still the same color, in fact i only have 3 classes, 
as you can see those two classes share the same color

![image](https://github.com/voxel51/fiftyone/assets/1567200/c89735d7-66c4-4235-8dd2-e1663acd577c)
![image](https://github.com/voxel51/fiftyone/assets/1567200/d6fcff8e-9def-4847-94c4-800d4382f798)

**Comment by twmht** [comment]
ok.

This works for me (https://github.com/voxel51/fiftyone/issues/1763)
