### ISSUE TITLE
Errors with importing fiftyone as fo

### ISSUE THREAD

**Issue by Caulac2006** [voxel51/fiftyone#3420]
### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 16.04): Window 7
-   **Python version** (`python --version`): python--3.7.0
-   **FiftyOne version** (`fiftyone --version`):
-   **FiftyOne installed from** (pip or source):

### Commands to reproduce

import fiftyone as fo

```
# commands here
D:\Lamondima\venv\Scripts\python.exe D:/Lamondima/main.py
Subprocess ['D:\\Lamondima\\venv\\lib\\site-packages\\fiftyone\\db\\bin\\mongod.exe', '--dbpath', 'C:\\Users\\hoan\\.fiftyone\\var\\lib\\mongo', '--logpath', 'C:\\Users\\hoan\\.fiftyone\\var\\lib\\mongo\\log\\mongo.log', '--port', '0'] exited with error -1073741511:
Traceback (most recent call last):
  File "D:/Lamondima/main.py", line 1, in <module>
    import fiftyone as fo
  File "D:\Lamondima\venv\lib\site-packages\fiftyone\__init__.py", line 25, in <module>
    from fiftyone.__public__ import *
  File "D:\Lamondima\venv\lib\site-packages\fiftyone\__public__.py", line 15, in <module>
    _foo.establish_db_conn(config)
  File "D:\Lamondima\venv\lib\site-packages\fiftyone\core\odm\database.py", line 200, in establish_db_conn
    port = _db_service.port
  File "D:\Lamondima\venv\lib\site-packages\fiftyone\core\service.py", line 276, in port
    return self._wait_for_child_port()
  File "D:\Lamondima\venv\lib\site-packages\fiftyone\core\service.py", line 170, in _wait_for_child_port
    return find_port()
  File "D:\Lamondima\venv\lib\site-packages\retrying.py", line 56, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "D:\Lamondima\venv\lib\site-packages\retrying.py", line 257, in call
    return attempt.get(self._wrap_exception)
  File "D:\Lamondima\venv\lib\site-packages\retrying.py", line 301, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "D:\Lamondima\venv\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "D:\Lamondima\venv\lib\site-packages\retrying.py", line 251, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "D:\Lamondima\venv\lib\site-packages\fiftyone\core\service.py", line 158, in find_port
    recursive=True
  File "D:\Lamondima\venv\lib\site-packages\psutil\__init__.py", line 277, in wrapper
    raise NoSuchProcess(self.pid, self._name, msg=msg)
psutil.NoSuchProcess: process no longer exists (pid=2428)

Process finished with exit code 1


### Describe the problem
I am currently using pycharm 2021 3.3 with python version 3.7.0. When I install fiftyone package, it says "the package has successfully been installed", but when I import it in my project, It cannot be excecuted with these problems. I tried to install Microsoft Visual C++ Redistributable 2015, using all types of method including uninstalling the applications and Pycharm, but none of them worked, I am realy desperate right now=(((. Please help me.
### Other info/logs
*Please contact me ASAP=((((. I will be very grateful

**Comment by benjaminpkane** [comment]
Hi @Caulac2006 

The MongoDB binary provided by fiftyone is failing to start for some reason.  Running the executable in `path\to\fiftyone\db\`  manually will show more information.

But I definitely recommend [configuring your own MongoDB connection](https://docs.voxel51.com/user_guide/config.html#configuring-a-mongodb-connection) as an alternative. One benefit is much faster import times of fiftyone.

**Comment by Caulac2006** [comment]
Hi @benjaminpkane 
I did run the mongod.exe file in my folder, but it said ‘the procedure entry point BCryptHash not found in the dynamic link bcrypt.dll’. I clicked properties the mongod.exe and it is currently version 5.0.4, while I am using window7, how can I use the older version of it that can be compatible.

**Comment by benjaminpkane** [comment]
FiftyOne supports MongoDB versions `>=4.4`. But it may be given your version of Windows, you'll have to set that up [manually](https://docs.voxel51.com/user_guide/config.html#configuring-a-mongodb-connection). I'm not sure if what versions of Windows MongoDB has support for, though.
