### ISSUE TITLE
[BUG] Windows: Cannot connect to session server

### ISSUE THREAD

**Issue by Caulac2006** [voxel51/fiftyone#3484]
### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 16.04): Window10 64bit
-   **Python version** (`python --version`):3.11.4
-   **FiftyOne version** (`fiftyone --version`):0.21.6
-   **FiftyOne installed from** (pip or source): pycharm using interpreter

### Commands to reproduce

As thoroughly as possible, please provide the Python and/or shell commands used to encounter the issue. Application steps can be described in the next section.

```
# commands here
```
import fiftyone as fo
import fiftyone.brain as fob
import json
import numpy as np
from glob import glob
import os

def main():
    dataset=fo.load_dataset('AIChallenge')
    dataset.persistent=True
    for sample in dataset:
        _, sample['video'], sample['frameid'] = sample['filepath'][:-4].rsplit('\\',2)
        sample.save()
    all_keyframe = glob('D:\\AnhAIchallenge\\keyframes\\*\\*.jpg')
    video_keyframe_dict = {}
    all_video = glob('D:\\AnhAIchallenge\\keyframes\\*')
    all_video = [v.rsplit('\\',1)[-1] for v in all_video]
    for kf in all_keyframe:
        _, vid, kf = kf[:-4].rsplit('\\',2)
        if vid not in video_keyframe_dict.keys():
            video_keyframe_dict[vid]= [kf]
        else:
            video_keyframe_dict[vid].append(kf)
    for k, v in video_keyframe_dict.items():
        video_keyframe_dict[k] = sorted(v)
    embedding_dict={}
    for v in all_video:
        clip_path=f'D:\\clip-features-vit-b32\\{v}.npy'
        a=np.load(clip_path)
        embedding_dict[v]={}
        for i,k in enumerate(video_keyframe_dict[v]):
            embedding_dict[v][k]=a[i]
    clip_embeddings = []
    for sample in dataset:
        clip_embedding = embedding_dict[sample['video']][sample['frameid']]
        clip_embeddings.append(clip_embedding)
    fob.compute_similarity(
        dataset,
        model="clip-vit-base32-torch",  # store model's name for future use
        embeddings=clip_embeddings,  # precomputed image embeddings
        brain_key="img_sim2",
    )

    dataset.save()
    session=fo.launch_app(dataset, auto=False, desktop=True)
    session.wait()

if __name__=="__main__":
    main()

### Describe the problem

I was trying to launch desktop app using "clip-vit-base32-torch" model; in fact, I managed to download the model; however, whenever I tried to run the program, the error kept occuring. I did try to give permission for fiftyone.exe to access the port and check for the programs running simultaneously but there was nothing. I don't really know what to do now to launch the desktop app in pycharm. Please help me, I will be very grateful. Please contact me ASAP. 

**This is the error:**

C:\Users\Dell\PycharmProjects\pythonProject\venv\Scripts\python.exe C:\Users\Dell\PycharmProjects\pythonProject\main.py 
Traceback (most recent call last):
  File "C:\Users\Dell\PycharmProjects\pythonProject\main.py", line 49, in <module>
    main()
  File "C:\Users\Dell\PycharmProjects\pythonProject\main.py", line 45, in main
    session=fo.launch_app(dataset, auto=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\PycharmProjects\pythonProject\venv\Lib\site-packages\fiftyone\core\session\session.py", line 197, in launch_app
    _session = Session(
               ^^^^^^^^
  File "C:\Users\Dell\PycharmProjects\pythonProject\venv\Lib\site-packages\fiftyone\core\session\session.py", line 427, in __init__
    _register_session(self)
  File "C:\Users\Dell\PycharmProjects\pythonProject\venv\Lib\site-packages\fiftyone\core\session\session.py", line 1205, in _register_session
    _server_services[session.server_port] = fos.ServerService(
                                            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\PycharmProjects\pythonProject\venv\Lib\site-packages\fiftyone\core\service.py", line 305, in __init__
    super().__init__()
  File "C:\Users\Dell\PycharmProjects\pythonProject\venv\Lib\site-packages\fiftyone\core\service.py", line 80, in __init__
    self.start()
  File "C:\Users\Dell\PycharmProjects\pythonProject\venv\Lib\site-packages\fiftyone\core\service.py", line 325, in start
    self._wait_for_child_port(port=port)
  File "C:\Users\Dell\PycharmProjects\pythonProject\venv\Lib\site-packages\fiftyone\core\service.py", line 170, in _wait_for_child_port
    return find_port()
           ^^^^^^^^^^^
  File "C:\Users\Dell\PycharmProjects\pythonProject\venv\Lib\site-packages\retrying.py", line 56, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\PycharmProjects\pythonProject\venv\Lib\site-packages\retrying.py", line 266, in call
    raise attempt.get()
          ^^^^^^^^^^^^^
  File "C:\Users\Dell\PycharmProjects\pythonProject\venv\Lib\site-packages\retrying.py", line 301, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "C:\Users\Dell\PycharmProjects\pythonProject\venv\Lib\site-packages\six.py", line 719, in reraise
    raise value
  File "C:\Users\Dell\PycharmProjects\pythonProject\venv\Lib\site-packages\retrying.py", line 251, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\PycharmProjects\pythonProject\venv\Lib\site-packages\fiftyone\core\service.py", line 168, in find_port
    raise ServiceListenTimeout(etau.get_class_name(self), port)
fiftyone.core.service.ServiceListenTimeout: fiftyone.core.service.ServerService failed to bind to port 5151

Process finished with exit code 1

### What areas of FiftyOne does this bug affect?

-   [ x] `App`: FiftyOne application issue
-   [ ] `Core`: Core Python library issue
-   [ x] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

**Comment by benjaminpkane** [comment]
Hi @Caulac2006. This usually means that the session server is unable to start. The best way to debug is to try to start the server directly with `python C:\Users\Dell\PycharmProjects\pythonProject\venv\Lib\site-packages\fiftyone\server\main.py`.

**Comment by benjaminpkane** [comment]
The below will start the server directly:
```
python C:\Users\Dell\PycharmProjects\pythonProject\venv\Lib\site-packages\fiftyone\server\main.py
```

It should reveal any issues with the installtion
