### ISSUE TITLE
Installing Fiftyone on Ubuntu 23.10

### ISSUE THREAD

**Issue by AISTALK** [voxel51/fiftyone#3928]
### System information

-   **OS Platform and Distribution**:
Distributor ID:	Ubuntu
Description:	Ubuntu 23.10
Release:	23.10
Codename:	mantic

-   **Python version** (`python --version`):
Python 3.11.6

-   **FiftyOne version** (`fiftyone --version`):
(venv) aitalent@aitalent-1-0:~/Code/fiftyone$ fiftyone --version
Traceback (most recent call last):
  File "/home/aitalent/Code/fiftyone/venv/lib/python3.11/site-packages/fiftyone/core/odm/database.py", line 200, in establish_db_conn
    _db_service = fos.DatabaseService()
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/aitalent/Code/fiftyone/venv/lib/python3.11/site-packages/fiftyone/core/service.py", line 80, in __init__
    self.start()
  File "/home/aitalent/Code/fiftyone/venv/lib/python3.11/site-packages/fiftyone/core/service.py", line 209, in start
    super().start()
  File "/home/aitalent/Code/fiftyone/venv/lib/python3.11/site-packages/fiftyone/core/service.py", line 118, in start
    + self.command,
      ^^^^^^^^^^^^
  File "/home/aitalent/Code/fiftyone/venv/lib/python3.11/site-packages/fiftyone/core/service.py", line 238, in command
    DatabaseService.find_mongod(),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aitalent/Code/fiftyone/venv/lib/python3.11/site-packages/fiftyone/core/service.py", line 286, in find_mongod
    raise ServiceExecutableNotFound("Could not find `mongod`")
fiftyone.core.service.ServiceExecutableNotFound: Could not find `mongod`

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aitalent/Code/fiftyone/venv/bin/fiftyone", line 5, in <module>
    from fiftyone.core.cli import main
  File "/home/aitalent/Code/fiftyone/venv/lib/python3.11/site-packages/fiftyone/__init__.py", line 25, in <module>
    from fiftyone.__public__ import *
  File "/home/aitalent/Code/fiftyone/venv/lib/python3.11/site-packages/fiftyone/__public__.py", line 16, in <module>
    _foo.establish_db_conn(config)
  File "/home/aitalent/Code/fiftyone/venv/lib/python3.11/site-packages/fiftyone/core/odm/database.py", line 206, in establish_db_conn
    raise FiftyOneConfigError(
fiftyone.core.config.FiftyOneConfigError: MongoDB could not be installed on your system. Please define a `database_uri` in your `fiftyone.core.config.FiftyOneConfig` to connect to yourown MongoDB instance or cluster 
(venv) aitalent@aitalent-1-0:~/Code/fiftyone$

-   **FiftyOne installed from** (pip or source):
pip

### Commands to reproduce
pip install fiftyone
pip install "fiftyone[desktop]"

#app.py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
session = fo.launch_app(dataset, desktop=True)

(venv) aitalent@aitalent-1-0:~/Code/fiftyone$ /home/aitalent/Code/fiftyone/venv/bin/python /home/aitalent/Code/fiftyone/app.py

### Describe the problem
It is not installing on my current OS.

### Other info/logs
Fresh Ubuntu 23.10, has nothing here except vscode and telegram.
pip install --upgrade pip setuptools wheel did not help

**Comment by benjaminpkane** [comment]
Hi @AISTALK. You are correct, we have not yet added support for the built-in database on Ubuntu 23. If you can confirm that the [Ubuntu 22](https://github.com/voxel51/fiftyone/blob/0a8fefc856337aae8690e8740d111d80be04abe7/package/db/setup.py#L77) downloads work, I can add the entry.

The alternative is [configuring your MongoDB connection](https://docs.voxel51.com/user_guide/config.html#configuring-a-mongodb-connection)

**Comment by AISTALK** [comment]
I'd like to help, but I'm quite newbie and I don't know how to use this setup.py script after modifying it...
At least don't know what to do with missing setuptools folder, so if you'll give me at least simplest instruction, I'll be glad to test!

**Comment by benjaminpkane** [comment]
Hi @AISTALK. No worries! I went ahead and tested Ubuntu 23 in #3936. `pip install -U fiftyone-db` should resolve the issue
