### ISSUE TITLE
[BUG] Evaluations method(s) do not support embedded label fields

### ISSUE THREAD

**Issue by benjaminpkane** [voxel51/fiftyone#3996]
In at least the coco detection evaluation method, schema related code prevents evaluation of labels in dynamic embedded documents

```python
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart", max_samples=1)

for sample in dataset:
    sample["embedded"] = fo.DynamicEmbeddedDocument(
        ground_truth=sample.ground_truth, predictions=sample.predictions
    )
    sample.save()

dataset.delete_sample_field("ground_truth")
dataset.delete_sample_field("predictions")

dataset.add_dynamic_sample_fields()

dataset.evaluate_detections(
    "embedded.predictions", gt_field="embedded.ground_truth"
)
``` 

Out:
```python
Traceback (most recent call last):
  File "/Users/ben/code/fiftyone/fiftyone/core/document.py", line 69, in __getitem__
    return self.get_field(field_name)
  File "/Users/ben/code/fiftyone/fiftyone/core/sample.py", line 99, in get_field
    return super().get_field(field_name)
  File "/Users/ben/code/fiftyone/fiftyone/core/document.py", line 753, in get_field
    raise AttributeError(
AttributeError: Field 'embedded.ground_truth' was not selected on this SampleView

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ben/code/scratch/eval.py", line 18, in <module>
    dataset.evaluate_detections(
  File "/Users/ben/code/fiftyone/fiftyone/core/collections.py", line 3255, in evaluate_detections
    return foue.evaluate_detections(
  File "/Users/ben/code/fiftyone/fiftyone/utils/eval/detection.py", line 195, in evaluate_detections
    doc_matches = eval_method.evaluate(doc, eval_key=eval_key)
  File "/Users/ben/code/fiftyone/fiftyone/utils/eval/coco.py", line 157, in evaluate
    gts = sample_or_frame[self.gt_field]
  File "/Users/ben/code/fiftyone/fiftyone/core/sample.py", line 60, in __getitem__
    return super().__getitem__(field_name)
  File "/Users/ben/code/fiftyone/fiftyone/core/document.py", line 71, in __getitem__
    raise KeyError(e.args[0])
KeyError: "Field 'embedded.ground_truth' was not selected on this SampleView"
```

**Comment by brimoor** [comment]
Resolved by https://github.com/voxel51/fiftyone/pull/4002
