### ISSUE TITLE
[INSTALL][ubuntu Ubuntu 20.04 LTS] fiftyone.core.config.FiftyOneConfigError: MongoDB could not be installed on your system. Please define a `database_uri` in your `fiftyone.core.config.FiftyOneConfig` to connect to yourown MongoDB instance or cluster

### ISSUE THREAD

**Issue by lynshwoo2022** [voxel51/fiftyone#4216]
### System information

-   **OS Platform and Distribution** : Linux ubuntu Ubuntu 20.04 LTS
-   **Python version** (`python --version`): 3.8
-   **FiftyOne version** (`fiftyone --version`): 
![image](https://github.com/voxel51/fiftyone/assets/121412945/3a67e317-c730-4f2f-a03b-3413d9434d27)
![image](https://github.com/voxel51/fiftyone/assets/121412945/a0fb1f56-fa7d-4cbe-8dca-bac0d9d046ec)

-   **FiftyOne installed from** (pip or source): pip

### Commands to reproduce

first
```shell
pip install fiftyone
```
then
```python
import fiftyone
```
or
```
fiftyone --version
```

### Describe the problem
error message
```shell
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch1.12/lib/python3.8/site-packages/fiftyone/core/odm/database.py", line 200, in establish_db_conn
    _db_service = fos.DatabaseService()
  File "/home/ubuntu/anaconda3/envs/pytorch1.12/lib/python3.8/site-packages/fiftyone/core/service.py", line 80, in __init__
    self.start()
  File "/home/ubuntu/anaconda3/envs/pytorch1.12/lib/python3.8/site-packages/fiftyone/core/service.py", line 209, in start
    super().start()
  File "/home/ubuntu/anaconda3/envs/pytorch1.12/lib/python3.8/site-packages/fiftyone/core/service.py", line 118, in start
    + self.command,
  File "/home/ubuntu/anaconda3/envs/pytorch1.12/lib/python3.8/site-packages/fiftyone/core/service.py", line 238, in command
    DatabaseService.find_mongod(),
  File "/home/ubuntu/anaconda3/envs/pytorch1.12/lib/python3.8/site-packages/fiftyone/core/service.py", line 286, in find_mongod
    raise ServiceExecutableNotFound("Could not find `mongod`")
fiftyone.core.service.ServiceExecutableNotFound: Could not find `mongod`

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "download.py", line 32, in <module>
    import fiftyone
  File "/home/ubuntu/anaconda3/envs/pytorch1.12/lib/python3.8/site-packages/fiftyone/__init__.py", line 25, in <module>
    from fiftyone.__public__ import *
  File "/home/ubuntu/anaconda3/envs/pytorch1.12/lib/python3.8/site-packages/fiftyone/__public__.py", line 16, in <module>
    _foo.establish_db_conn(config)
  File "/home/ubuntu/anaconda3/envs/pytorch1.12/lib/python3.8/site-packages/fiftyone/core/odm/database.py", line 206, in establish_db_conn
    raise FiftyOneConfigError(
fiftyone.core.config.FiftyOneConfigError: MongoDB could not be installed on your system. Please define a `database_uri` in your `fiftyone.core.config.FiftyOneConfig` to connect to yourown MongoDB instance or cluster 
```
### Other info/logs
already installed pymongo or fiftyone-db

**Comment by benjaminpkane** [comment]
Hi @lynshwoo2022. Can you share your `/etc/os-release` file? Ubuntu 20.04 should be supported.

```shell
cat /etc/os-release
``` 

Also, a workaround is to install `fiftyone-db==0.4`

**Comment by lynshwoo2022** [comment]
thanks，i'll try `fiftyone-db==0.4`
ubuntu version：
![image](https://github.com/voxel51/fiftyone/assets/121412945/42959877-eb80-44ac-963a-8569f502b7e7)

**Comment by lynshwoo2022** [comment]
fiftyone-db==0.4 works, confusing, why ubuntu20 is not supported by up-to-date version

**Comment by benjaminpkane** [comment]
ubuntu20 is supported. You may be working in a restricted network, which prevented the MongoDB download. The URL is found [here].(https://github.com/voxel51/fiftyone/blob/e53596a757ed202857f477b83300f4cc42c6101e/package/db/setup.py#L73)

fiftyone-db==0.4 does not require downloading on install, but limits support to only ubuntu20 and ubuntu18
