### ISSUE TITLE
[INSTALL] Cannot launch QuickStart

### ISSUE THREAD

**Issue by tfaehse** [voxel51/fiftyone#4880]
### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 16.04): macOS 15.0 (ARM)
-   **Python version** (`python --version`): 3.9-3.11, installed via miniconda
-   **FiftyOne version** (`fiftyone --version`): 1.0.0
-   **FiftyOne installed from** (pip or source): pip

### Commands to reproduce

As thoroughly as possible, please provide the Python and/or shell commands used to encounter the issue.

```
fiftyone quickstart
```

### Describe the problem

Stack trace:

```
Traceback (most recent call last):
  File "/Users/USER/miniforge3/envs/fo/bin/fiftyone", line 8, in <module>
    sys.exit(main())
  File "/Users/USER/miniforge3/envs/fo/lib/python3.9/site-packages/fiftyone/core/cli.py", line 4636, in main
    args.execute(args)
  File "/Users/USER/miniforge3/envs/fo/lib/python3.9/site-packages/fiftyone/core/cli.py", line 4619, in <lambda>
    parser.set_defaults(execute=lambda args: command.execute(parser, args))
  File "/Users/USER/miniforge3/envs/fo/lib/python3.9/site-packages/fiftyone/core/cli.py", line 174, in execute
    _, session = fouq.quickstart(
  File "/Users/USER/miniforge3/envs/fo/lib/python3.9/site-packages/fiftyone/utils/quickstart.py", line 44, in quickstart
    return _quickstart(port, address, remote, desktop)
  File "/Users/USER/miniforge3/envs/fo/lib/python3.9/site-packages/fiftyone/utils/quickstart.py", line 50, in _quickstart
    return _launch_app(dataset, port, address, remote, desktop)
  File "/Users/USER/miniforge3/envs/fo/lib/python3.9/site-packages/fiftyone/utils/quickstart.py", line 60, in _launch_app
    session = fos.launch_app(
TypeError: launch_app() got an unexpected keyword argument 'desktop'
```
### Other info/logs

I originally tried to load my own dataset (a small YOLO one) via python code, but I always just get a window in my browser with an unspecified "TypeError: Load failed". So I tried the demo (`fiftyone quickstart`), and it looks like my installation is wrong somehow? I went into the code a bit, it looks like session's launch_app wants no desktop argument at all. If I just remove that one in quickstart's launch_app() call the error is gone, but then I go back to my original issue with my own dataset and get a "TypeError: Load failed".

I've tried a few different python versions but both errors are persistent. I'd appreciate any help, or even some help in enabling some more verbose output/pointing me to where logs are stored. Thanks!

PS: Considering that no one else has encountered this issue so far I've put this as an installation issue, hope that works.

**Comment by brimoor** [comment]
Hi @tfaehse 👋 

Oops, thanks for catching this bug 🤦

I've patched this in #4888 and the fix will be available in `fiftyone>=1.0.1`.

In the meantime, you can launch quickstart via Python like so:

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
session = fo.launch_app(dataset)
```
