### ISSUE TITLE
[BUG] Can't load Detections (on develop)

### ISSUE THREAD

**Issue by lethosor** [voxel51/fiftyone#567]
Specifically: works on 796288f5b0e9ddfe4606587a016d0f069201f8f1, broken on 54b3f9708f73bf147da36eba43b133e19d1ee04f
After #561 was merged, I am getting the following server error when loading any dataset containing a `Detections` object:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File ".../lib/python3.6/site-packages/socketio/server.py", line 696, in _handle_event_internal
    binary=binary))
  File ".../lib/python3.6/site-packages/socketio/server.py", line 607, in _send_packet
    encoded_packet = pkt.encode()
  File ".../lib/python3.6/site-packages/socketio/packet.py", line 71, in encode
    encoded_packet += self.json.dumps(data, separators=(',', ':'))
  File ".../fiftyone/server/json_util.py", line 57, in dumps
    json_util.dumps(*args, **kwargs), parse_constant=lambda c: c
  File ".../lib/python3.6/site-packages/bson/json_util.py", line 383, in dumps
    return json.dumps(_json_convert(obj, json_options), *args, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File ".../lib/python3.6/site-packages/simplejson/encoder.py", line 275, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File ".../lib/python3.6/site-packages/simplejson/encoder.py", line 357, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte
```

Code to reproduce:
```python
import fiftyone as fo
sample = fo.Sample(
    filepath="/some/path.png",
    object=fo.Detections(detections=[
        fo.Detection(label="x", bounding_box=[0, 0, 1, 1])
    ])
)
dataset = fo.Dataset()
dataset.add_sample(sample)
session = fo.launch_app(dataset, remote=True)
```

**Comment by lethosor** [comment]
Possibly already fixed by #568
