### ISSUE TITLE
[BUG] App error when filtering a Classifications field of a video dataset in the App

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#627]
I get an App error when trying to apply a filter to the `gt` field of the attached dataset in the App

[pip-175k-sample.zip](https://github.com/voxel51/fiftyone/files/5425796/pip-175k-sample.zip)

Here's how to load the dataset:

```py
import fiftyone as fo

dataset = fo.Dataset.from_dir(
    "/path/to/pip-175k-sample",
    fo.types.FiftyOneDataset
)

session = fo.launch_app(dataset)
```

For example, I expand the label filter for `gt` and then uncheck "Show no confidence".

Here's the error:

```
Traceback (most recent call last):
  File "main.py", line 108, in wrapper
    return func(self, *args, **kwargs)
  File "main.py", line 196, in on_update
    self.state = fos.StateDescriptionWithDerivables.from_dict(
  File "/home/brian/env/fifty3/lib/python3.8/site-packages/fiftyone/core/state.py", line 175, in from_dict
    return super().from_dict(d, **kwargs)
  File "/home/brian/env/fifty3/lib/python3.8/site-packages/fiftyone/core/state.py", line 122, in from_dict
    return cls(
  File "/home/brian/env/fifty3/lib/python3.8/site-packages/fiftyone/core/state.py", line 159, in __init__
    extended_view = extended_view.add_stage(
  File "/home/brian/env/fifty3/lib/python3.8/site-packages/fiftyone/core/collections.py", line 392, in add_stage
    return self._add_view_stage(stage)
  File "/home/brian/env/fifty3/lib/python3.8/site-packages/fiftyone/core/view.py", line 371, in _add_view_stage
    stage.validate(self)
  File "/home/brian/env/fifty3/lib/python3.8/site-packages/fiftyone/core/stages.py", line 631, in validate
    sample_collection.validate_field_type(
  File "/home/brian/env/fifty3/lib/python3.8/site-packages/fiftyone/core/collections.py", line 312, in validate_field_type
    raise ValueError("Field '%s' does not exist" % field_name)
ValueError: Field 'gt' does not exist
```

**Comment by lethosor** [comment]
May be related to #208 - does this occur in a local session?

**Comment by brimoor** [comment]
This happens in a local session

**Comment by benjaminpkane** [comment]
Looking into it

**Comment by brimoor** [comment]
This only happens when filtering sample-level `gt` and not when filtering frame-level `gt_objects`. The latter does work

**Comment by benjaminpkane** [comment]
I found the issue, I can push a fix if we would like to have patch release before `0.6.4`. If not, `video-3.0` will resolve this.

**Comment by brimoor** [comment]
Ok cool. Patch is not critical

**Comment by benjaminpkane** [comment]
For reference, it is a client side issue. https://github.com/voxel51/fiftyone/blob/5cfe821d3e0ff32216f4eb0c0c4a7ddced637b81/electron/app/components/Filter.tsx#L446

The App still assumes all label filtering is only for frame labels. My mistake.
