### ISSUE TITLE
[BUG] Error using label filters in the App

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#660]
On fiftyone v0.6.4, with the dataset below open:

```py
import fiftyone as fo

# Download from https://drive.google.com/file/d/1t8nAEFOw-khYwbaOLP5IYMq6mbvJY06Y
DATASET_PATH = "/path/to/deepfakes"

dataset = fo.Dataset.from_dir(DATASET_PATH, dataset_type=fo.types.FiftyOneDataset)
session = fo.launch_app(dataset)
```

I get the error below when trying to use any label filter in the App. For example, when trying to uncheck `Show no confidence` for the `ground_truth` field:

```
Server Error

An exception has been raised by the server. Your session has been reverted to its previous state.

Traceback (most recent call last):
  File "main.py", line 112, in wrapper
    return func(self, *args, **kwargs)
  File "main.py", line 273, in on_get_statistics
    return fos.DatasetStatistics(view).serialize()["stats"]
  File "/Users/Brian/dev/env/tmp3/lib/python3.6/site-packages/fiftyone/core/state.py", line 176, in __init__
    self.stats = view.aggregate(aggregations)
  File "/Users/Brian/dev/env/tmp3/lib/python3.6/site-packages/fiftyone/core/collections.py", line 154, in aggregate
    result_d = next(self._aggregate([{"$facet": pipelines}]))
  File "/Users/Brian/dev/env/tmp3/lib/python3.6/site-packages/fiftyone/core/view.py", line 281, in _aggregate
    s.validate(self)
  File "/Users/Brian/dev/env/tmp3/lib/python3.6/site-packages/fiftyone/core/stages.py", line 672, in validate
    sample_collection.validate_fields_exist(self.field)
  File "/Users/Brian/dev/env/tmp3/lib/python3.6/site-packages/fiftyone/core/collections.py", line 368, in validate_fields_exist
    raise ValueError("Field '%s' does not exist" % field_name)
ValueError: Field 'ground_truth' does not exist
```

**Comment by brimoor** [comment]
@benjaminpkane This looks to be specific to sample-level fields of video datasets

**Comment by benjaminpkane** [comment]
I have this fixed, but am working through some related problems. Will post PR today/tomorrow.
