### ISSUE TITLE
[BUG] Server error when trying to render an empty graph

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#688]
```py
import fiftyone as fo

dataset, session = fo.quickstart()

session.view = dataset.exists("uniqueness", False)  # error
```

yields the following error:

```
Server Error

An exception has been raised by the server. Your session has been reverted to its previous state.

Traceback (most recent call last):
  File "main.py", line 131, in wrapper
    result = await func(self, *args, **kwargs)
  File "main.py", line 294, in on_message
    await event(**message)
  File "main.py", line 658, in on_distributions
    self.sample_collection, view, group
  File "main.py", line 666, in _get_distributions
    await _numeric_distribution_pipelines(coll, view, pipeline)
  File "main.py", line 709, in _numeric_distribution_pipelines
    field_bounds = bounds[sub_pipeline][0]
IndexError: list index out of range
```

**Comment by benjaminpkane** [comment]
Addressed in #684
