### ISSUE TITLE
[BUG] Can't create Limit(n) stage for n >= 1000 in App

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#754]
Trying to create a `Limit(n)` stage from the App with `n >= 1000` fails on develop. The stack trace is below.

In the view bar `Limit(1234)` is converted to `Limit(1,234)` which suggests that there's a string vs numeric issue going on.

`session.view = dataset.limit(1234)` works, however, and the view bar shows `Limit(1234)`.

```
Server Error

An exception has been raised by the server. Your session has been reverted to its previous state.

Traceback (most recent call last):
  File "main.py", line 182, in wrapper
    result = await func(self, *args, **kwargs)
  File "main.py", line 445, in on_message
    await event(self, **message)
  File "main.py", line 533, in on_page
    pipeline = view._pipeline(hide_frames=True, squash_frames=True)
  File "/Users/Brian/dev/fiftyone/fiftyone/core/view.py", line 399, in _pipeline
    _pipeline.extend(s.to_mongo(self))
  File "/Users/Brian/dev/fiftyone/fiftyone/core/stages.py", line 1229, in to_mongo
    if self._limit <= 0:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
```

**Comment by benjaminpkane** [comment]
Clear your cache maybe? I do not have this issue.

To be certain:
```
cd app
yarn install && yarn build-web
```
