### ISSUE TITLE
[BUG] Constantly crashing, maybe due to anaconda ?

### ISSUE THREAD

**Issue by Legor** [voxel51/fiftyone#802]
### System information

-   **Windows 20**:
-   **installed from pip**:
-   **fiftyone v0.7.1.4, Voxel51, Inc.**:
-   **Python 3.9.1**:

### Commands to reproduce
In IPython shell:
```
import fiftyone as fo
ds = fo.Dataset(name='test')
```

### Describe the problem

I wanted to play around with fiftyone and was just trying to use it in an IPython shell for the beginning. I followed my usual routine: set up a new conda env and pip install all I need. When trying out simple things with fo in the shell, IPython crashes and terminates completely, however this does not happen with the same commands and not all the time but unforeseeable e.g, when creating a dataset, when creating a sample, when creating metadata or when just accessing an attribute of a dataset or sample.  I can't really make much of the outputted exception messages but I get the feeling that it maybe related to conda because there isn't really a installation instruction for conda users either.

### Other info / logs

```
Traceback (most recent call last):
  File "c:\users\gordo\miniconda3\envs\fo_test\lib\site-packages\IPython\terminal\ptutils.py", line 113, in get_completions
    yield from self._get_completions(body, offset, cursor_position, self.ipy_completer)
  File "c:\users\gordo\miniconda3\envs\fo_test\lib\site-packages\IPython\terminal\ptutils.py", line 129, in _get_completions
    for c in completions:
  File "c:\users\gordo\miniconda3\envs\fo_test\lib\site-packages\IPython\core\completer.py", line 438, in _deduplicate_completions
    completions = list(completions)
  File "c:\users\gordo\miniconda3\envs\fo_test\lib\site-packages\IPython\core\completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "c:\users\gordo\miniconda3\envs\fo_test\lib\site-packages\IPython\core\completer.py", line 1861, in _completions
    matched_text, matches, matches_origin, jedi_matches = self._complete(
  File "c:\users\gordo\miniconda3\envs\fo_test\lib\site-packages\IPython\core\completer.py", line 2029, in _complete
    completions = self._jedi_matches(
  File "c:\users\gordo\miniconda3\envs\fo_test\lib\site-packages\IPython\core\completer.py", line 1373, in _jedi_matches
    interpreter = jedi.Interpreter(
  File "c:\users\gordo\miniconda3\envs\fo_test\lib\site-packages\jedi\api\__init__.py", line 725, in __init__
    super().__init__(code, environment=environment,
TypeError: __init__() got an unexpected keyword argument 'column'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\gordo\miniconda3\envs\fo_test\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\gordo\miniconda3\envs\fo_test\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\gordo\miniconda3\envs\fo_test\Scripts\ipython.exe\__main__.py", line 7, in <module>
    sys.exit(start_ipython())
  File "c:\users\gordo\miniconda3\envs\fo_test\lib\site-packages\IPython\__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "c:\users\gordo\miniconda3\envs\fo_test\lib\site-packages\traitlets\config\application.py", line 845, in launch_instance
    app.start()
  File "c:\users\gordo\miniconda3\envs\fo_test\lib\site-packages\IPython\terminal\ipapp.py", line 356, in start
    self.shell.mainloop()
  File "c:\users\gordo\miniconda3\envs\fo_test\lib\site-packages\IPython\terminal\interactiveshell.py", line 564, in mainloop
    self.interact()
  File "c:\users\gordo\miniconda3\envs\fo_test\lib\site-packages\IPython\terminal\interactiveshell.py", line 547, in interact
    code = self.prompt_for_code()
  File "c:\users\gordo\miniconda3\envs\fo_test\lib\site-packages\IPython\terminal\interactiveshell.py", line 473, in prompt_for_code
    text = self.pt_app.prompt(
  File "c:\users\gordo\miniconda3\envs\fo_test\lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 1013, in prompt
    return self.app.run(set_exception_handler=set_exception_handler)
  File "c:\users\gordo\miniconda3\envs\fo_test\lib\site-packages\prompt_toolkit\application\application.py", line 825, in run
    return loop.run_until_complete(
  File "c:\users\gordo\miniconda3\envs\fo_test\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\users\gordo\miniconda3\envs\fo_test\lib\site-packages\prompt_toolkit\application\application.py", line 792, in run_async
    return await _run_async2()
  File "c:\users\gordo\miniconda3\envs\fo_test\lib\site-packages\prompt_toolkit\application\application.py", line 780, in _run_async2
    await self.cancel_and_wait_for_background_tasks()
  File "c:\users\gordo\miniconda3\envs\fo_test\lib\site-packages\prompt_toolkit\application\application.py", line 881, in cancel_and_wait_for_background_tasks
    await task
  File "c:\users\gordo\miniconda3\envs\fo_test\lib\site-packages\prompt_toolkit\buffer.py", line 1893, in new_coroutine
    await coroutine(*a, **kw)
  File "c:\users\gordo\miniconda3\envs\fo_test\lib\site-packages\prompt_toolkit\buffer.py", line 1722, in async_completer
    async for completion in self.completer.get_completions_async(
  File "c:\users\gordo\miniconda3\envs\fo_test\lib\site-packages\prompt_toolkit\completion\base.py", line 269, in get_completions_async
    async for completion in completer.get_completions_async(
  File "c:\users\gordo\miniconda3\envs\fo_test\lib\site-packages\prompt_toolkit\completion\base.py", line 196, in get_completions_async
    for item in self.get_completions(document, complete_event):
  File "c:\users\gordo\miniconda3\envs\fo_test\lib\site-packages\IPython\terminal\ptutils.py", line 116, in get_completions
    exc_type, exc_value, exc_tb = sys.exc_info()
NameError: name 'sys' is not defined

If you suspect this is an IPython 7.19.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [x] No. I cannot contribute a bug fix at this time.

**Comment by Legor** [comment]
I have an update to this issue. It seems the bug is not related to fiftyone but to the jedi autocompletion in IPython. A bit strange this never showed before, given that I use IPython regularly and also auto completion excessively. It has been discussed here as well: https://github.com/mne-tools/mne-python/issues/7315

**Comment by jasoncorso** [comment]
Great, thank you for the bug and the update.  Glad it's at least resolved from the FiftyOne standpoint!
