### ISSUE TITLE
[BUG] Launching different versions of the App remotely

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/fiftyone#831]
I was working in a remote Jupyter notebook and updated FiftyOne to 0.7.2. My local version was still on 0.7.1, and when I launched the App in the notebook I got the following error.

```
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/home/erich/sw/conda/envs/test/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/erich/sw/conda/envs/test/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/erich/sw/conda/envs/test/lib/python3.9/site-packages/fiftyone/core/client.py", line 108, in run_client
    io_loop.run_sync(connect)
  File "/home/erich/sw/conda/envs/test/lib/python3.9/site-packages/tornado/ioloop.py", line 530, in run_sync
    return future_cell[0].result()
  File "/home/erich/sw/conda/envs/test/lib/python3.9/site-packages/fiftyone/core/client.py", line 96, in connect
    self._data = self._HC_ATTR_TYPE.from_dict(
  File "/home/erich/sw/conda/envs/test/lib/python3.9/site-packages/fiftyone/core/state.py", line 126, in from_dict
    stage = fost.ViewStage._from_dict(stage_dict)
  File "/home/erich/sw/conda/envs/test/lib/python3.9/site-packages/fiftyone/core/stages.py", line 183, in _from_dict
    stage = view_stage_cls(**{k: v for (k, v) in d["kwargs"]})
TypeError: __init__() got an unexpected keyword argument 'tags'
```

**Comment by benjaminpkane** [comment]
I'm not sure how a version mismatch could cause in issue. The Jupyter notebook should be only using the remote install. Perhaps clear your cache?

You were using a `match_tags()` stage? It's parameter name was changed from `tags` to `tag`. Hmmm

**Comment by ehofesmann** [comment]
It just occurred when I installed the new version, it could very likely have been a cache issue. 

The strange thing is that I was only trying to visualize the entire dataset, there was no `match_tags()` stage

**Comment by brimoor** [comment]
I think this can be closed. We haven't been able to reproduce, right?

**Comment by benjaminpkane** [comment]
I haven't, closing.
