### ISSUE TITLE
[BUG] v0.7.2 migration fails on old dataset

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#837]
When trying to open an older dataset in v0.7.2, the `up` migration returns the error below.

> I spent a minute trying to figure out how to print the `dataset_dict` so I could document the current version, but the migration runs in a separate process so printing wasn't available. Then I ran with the fix below and lost the original version...

I was able to avoid this by replacing `dataset_dict["media_type"]` with `dataset_dict.get("media_type", None)`, and I could then load the resulting dataset in v0.7.2, but, I wonder if this error suggests that there's a missing migration somewhere between v0.6.5 and v0.72?

```
Traceback (most recent call last):
  File "main.py", line 182, in wrapper
    result = await func(self, *args, **kwargs)
  File "main.py", line 445, in on_message
    await event(self, **message)
  File "main.py", line 678, in on_set_dataset
    dataset = fod.load_dataset(dataset_name)
  File "/Users/Brian/dev/fiftyone/fiftyone/core/dataset.py", line 91, in load_dataset
    return Dataset(name, _create=False)
  File "/Users/Brian/dev/fiftyone/fiftyone/core/singleton.py", line 36, in __call__
    instance.__init__(name=name, _create=_create, *args, **kwargs)
  File "/Users/Brian/dev/fiftyone/fiftyone/core/dataset.py", line 232, in __init__
    ) = _load_dataset(name)
  File "/Users/Brian/dev/fiftyone/fiftyone/core/dataset.py", line 2598, in _load_dataset
    fomi.migrate_dataset_if_necessary(name, destination=focn.VERSION)
  File "/Users/Brian/dev/fiftyone/fiftyone/migrations/runner.py", line 71, in migrate_dataset_if_necessary
    runner.run(name)
  File "/Users/Brian/dev/fiftyone/fiftyone/migrations/runner.py", line 185, in run
    fcn(conn, dataset_name)
  File "/Users/Brian/dev/fiftyone/fiftyone/migrations/revisions/v0_7_2.py", line 14, in up
    if dataset_dict["media_type"] != "video":
KeyError: 'media_type'
```

**Comment by benjaminpkane** [comment]
`v0_6_2.py` adds `media_type` type to the document. I will try to reproduce the above, though.

**Comment by brimoor** [comment]
Sorry I think this happened because I had a bug when updating the migration framework that caused the updated document to not be committed to the database. I can no longer produce this.
